### ISSUE TITLE
[Generic] Its not working on Windows / XAMPP

### ISSUE THREAD

**Issue by Sarjuuk** [Sarjuuk/aowow#101]
I already know, all right.
As a rule of thumb. 
* When the CLI stops without any info, assume it broke. 
* Enable debug in the config-table and check the errors-table for information.
* If you can't contribute new information, please refrain from creating new tickets.

Here is a couple of things you might want to try out.

* **memory_limit** ~~unless you are great and compiled php as 64bit for yourself your technical limit is 2GB. Set it to something lower or php will pick a value for you, most likely 2MB (yes, thats an M)~~
changed in dde09a8a023a8f0dae3a19a0b31b07ee1cdad863. If this issue persist you can always try to set it to something appropriate. 

* **appcrash**
  * ~~try reducing [DBC::$bufferSize](https://github.com/TrinityCore/aowow/blob/master/setup/tools/dbc.class.php#L252) from 1000 entries to 500~~ added in dde09a8a023a8f0dae3a19a0b31b07ee1cdad863
  * try to revert d63ac946f6c483f9b5f8966a0dc6b8430361a8c1
  * consider downgrading from php7.1 to php5.5 (if you are using xampp you weren't going to publish it anyway .. or at least i hope so)

Please use this ticket if you are having issues using Windows.

**Comment by Dokman** [comment]
@Sarjuuk it0s not better to get the OS and then set a switch to change the variable for every OS?

**Comment by Sarjuuk** [comment]
The things above are fighting symptoms, not causes. I'd prefer to find the cause before implementing changes.

**Comment by Dokman** [comment]
that's true but i don't know how to debug in php :(

**Comment by Dokman** [comment]
at commit https://github.com/Sarjuuk/aowow/commit/33b1e4a978fbcef0c3c28fdb44a09df822d8386c has the same problem

**Comment by Dokman** [comment]
now is installable, but i don't know if i have to port the blp to png but okay...
Then is always slow, the apache server is consuming like ~500MB

**Comment by Dokman** [comment]
@Sarjuuk here you have the news :)

**Comment by Kittnz** [comment]
php 5.6 xampp works perfectly for me

**Comment by qyh214** [comment]
php 5.6 xampp works perfectly for me too
only test enus and I will continue test.

**Comment by qyh214** [comment]
Now maybe we can close this issue.
I have test in latest xampp version(7.2.13 / PHP 7.2.13) in Windows 10
