### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by kep123** [Sarjuuk/aowow#103]
Add Chinese support display ：
[err] known field types [8] and names [7] do not match for achievement_category.dbc,aborting

**Comment by Sarjuuk** [comment]
cannot reproduce, works for me.

(branch aowow/locale4 assumed)

**Comment by kep123** [comment]
Network is not good, because access to foreign websites is slow

**Comment by kep123** [comment]
But ,I can translate Chinese

**Comment by Sarjuuk** [comment]
error unclear, ticket abandoned
