### ISSUE TITLE
Issue with sound

### ISSUE THREAD

**Issue by Dokman** [Sarjuuk/aowow#104]
![image](https://cloud.githubusercontent.com/assets/2290904/24985742/7e0b9e92-1ff6-11e7-8a32-0cabb4a1770a.png)

**Comment by Sarjuuk** [comment]
so, should i post a picture of cats in response or something..?

**Comment by Dokman** [comment]
it has a folder called <locale> and all the other things are working, i've converted the blp too, but it doesn't show

**Comment by Sarjuuk** [comment]
error unclear, ticket abandoned

**Comment by Magnifikator** [comment]
I also have a lot of such warnings. But the warning means only that there is no locale sound found.
Not all sounds have a local version. 
For example in my case I also don't have any deDE sounds for sound/creature/fleshgolem/*

So I guess this warnings can be ignored.
