### ISSUE TITLE
Generate db content from your world tables

### ISSUE THREAD

**Issue by Rimovals2** [Sarjuuk/aowow#106]
Hi, 

When i use command to Generate db like aowow --sql
Miss item_template, table aowow_items is empty

next problem is  _loot_template and Quest does not work 2

I have Last TC DB

 E_WARNING - Invalid argument supplied for foreach() @ /home/www/empty/pages/npc.php:993
 E_NOTICE - Undefined offset: 29434 @ /home/www/empty/includes/loot.class.php:260
 E_WARNING - array_merge(): Argument #1 is not an array @ /home/www/empty/includes/loot.class.php:260
 E_NOTICE - Undefined offset: 60056 @ /home/www/empty/includes/loot.class.php:260
 E_WARNING - array_merge(): Argument #1 is not an array @ /home/www/empty/includes/loot.class.php:260
 E_NOTICE - Undefined offset: 90092 @ /home/www/empty/includes/loot.class.php:260
 E_WARNING - array_merge(): Argument #1 is not an array @ /home/www/empty/includes/loot.class.php:260
 E_NOTICE - Undefined offset: 90093 @ /home/www/empty/includes/loot.class.php:260
 E_WARNING - array_merge(): Argument #1 is not an array @ /home/www/empty/includes/loot.class.php:260
 E_NOTICE - Undefined offset: 90094 @ /home/www/empty/includes/loot.class.php:260
 E_WARNING - array_merge(): Argument #1 is not an array @ /home/www/empty/includes/loot.class.php:260
 E_NOTICE - Undefined offset: 90095 @ /home/www/empty/includes/loot.class.php:260
 E_WARNING - array_merge(): Argument #1 is not an array @ /home/www/empty/includes/loot.class.php:260
 E_NOTICE - Undefined offset: 90096 @ /home/www/empty/includes/loot.class.php:260
 E_WARNING - array_merge(): Argument #1 is not an array @ /home/www/empty/includes/loot.class.php:260
 E_NOTICE - Undefined offset: 90097 @ /home/www/empty/includes/loot.class.php:260
 E_WARNING - array_merge(): Argument #1 is not an array @ /home/www/empty/includes/loot.class.php:260
 E_NOTICE - Undefined offset: 90098 @ /home/www/empty/includes/loot.class.php:260
 E_WARNING - array_merge(): Argument #1 is not an array @ /home/www/empty/includes/loot.class.php:260
 E_NOTICE - Undefined offset: 90099 @ /home/www/empty/includes/loot.class.php:260
 E_WARNING - array_merge(): Argument #1 is not an array @ /home/www/empty/includes/loot.class.php:260
 E_NOTICE - Undefined offset: 90100 @ /home/www/empty/includes/loot.class.php:260
 E_WARNING - array_merge(): Argument #1 is not an array @ /home/www/empty/includes/loot.class.php:260
 E_NOTICE - Undefined offset: 90101 @ /home/www/empty/includes/loot.class.php:260
 E_WARNING - array_merge(): Argument #1 is not an array @ /home/www/empty/includes/loot.class.php:260
 E_NOTICE - Undefined offset: 90102 @ /home/www/empty/includes/loot.class.php:260
 E_WARNING - array_merge(): Argument #1 is not an array @ /home/www/empty/includes/loot.class.php:260
 E_NOTICE - Undefined offset: 90103 @ /home/www/empty/includes/loot.class.php:260
 E_WARNING - array_merge(): Argument #1 is not an array @ /home/www/empty/includes/loot.class.php:260
 E_NOTICE - Undefined offset: 90104 @ /home/www/empty/includes/loot.class.php:260
 E_WARNING - array_merge(): Argument #1 is not an array @ /home/www/empty/includes/loot.class.php:260
> E_NOTICE - Undefined offset: 90105 @ /home/www/empty/includes/loot.class.php:260
> E_WARNING - array_merge(): Argument #1 is not an array @ /home/www/empty/includes/loot.class.php:260
> E_NOTICE - Undefined offset: 90106 @ /home/www/empty/includes/loot.class.php:260
> E_WARNING - array_merge(): Argument #1 is not an array @ /home/www/empty/includes/loot.class.php:260
> E_NOTICE - Undefined offset: 90108 @ /home/www/empty/includes/loot.class.php:260
> E_WARNING - array_merge(): Argument #1 is not an array @ /home/www/empty/includes/loot.class.php:260
> E_NOTICE - Undefined offset: 90109 @ /home/www/empty/includes/loot.class.php:260
> E_WARNING - array_merge(): Argument #1 is not an array @ /home/www/empty/includes/loot.class.php:260
> E_NOTICE - Undefined offset: 90110 @ /home/www/empty/includes/loot.class.php:260
> E_WARNING - array_merge(): Argument #1 is not an array @ /home/www/empty/includes/loot.class.php:260
> E_NOTICE - Undefined offset: 90111 @ /home/www/empty/includes/loot.class.php:260
> E_WARNING - array_merge(): Argument #1 is not an array @ /home/www/empty/includes/loot.class.php:260
> E_NOTICE - Undefined offset: 700465 @ /home/www/empty/includes/loot.class.php:260
> E_WARNING - array_merge(): Argument #1 is not an array @ /home/www/empty/includes/loot.class.php:260

**Comment by Sarjuuk** [comment]
http://realm.internetgamez.eu/
this is yours, isn't it..?

anyway .. what *is* 'latest' TDB
what version of aowow are you using 
and what where you actually doing.

If your setup process bugs out why don't post these errors instead of symptomatic in-page errors.

> E_WARNING - Invalid argument supplied for foreach() @ /home/www/empty/pages/npc.php:993     

That is creature broadcast text. I can say with near certainty, you are not using the (as of this time) latest version of TDB. (335.63)

**Comment by Rimovals2** [comment]
I have TDB 335.63, 
yes, http://realm.internetgamez.eu/ is my page http://realm.internetgamez.eu/masterhead/

Yesterday I downloaded your latest version of aowow

**Comment by Sarjuuk** [comment]
oh ffs, TC snuck in more structural changes after just releasing a new DB version.

**Comment by Rimovals2** [comment]
Yes, I'll wait for the changes thank you for the development :) :+1:

**Comment by Sarjuuk** [comment]
try again with 00342b0b6167e21c30061e797a7950469331c9f3

**Comment by Rimovals2** [comment]
I upload your update
used the command php aowow update
and php aowow sql but table aowow_items, aowow_quest,

22:13:41  [OK]     - subscript 'itemset' returned sucessfully
22:13:41          SqlGen::generate() - filling aowow_item_stats with data
22:13:41           - applying stats for enchantments
22:13:43             2680 enchantments parsed
22:13:43           - applying stats for items
22:13:43  [OK]     - subscript 'item_stats' returned sucessfully
22:13:43          SqlGen::generate() - filling aowow_source with data
22:13:43           - Items & Spells [inherited]
22:13:43             * resolve ref-loot tree
22:13:44             * #1  Crafted
22:13:44             * #2  Drop
22:13:50             * #3  PvP
22:13:50             * #4  Quest
22:13:51             * #5  Vendor
22:13:55             * #10 Starter
22:13:55             * #12 Achievement
22:13:55             * #15 Disenchanted
22:13:55             * #16 Fished
22:13:55             * #17 Gathered
22:13:55             * #18 Milled
22:13:55             * #19 Mined
22:13:55             * #20 Prospected
22:13:55             * #21 Pickpocket
22:13:56             * #22 Salvaged
22:13:56             * #23 Skinned
22:13:56           - Spells [original]
22:13:56             * #4  Quest
22:13:56             * #6  Trainer
22:13:56             * #7  Discovery
22:13:56             * #9  Talent
22:13:56               - 1. pass
22:13:56               - 2. pass
22:13:56               - 3. pass
22:13:56             * #10 Starter
22:13:56           - Titles
22:13:56             * #4  Quest
22:13:57             * #12 Achievement
22:13:57             * #13 cuStrings
22:13:57  [OK]     - subscript 'source' returned sucessfully

22:13:57  [OK]    successfully finished sql generation

**Comment by Sarjuuk** [comment]
meh, i fucked up the update queries.
in your `aowow_dbversion` table; empty the 'build' and 'sql' fields

in CLI do `php aowow --sync=item_template,quest_template`
this will rebuild everything, that depends on TCs quest and item tables

**Comment by Rimovals2** [comment]
That's fun :)

https://pastebin.com/AxBEZCcC

**Comment by Sarjuuk** [comment]
you are still having issues with your item_template. Enable debug in your config and retry.
You'' probably get an sql-error

**Comment by Rimovals2** [comment]
I'm sorry I have a lot of work.

Now everything works thank you.

**Comment by Sarjuuk** [comment]
great to hear
