### ISSUE TITLE
Update class with new DB structure of TC

### ISSUE THREAD

**Issue by Endalaust** [Sarjuuk/aowow#107]
https://github.com/TrinityCore/TrinityCore/commit/9a3b28894da14a4d839ddad77fa85be61ff03287
https://github.com/TrinityCore/TrinityCore/commit/460e2c5dc5eae49f62a9193fb58f1bab42028bd2
https://github.com/TrinityCore/TrinityCore/commit/3739d8444b1d5683bdac29f4a91df567dc19fd79

Cause /pages/npc.php line 991 ofc table 'locales_broadcast_text' doesn't exist since this update, new name and new structure.
Dont know if quest_template_locale & item_template_locale broke anything else right now

Ty a lot Sarjuuk

**Comment by Sarjuuk** [comment]
NOOOoooo.........

:(

**Comment by Endalaust** [comment]
I had the same reaction after the merge
I don't tell you the armory of my site with elendil... And the worst, I'm afraid it's just the beginning at trinitycore

**Comment by Sarjuuk** [comment]
try again with 00342b0b6167e21c30061e797a7950469331c9f3

**Comment by Endalaust** [comment]
mhmm, its works great, nice work
I give you the pleasure to close this issue ;)

**Comment by Endalaust** [comment]
https://github.com/TrinityCore/TrinityCore/pulls/ChazyTheBest

Just to know ;)

**Comment by Sarjuuk** [comment]
Besides these three, only locales_achievement_reward is left. Then it'll be over, finally...
Although, i'm not affected by changes to npc_text or the gossip related tables.

but nice to have these all in one place to keep an eye on.

**Comment by Sarjuuk** [comment]
aaand it happened...
