### ISSUE TITLE
Aowow --first run error incorrect format string

### ISSUE THREAD

**Issue by dikkedeur** [Sarjuuk/aowow#110]
when doing the aowow --first run and setup the database login details i went on.
The first error was something about site host not being set, but that can be done later on i saw with aowow --siteconfig.

but then i came on the next error which involves the sql generating from the dbc files.
it seems that there is something wrong.

```
10:53:15          SqlGen::generate() - copying achievement_criteria.dbc into aowow_achievementcriteria

10:53:15          reading MPQdata from setup/mpqdata/ to list for first time use...
10:53:15          done

10:53:15  [ERR]   incorrect format string (niiiiiiiisxssxxsxsxxxxxxxxiixii) specified for file setup/mpqdata/dbfilesclient/achievement_criteria.dbc fieldCount=28
10:53:15  [ERR]   no suitable files found for achievement_criteria.dbc, aborting.

[c]ontinue anyway? [r]etry? [a]bort?: 
```

aborted the process..

i checked and the file is that directory, along with other dbc files.. specially since he did already dbfilesclient/achievement_category.dbc  since that table is already populated in my database.

thanks for your time...and patience

**Comment by Sarjuuk** [comment]
The current AchievementCriteria.dbc has 31 fields. I guess you didn't follow the patch order, when extracting the MPQs

**Comment by dikkedeur** [comment]
time to redo the whole process again then tomorrow, thanks for the answer..

**Comment by dikkedeur** [comment]
fixed...

thanks for your time and help!

**Comment by dikkedeur** [comment]
Dont want to make another thread, but do you know how it comes i se everything, the whole page but not any icons??

![schermafbeelding 2017-05-09 om 14 14 06](https://cloud.githubusercontent.com/assets/11842306/25850247/d80dcb38-34c1-11e7-86d5-99b0fd693092.png)

everything seems to work only i dont see those icons.

**Comment by Sarjuuk** [comment]
you are also missing the sounds.

`php aowow -build=simpleImg,talentIcons,soundfiles`
talentIcons, because they depend on the missing icons. 
if it didn't work, what does the log say.

**Comment by dikkedeur** [comment]
@Sarjuuk well i did the command.

this is the outcome, i have put it in gist, since it was way too much.

https://gist.github.com/dikkedeur/b2cb7edb1b1259f63709501138489222

Now for the record, it says setup/mpqdata/enGB/Interface/Icons/ is missing etc.etc.
true.. i use enUS. so i have not made it for the rest of the locale.

Now i was thinking, hmm maybe it cant find the files.. could be.. ( strange since dbfilesclient was found and others ) so everything i extracted by the mpqextrator is copyed to multiple directories just to be sure.

/setup/mpqdata/*
/setup/mpqdata/enUs
/setup/mpqdata/0  ( since enUs is locale 0 i was.. maybe thats it.. )

on all formats above it doesnt matter.. icons not shown..
when i go to /setup/mpqdata/interface/icons
i see alot of files.. so it seems they are all extracted.

**Comment by dikkedeur** [comment]
did a pull to get latest changes, and did the whole process you said, but without the soundfiles..
this is the error log
https://gist.github.com/dikkedeur/5036ab81f0d7b90ac88bdc8e8ce4dfbf

**Comment by Sarjuuk** [comment]
Sorry, i'm currently busy with personal things. Although, i have a suspicion It may be a couple of days until i can get around to check it.

**Comment by dikkedeur** [comment]
no problem @Sarjuuk personal life comes first.. its more important then anything.
take care and hope to hear from you soon.

**Comment by Sarjuuk** [comment]
c61fb787aee19a37cda4e4cc41911dc5e1cb36c6
this will probably not fix your problem (which i couldn't reproduce) but make it more obvious what you are missing.

**Comment by dikkedeur** [comment]
@Sarjuuk i will try it out in a few minutes and let you know

**Comment by dikkedeur** [comment]
Frankly @Sarjuuk its working now.
only thing i miss is now the sound files. but thats well not a problem in my case.
```
 php aowow --build=simpleImg,talentIcons,soundfiles
10:59:54          FileGen::init() - creating required directories
10:59:54          created 8 extra paths

10:59:54          begin generation of simpleImg, talentIcons, soundfiles

10:59:54          FileGen::generate() - gathering data for simpleImg

10:59:54          reading MPQdata from setup/mpqdata/ to list for first time use...
10:59:54          done

10:59:54  [INFO]  required resources overview:
10:59:54           FOUND  - Icons/                                                @ setup/mpqdata/interface/icons
10:59:54           FOUND  - Spellbook/                                            @ setup/mpqdata/interface/spellbook
10:59:54           FOUND  - PaperDoll/                                            @ setup/mpqdata/interface/paperdoll
10:59:54           FOUND  - GLUES/CHARACTERCREATE/UI-CharacterCreate-Races.blp    @ setup/mpqdata/interface/glues/charactercreate/ui-charactercreate-races.blp
10:59:54           FOUND  - GLUES/CHARACTERCREATE/UI-CharacterCreate-CLASSES.blp  @ setup/mpqdata/interface/glues/charactercreate/ui-charactercreate-classes.blp
10:59:54           FOUND  - GLUES/CHARACTERCREATE/UI-CharacterCreate-Factions.blp @ setup/mpqdata/interface/glues/charactercreate/ui-charactercreate-factions.blp
10:59:54           FOUND  - FlavorImages/                                         @ setup/mpqdata/interface/flavorimages
10:59:54           FOUND  - Pictures/                                             @ setup/mpqdata/interface/pictures
10:59:54           FOUND  - PvPRankBadges/                                        @ setup/mpqdata/interface/pvprankbadges
10:59:54           FOUND  - Calendar/Holidays/                                    @ setup/mpqdata/interface/calendar/holidays

10:59:55          processing 6308 files in setup/mpqdata/interface/icons...
10:59:55  [OK]     - 1/25232     (0.00%)   - image static/images/wow/icons/large/creature_sporemushroom.jpg written
10:59:55  [OK]     - 2/25232     (0.01%)   - image static/images/wow/icons/medium/creature_sporemushroom.jpg written
10:59:55  [OK]     - 3/25232     (0.01%)   - image static/images/wow/icons/small/creature_sporemushroom.jpg written
10:59:55  [OK]     - 4/25232     (0.02%)   - image static/images/wow/icons/tiny/creature_sporemushroom.gif written
10:59:55  [OK]     - 5/25232     (0.02%)   - image static/images/wow/icons/large/inv_throwingknife_07.jpg written
10:59:55  [OK]     - 6/25232     (0.02%)   - image static/images/wow/icons/medium/inv_throwingknife_07.jpg written
10:59:55  [OK]     - 7/25232     (0.03%)   - image static/images/wow/icons/small/inv_throwingknife_07.jpg written
10:59:55  [OK]     - 8/25232     (0.03%)   - image static/images/wow/icons/tiny/inv_throwingknife_07.gif written
```

**Comment by Sarjuuk** [comment]
ok then :>
