### ISSUE TITLE
Talent calculator doesn't work

### ISSUE THREAD

**Issue by Yehonal** [Sarjuuk/aowow#111]
Hello

i've this error accessing the browser console on talent calculator page:

`TalentCalc.js?26:1713 Uncaught ReferenceError: g_glyphs is not defined
    at _initGlyphData (TalentCalc.js?26:1713)
    at TalentCalc.initialize (TalentCalc.js?26:367)
    at tc_init (talent.js?26:44)
    at ?talent:83`

http://db.wow-game.net/?talent

How can i solve?

**Comment by Sarjuuk** [comment]
dunno, it works for me. :o

except, that your site is terribly slow.

**Comment by Yehonal** [comment]
i've fixed it, seemed a cloudflare issue.
The speed is not so bad imho, but seems that the cache isn't working.

The cache/template path is empty and it has 777 permissions. Does it work for you?

**Comment by Sarjuuk** [comment]
Hm, from the top of my head.. 
* is filecache enabled in the config? 
* access 0755 should be sufficient (maybe even 0744)

If it is something else I'm afraid it'll have to wait.

**Comment by Playon24** [comment]
Try to disable Rocket Loader in the Speed tab on CloudFlare

**Comment by Yehonal** [comment]
I've fixed both issues:

* no working talents:  just disable cloudflare minify and/or cache everything page rule and/or rocket loader

* no working cache: CFG_DEBUG was default enabled (dunno why) , just disable it

thank you :)

**Comment by Yehonal** [comment]
FYI:

I've found this problem again on another host without cloudflare and i've debugged it to found cause.

The issue happens when there's an invalid PHPSESSID cookie that doesn't allow the correct behaviour of php session and this check doesn't pass:

```
            // requires valid token to hinder automated access
            if ($set != 'item-scaling')
                if (!$this->_get['t'] || empty($_SESSION['dataKey']) || $this->_get['t'] != $_SESSION['dataKey'])
                    continue;
```
It could happen when you've changed the protocol (http -> https) or something that doesn't recognize your PHPSESSID in the correct way. Maybe we should automatically delete this kind of cookie with aowow (?)

Currently the solution (or workaround) would be deleting this cookie allowing the system to recreate it correctly.

**Comment by Sarjuuk** [comment]
oh, thats bad.
I don't "handle" the sessions, php does this almost by itself. I'm just writing a hand full of variables onto it. 
If the browser and server get decoupled for some reason and a new session isn't established as soon as you make ANY new request. ... I'm not sure, what i can do about that ...
