### ISSUE TITLE
Bug - Spells/DetailPage: requiredForms not displayed in table

### ISSUE THREAD

**Issue by Kittnz** [Sarjuuk/aowow#113]
Add "forms". On wowhead we can see "Forms: Zombie" for example:
http://www.wowhead.com/spell=51230/retch

We currently don't have this:
https://woehead.way-of-elendil.fr/?spell=51230

Maybe a way to filter on it too?

**Comment by Sarjuuk** [comment]
..its a bug :<

**Comment by Sarjuuk** [comment]
just to underline the 'convoluted' part
https://woehead.way-of-elendil.fr/?spell=66530 ;)

**Comment by Kittnz** [comment]
I wonder how wowhead did it..

**Comment by Sarjuuk** [comment]
should be fixed in 94321ea1788f51f6985490edb760393d6cd383ed
