### ISSUE TITLE
Bug or Error?

### ISSUE THREAD

**Issue by PaulTinnick** [Sarjuuk/aowow#114]
Hi. I have some problems: 

When I use the tooltips, the inscriptions in English are displayed on my site (not the database). Although the database in Russian
Look: [database](http://pastenow.ru/5f0672053eac5edd9226ccc155bf052b) and [site](http://pastenow.ru/18a31083ee779de95332c6cace8b1de8)

And when I use spells, "undefined" is displayed and there is no caption for the tooltips.
Look: [database](http://pastenow.ru/cf9abd76d89608602285cb1f7793075d) and [site](http://pastenow.ru/c6fd70e4ef7c71d2bf8bb56ae9b361b1)

Please, help

**Comment by Sarjuuk** [comment]
add `?lang=ru` to the power.js include in your site. 
Not entirely sure about the parameter though, may also be `?locale=8`

**Comment by PaulTinnick** [comment]
Thank you very much
