### ISSUE TITLE
Cant change of Domain

### ISSUE THREAD

**Issue by IlPicasso** [Sarjuuk/aowow#116]
Hello! 

When I try to change the site host of my web from wowdb.comugamers.com to db.wow.comugamers.com I have issues 

some pages shows no content like these

![image](https://cloud.githubusercontent.com/assets/5110242/26653538/05f53398-4619-11e7-9fc5-4a581c3bd52b.png)

![image](https://cloud.githubusercontent.com/assets/5110242/26653555/0d0bd628-4619-11e7-8dd8-772bb0489ded.png)

However if I change back, to wowdb.comugamers.com it does appear 

![image](https://cloud.githubusercontent.com/assets/5110242/26653613/3a40bb7c-4619-11e7-8f6c-8473ff5ab65f.png)

**Comment by dikkedeur** [comment]
have you changed the site host?? or domain host in aowow...

**Comment by dikkedeur** [comment]
I mean static host

**Comment by IlPicasso** [comment]
Yes

**Comment by Sarjuuk** [comment]
Uh, i never tested second level subdomains. I'll have to check that.

**Comment by Sarjuuk** [comment]
hm, sorry, cant reproduce that.

1) When viewing the pages source code, can you find the javascript block `Markup.printHtml("<escaped_article_text>", "article-generic", {"allow": Markup.CLASS_ADMIN});`
2) If so, do you have javascript errors in your browser console?

**Comment by Sarjuuk** [comment]
Is this still relevant?

**Comment by Sarjuuk** [comment]
Hm, apparently not.
