### ISSUE TITLE
Creating characters not working

### ISSUE THREAD

**Issue by IlPicasso** [Sarjuuk/aowow#117]
When I try creating a character it doesn't save at all , after clicking on save as it never redirects me anywhere

![image](https://cloud.githubusercontent.com/assets/5110242/26653652/65988016-4619-11e7-9306-e2413f0fc0d0.png)

![image](https://cloud.githubusercontent.com/assets/5110242/26653669/783452ea-4619-11e7-835d-4583ecc4fcd8.png)

![image](https://cloud.githubusercontent.com/assets/5110242/26653688/85f29c2a-4619-11e7-9567-3a6d96f7be7c.png)

**Comment by Sarjuuk** [comment]
NYI on branch master
