### ISSUE TITLE
Could not fetch static data: item-scaling.

### ISSUE THREAD

**Issue by HannibalRoG** [Sarjuuk/aowow#121]
I have an error when i try to load the page "could not fetch static data: item-scaling"
Is it because I need to configure something or a site error?

**Comment by Sarjuuk** [comment]
Are there any other files in `datasets/`? If so, just try to rebuild the file `php aowow --build=item-scaling` I believe.
If not, setup probably wasn't allowed to write it that folder. Fix that.

**Comment by HannibalRoG** [comment]
Eetouch all permission in aowow folder, run aowow script again, problem solved.

**Comment by Sarjuuk** [comment]
Great to hear :]
