### ISSUE TITLE
Item Not Found

### ISSUE THREAD

**Issue by electricmessiah** [Sarjuuk/aowow#123]
I got the site running, the first issue I have to report is many icons and items are producing "item not found" errors. If I click 'Daggers' the page comes up blank. Item sets show a bunch of ? icons with "item not found" in the tooltips. The install went fine (except for crashing on glyphs - step 64) as far as I can tell, and I extracted everything as instructed.

**Comment by Sarjuuk** [comment]
closed due to age. sorry :(
