### ISSUE TITLE
Sounds not found on install

### ISSUE THREAD

**Issue by electricmessiah** [Sarjuuk/aowow#124]
I converted all of the sounds as instructed, but the install produces hundreds of errors about not being able to find the files.

**Comment by Magnifikator** [comment]
Same problem here. But looking to the warning it's seems the install program is looking for *.wav.ogg files instead of *.ogg files.

**Comment by Sarjuuk** [comment]
maybe fixed..?
i just hope underscores are not reserved characters on *nix or WIN

**Comment by Sarjuuk** [comment]
apparently fixed
