### ISSUE TITLE
[Suggestion] Add SpellIcon ID from SpellIcon.dbc

### ISSUE THREAD

**Issue by BarbzYHOOL** [Sarjuuk/aowow#125]
I often use AoWOW for AzerothCore https://wowgaming.altervista.org/aowow/
I wondered if you could add the SpellIcon ID from SpellIcon.dbc to the icon description.

For item icons, you get the icon ID.
But for spell icons, the ID we find in Spell.dbc points at SpellIcon.dbc which points to the icon location.

That's why we can't find easily the icon associated with each spell.

If you added it it would be very useful, especially for custom creation.

**Comment by Sarjuuk** [comment]
There are about 22 duplicate icons in spellicon.dbc, the worst offender being _trade_engineering_ with 22 occurences. itemdisplayinfo.dbc is even worse from an icon perspective, as it primarily serves other data.
_INV_Gauntlets_05_ is used 426 times .. yeah ...

Thats why i assigned new, unique ids and never looked back.

in short; sorry, not going to happen.

**Comment by BarbzYHOOL** [comment]
Duplicate icons ? they just point to the same icon because many spells use the same icon.

I don't understand what is the issue but I have no idea how Aowow works neither lol

**Comment by BarbzYHOOL** [comment]
> hundreds in case of items

https://wowgaming.altervista.org/aowow/?item=5863# look if you click on the icon, it gives the name of the icon at least
