### ISSUE TITLE
on firstrun configuration error: http vs. https

### ISSUE THREAD

**Issue by Magnifikator** [Sarjuuk/aowow#127]
On firstrun configuration there are 2 file checks for:
http://[path]/README.md
http://[path]/static/css/aowow.css

This results in a 'could not access' error if the domain uses https protocol and/or redirects http to https. The error code is 301 (redirect).

However the setup can be continued.

**Comment by Sarjuuk** [comment]
True.. 
Issue put onto todo-stack

**Comment by Magnifikator** [comment]
The cheap way: Try directly to access on https.
For most websites http protocol is gone since main browsers warn about non-saftey.

**Comment by Magnifikator** [comment]
If force_ssl is set to 1 in the config table it accesses https correct.
