### ISSUE TITLE
Factions in FR

### ISSUE THREAD

**Issue by Endalaust** [Sarjuuk/aowow#132]
Hello Sarjuuk, long time ago right
My translator has finished to translate all factions in FR
https://way-of-elendil.fr/telechargement/aowow_articles_factions_fr.sql

We regret there are not many updates on aowow, hollidays ? ;)
Have a nice day.

**Comment by Sarjuuk** [comment]
Thanks, but you may want to take a hard look at your replacement patterns. 
There is a good amount of broken markup within the articles. (e.g. [spanclass=q2]text[/span] or [npc = 1234])

anyway, fixed and incorporated.

thx again.
