### ISSUE TITLE
HOURS is not a predefined constant in PHP

### ISSUE THREAD

**Issue by Magnifikator** [Sarjuuk/aowow#134]
Commit: d83f370fb4f7740eaece8ef19aed1cacffadc989
HOURS is not a predefined constant in PHP.
The result is: 'Retry-After: 0'

**Comment by Sarjuuk** [comment]
yeah, its **HOUR**~~S~~...
https://github.com/Sarjuuk/aowow/blob/master/includes/defines.php#L119

**Comment by Sarjuuk** [comment]
fixed in f2fce0f6021699dea683f67db05495606988a592
