### ISSUE TITLE
[Recommendation] CSS and js files should have own version number

### ISSUE THREAD

**Issue by Magnifikator** [Sarjuuk/aowow#135]
CSS and js files have AOWOW_REVISION as version in html HEAD section.

This is may not a good solution because if somebody wants to change design (css) or individual menu (js) the file version should be changed. Otherwise the client uses still the old cached file.

Recommend to include either a file with a own constant and  (random) version number outside of git tracking.
Or better use a random generated number saved in the db.

**Comment by Sarjuuk** [comment]
AOWOW_REVISION does two things
 * file versioning (as you mentioned, but also for cache files (if used))
 * prevent access to arbitrary files

In both cases it *should* be of no concern, what actual data this constant contains. so you could/should just append an incremental letter or something to it, when you edit your css/js-files (e.g. rev: 46 => 46a)
This will also force the browser to re-download the files.

For now, the cache expects a numeric value for comparison. I'm going to change that.

**Comment by Sarjuuk** [comment]
it's no longer a concern: ada57d4384073d4b9893e769f622a93d52b8b0da

if you alter your css/js files, just change AOWOW_REVISION in tandem.

**Comment by Magnifikator** [comment]
You really should think to split AOWOW_REVISION and BROWSER_CACHE_VERSION.

Nobody can know what you are going to use AOWOW_REVISION for. You also use is f.ex. for logging.
It's a better praxis to split such things.

Additionally the template has a lot of lines using this version number. Better to provide a constant or a variable for it. (or take it from database)
