### ISSUE TITLE
Installation don't work

### ISSUE THREAD

**Issue by Dainara82** [Sarjuuk/aowow#141]
Hi, ich versuch schon seit über 3 Wochen die Seite zum laufen zu bringen, ich habs mit den Clients enUS, enGB, deDE versucht, hab alle benötigten Dateien von allen MPQ dateien extrahiert, jede in einen eigenen Ordner, hab dann versucht die richtige Reihenfolgen herauszufinden, hab versucht alle Großbuchstaben in kleinbuchstaben zu ersetzen mit scrips, hab alle blp dateien mit dem tool in png umgewandelt,
hab den Ordner mpqdata unter setup erstellt, habs auch mit den enUS und ohne diesen Ordner versucht.

das script zum umwandeln der soundfiles geht auch nicht
und beim firstrun erhalte ich nur WARGINGS, INFOS, ERROR  etc pp

beim firstrun script erhalte ich ausserdem irgendwann folgenden Fehler
`19:41:00          FileGen::generate() - gathering data for glyphs
Fatal Error - Allowed memory size of 1572864000 bytes exhausted (tried to allocate 20480 bytes) @ /var/www/html/aowow/includes/libs/DbSimple/Database.php:1024
r`
ich hab in einigen Foren um hilfe gefragt, entweder konnte oder wollte mir neimand helfen, ich weis nicht was ich noch tun soll

hier die MPQ dateien mit denen ich versucht habe die richtige Reihenfolge herauszufinden, habs auch mit backup-enUS.MPQ und ohne versucht, habs auch schon versucht rein nur mit den enUS MPQ's
und eine andere reinhekfolge der pach files, bin am verzweifeln

base-enUS.MPQ
patch.MPQ
patch-2.MPQ
patch-3.MPQ
common.MPQ
common-2.MPQ
expansion.MPQ
expansion-locale-enUS.MPQ
expansion-speech-enUS.MPQ
lichking.MPQ
lichking-locale-enUS.MPQ
lichking-speech-enUS.MPQ
locale-enUS.MPQ
patch-enUS.MPQ
patch-enUS-2.MPQ
patch-enUS-3.MPQ
speech-enUS.MPQ

hab mit nem rename script alle Großbuchstaben in kleinbuchstaben umgewandelt

bitte hilf mir dieses dessaster zu beseitigen, mag sein dass ich zu blöd bin, bin blond und blauäugig ja aber hab bisher immer alles gelöst bekommen aber hier bin ich mal echt am scheitern
benutze debian 9  64 bit

ByeByeb
Dainara

**Comment by Sarjuuk** [comment]
closed due to age. sorry :(
