### ISSUE TITLE
[An internal error occured.] Failed login

### ISSUE THREAD

**Issue by OlegVintage88** [Sarjuuk/aowow#142]
I can not log in to Aowow, nor is registration available
Error **[An internal error occured.]**

Some settings
> acc_allow_register	        1
> acc_auth_mode	        0
> acc_create_save_decay	604800
> acc_failed_auth_block	900
> acc_failed_auth_count	5
> acc_recovery_decay	        300

**Comment by Sarjuuk** [comment]
closed due to age. sorry :(
