### ISSUE TITLE
image upload suggestion

### ISSUE THREAD

**Issue by kvipka** [Sarjuuk/aowow#143]
What about to block func approve img by moderator ?

For example rating 50-75+ and user can upload images without approve

**Comment by Sarjuuk** [comment]
not going to do this.

if you want this for yourself add a check against User::getReputation() to the query [here](https://github.com/Sarjuuk/aowow/blob/959d0ace0b070446333570e475f207794fce6c52/pages/screenshot.php#L218) and directly flag the screenshot as approved

optionally make the value configurable by adding it to the aowow_config table

optionally optionally reference the value on the privileges page by adding the config value to the array [here](https://github.com/Sarjuuk/aowow/blob/9516affde52ddddf3ce9ab769ecef5166d8f0cc4/pages/more.php#L20) and adding localization as needed.
