### ISSUE TITLE
Instalation fail

### ISSUE THREAD

**Issue by Adeer** [Sarjuuk/aowow#144]
How to install?
when entering php aowow --build

```
# php aowow --build
12:16:48          FileGen::init() - creating required directories
12:16:48          created 8 extra paths
12:16:48  [INFO]  generated dbc_* - tables kept available
```

Please send me complete instructions how to install, Very Thanks.

**Comment by Sarjuuk** [comment]
[README.md](https://github.com/Sarjuuk/aowow/blob/master/README.md)
something you definitely did not use, because it doesn't say anything about `php aowow --build` .. at all

**Comment by Adeer** [comment]
items are not functional... table is empty!
