### ISSUE TITLE
Errors when installing Spawns and Zones

### ISSUE THREAD

**Issue by Zirgus** [Sarjuuk/aowow#145]
Good time.
Sarjuuk, I need your help! I've been back and forth on the issue.
1. Write permissions (777) as described exposed.
2. Next, run php aowow --firstrun, DBC files are extracted without errors and the rest too, but as soon as it comes to the item **Spawns** and **Zones** (photo attached) 
![spawn2](https://user-images.githubusercontent.com/40244703/41375407-a67a267e-6f5e-11e8-8019-7fbc15681be2.jpg)
get solid errors! (photo shows).
![spawn](https://user-images.githubusercontent.com/40244703/41375398-9cd7d3a0-6f5e-11e8-84c1-b54a887f4fe0.jpg)

That just did not try, different database: from (TDB_full_335.60, 61, 62, 63, 64) even (YTDB_0.14.7_R640, TC_0.14.8_r650) errors appear in different places, tell me where to look for the problem???
This is the main on this issue!
And the last question about (3D Flash-Animation) all the content on the site that the description, It is extracted from the client WoW 3.3.5 or is it possible to download?, and path *.swf files **static/modelviewer** straight to the root or another location?.
Sorry about my English.
Thanks in advance! I'll wait.

**Comment by Sarjuuk** [comment]
The warnings spawn/waypoints are fine-ish. A lot of instances don't have maps and thus creatures/GOs spawned there are lost.
You could let you core calculate spawn areas though. (See readme)

The flash modelviewer is no longer supplied by wowhead, so it won't work (see readme)

**Comment by Zirgus** [comment]
Sajuuk, Thanks for answering.
1. On the first question, Included in a config parameters
Calculate.Creature.Zone.Area.Data = 1
Calculate.Gameoject.Zone.Area.Data = 1
but it didn't help! errors have not diminished, ispolzoval different core Trinitycore database 335.63 TDB, TDB 335.64, Have a client WoW 3.3.5 a (12340) Extracted as in the description of all the DBC files checked database TDB 335.63, created the admin account and run php aowow --firstrun, at the stage of extracting the DBC files everything is fine, there is 1 error while iavleaetsea with the item_template table (44209 not found #181) . Then the cards themselves are extracted in the amount of 660 PCs. Sajuuk, maybe there are options how to fix it?
2. And the question about Flash-animation remains open on your website https://db.rising-gods.de animation works!  All these animation models are in the client! but a question ...  what files where you want to put it: .3ds,.lws,.m2,.ms3d,.x3d,.mtl,.obj ..  further some of these (or all files) are generated in .SWF ? or wrong, please tell me the full path.
Thanks

**Comment by Zirgus** [comment]
So will someone help?

**Comment by qyh214** [comment]
@Zirgus I suggest you use clear 335 enus client with 335.63 tc tables test!

I can't reproduce your issue

**Comment by Sarjuuk** [comment]
closed due to age. sorry :(
