### ISSUE TITLE
Racial skills don't appear in search results

### ISSUE THREAD

**Issue by wodim** [Sarjuuk/aowow#146]
Racial spells/passive skills don't appear when you search for them.

For example, searching for "blood fury" doesn't return https://db.rising-gods.de/?spell=20572

**Comment by Sarjuuk** [comment]
hm true.
if you need it desperately add `-4` to the array [on this line](https://github.com/Sarjuuk/aowow/blob/master/pages/search.php#L642)

**Comment by wodim** [comment]
I don't run my own instance, I was hoping you could update db.rising-gods.de ?

**Comment by wodim** [comment]
Also, it would be nice if there was a way of showing titles that are hidden in the `?titles` list. I don't understand why are titles that are hidden to begin with; I expect a list like that to display all titles that exist even if they are not obtainable. I also wonder if there are other parts of aowow that hide stuff. I can also think of the zones list, that doesn't display "GM Island", and maybe even more.

**Comment by Sarjuuk** [comment]
It's going to be pushed there eventually.

Whether it makes sense to you or not to hide unimplemented or placeholder entries from non-development personal is not within the scope of this bug/issue.

**Comment by Sarjuuk** [comment]
fixed in ceedf3fbdd8ee953dd2097a8345d3690436442e7
