### ISSUE TITLE
Stupid questions(everybody can help me)

### ISSUE THREAD

**Issue by 1fosters1** [Sarjuuk/aowow#147]
Good day! I apologize for such a stupid question, but I can not step beyond the first launch of the cli. Static host and site host .... For me, these concepts mean - the name or address of the resource, to which I can "go through" to see the result, but in this case I'm confused (connection error).
I specify either the IP address or the domain name (domain zone gq), I also tried https or http.
Selinux - off
firewall - off
php7.1.2 - all modules are included
So, I thought it worked with Apache. Configured directories for Apache access to aowow and create server, there is no result ....
Please give me direction, or turn me away from these cases, I have run out of thoughts.
![default](https://user-images.githubusercontent.com/16632737/44371961-4616c500-a4ea-11e8-9882-19fcbb75d6f7.png)
![default](https://user-images.githubusercontent.com/16632737/44371993-87a77000-a4ea-11e8-9207-4bd56fd026ba.png)
![default](https://user-images.githubusercontent.com/16632737/44372020-a86fc580-a4ea-11e8-8f2b-6ca992a0e942.png)
I'm sorry, but these screenshots proof what all job, but aowow do not can run(

**Comment by Sarjuuk** [comment]
if you want to use `riseofempire.gq` then SITE_HOST is fine.
if you want to keep the folder folder structure as is STATIC_HOST should be `riseofempire.gq/static`

the thing is .. riseofempire.gq doesn't respond to requests .. at all
