### ISSUE TITLE
Titles not properly escaped

### ISSUE THREAD

**Issue by wodim** [Sarjuuk/aowow#148]
For example this next quest has \<TXT> in the title but since it's not escaped it does not appear at all (the browser interprets it as an HTML tag)

https://db.rising-gods.de/?quest=108

**Comment by Sarjuuk** [comment]
>.<

Note to self, also check Tooltip sind json

**Comment by Sarjuuk** [comment]
fixed in 31ec17d279f490d1fdcd56fb1c8d9d173ebb34ed

**Comment by Sarjuuk** [comment]
probably not :man_shrugging:
