### ISSUE TITLE
Warning: mysqli_connect(): (HY000/1045): Access denied for user '<root>'@'localhost' (using password: YES) in F:\xampp\htdocs\includes\libs\DbSimple\Mysqli.php on line 65

### ISSUE THREAD

**Issue by ctmwow** [Sarjuuk/aowow#150]
Warning: mysqli_connect(): (HY000/1045): Access denied for user '<root>'@'localhost' (using password: YES) in F:\xampp\htdocs\includes\libs\DbSimple\Mysqli.php on line 65

**Comment by Sarjuuk** [comment]
How about entering a correct db login
