### ISSUE TITLE
profiler Page not found

### ISSUE THREAD

**Issue by kep123** [Sarjuuk/aowow#152]
E:\phpStudy\www\aowow\pages\genericPage.class.php 513 Undefined index: pageName
E:\phpStudy\www\aowow\template\bricks\head.tpl.php 56 Undefined property: ProfilerPage::$gFavorites

could you help me ?

**Comment by Sarjuuk** [comment]
Did you enable this feature in your config?
Also please provide the appropriate rows from your `aowow_errors` table. They also contain the parameters for the page call.

**Comment by kep123** [comment]
One or more errors occured, while generating this page.
E_USER_WARNING - no access to auth-db or table realmlist is empty @ E:\phpStudy\www\aowow1\includes\types\profile.class.php:534

**Comment by kep123** [comment]
> Did you enable this feature in your config?
> Also please provide the appropriate rows from your `aowow_errors` table. They also contain the parameters for the page call.

One or more errors occured, while generating this page.
E_USER_WARNING - no access to auth-db or table realmlist is empty @ E:\phpStudy\www\aowow1\includes\types\profile.class.php:534

How to set it？

**Comment by Sarjuuk** [comment]
closed due to age. sorry :(

**Comment by ex1dreamer** [comment]
I've got the same issue with profiler
