### ISSUE TITLE
Wrong name of crafted item

### ISSUE THREAD

**Issue by wodim** [Sarjuuk/aowow#153]
https://db.rising-gods.de/?spell=56005

The resulting item's name in "Effect #1" is wrong.

**Comment by Sarjuuk** [comment]
yeah, somewhere a reference gets reused and i am yet to find :/

**Comment by jackpoz** [comment]
here's the fix https://github.com/TrinityCore/aowow/commit/c2e2ea51f36800901a747b3aa5390f81a3e2daa5

**Comment by Sarjuuk** [comment]
fixed in 163e3d82b0e7c9a474604b46a13afbff1ee95833
