### ISSUE TITLE
Show waypoints in another colour

### ISSUE THREAD

**Issue by wodim** [Sarjuuk/aowow#154]
It would be nice if waypoints on the map had a different colour, as opposed to the golden pins from spawn points.

For example Twinhead uses [blue pins](https://wotlk-twinhead.twinstar.cz/images/map-pin-blue.png) for waypoints. ([Example](https://vanilla-twinhead.twinstar.cz/?npc=10182))

aowow uses golden pins for both waypoints and spawn points which [looks messy](https://db.rising-gods.de/?npc=522)

**Comment by Sarjuuk** [comment]
Hrm...
I opted to display multiple paths for different spawns of the same entry in different colors each.

See here: https://db.rising-gods.de/?npc=27972

**Comment by Sarjuuk** [comment]
Dafuq, where did my comment go.. OO

anyway;
I chose to display multiple paths for multiple creatures in a unique color each.
https://db.rising-gods.de/?npc=864 is comparable to twinstar.
Perhaps the more reasonable thing would be to move the spawn point on top of the waypoints. This is currently not always the case.

**Comment by wodim** [comment]
Yes, this last comment has also disappeared. I think github is fucked today. But I get to read the comments in my inbox.

What you've said is okay, I didn't know different spawn points used different colours; that's an even better use of colours. So forget about my suggestions. It would be nice, yes, for the spawn point to always remain on top.
