### ISSUE TITLE
Achievement criteria name links not displayed

### ISSUE THREAD

**Issue by TheWinchesters** [Sarjuuk/aowow#158]
I will add two images for better explanation. (Sorry, I do not really speak english).
My case:
https://ibb.co/je0Jn0

Rising-gods:
https://ibb.co/fe29uf

**Comment by Sarjuuk** [comment]
ok step by step.
is entry 4949 set for locale esES in `world.creature_template_locale`?
is name_loc6 set for entry 4949 in `aowow_creature`?

**Comment by TheWinchesters** [comment]
Somehow, the problem was a dbc file.
I fixed by using the dbc files I had from TrinityCore installation.

**Comment by Sarjuuk** [comment]
I'm not entirely convinced the dbc files were the reason it broke. 
Anyway, fine if it works for you.
