### ISSUE TITLE
Install the new version there is an error

### ISSUE THREAD

**Issue by kep123** [Sarjuuk/aowow#159]
E:\phpStudy\www\aowow2>php aowow --firstrun
PHP Parse error:  syntax error, unexpected '|', expecting ',' or ';' in E:\phpSt
udy\www\aowow2\includes\profiler.class.php on line 10
E:\phpStudy\www\aowow2>php aowow --firstrun
PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in E:\phpSt
udy\www\aowow2\includes\smartAI.class.php on line 54

**Comment by Sarjuuk** [comment]
Hmm, your version of php is outdated.
But I'll have to check when return type hints were implemented.

Also at some point const. expressions in class declarations were permitted. Probably prior to return type hints.

**Comment by kep123** [comment]
Ok, thank you very much
I will complete the localization(zh_cn) work as soon as possible

**Comment by Sarjuuk** [comment]
return type declarations are php v7.0 or higher. You can check your version with `php -v`on the console.

i need to update the requirements in readme.md and startup checks
