### ISSUE TITLE
"This item is not available to players." is missing

### ISSUE THREAD

**Issue by TheWinchesters** [Sarjuuk/aowow#160]
I do not have the  " This item is not available to players." message and I do not know why.
I am sure is a problem just for me.
Where should I check?

For example: https://db.rising-gods.de/?item=39303
In my case, I have not the red message "This item is not available to players." and I have not "Not available to players" neither.

**Comment by Sarjuuk** [comment]
...I suspect the source query fails, because the quest_template structure changed.

Remember..?

**Comment by Sarjuuk** [comment]
hm, nope .. no idea.
there should be ~44k entries in `aowow_source` for you and.
```sql
select 1 from aowow_source where type = 3 and typeId = 39303; -- should return empty
select count(*) from aowow_items where cuFlags & 0x20000000; -- should return about 4.3k entries
```

**Comment by TheWinchesters** [comment]
My case:
40879 entries en `aowow_sorce`
`select 1 from aowow_source where type = 3 and typeId = 39303;` returns empty
`select count(*) from aowow_items where cuFlags & 0x20000000;` returns 0

Where does the database look for information on whether an item is available to players or not?
What do I need to change if I want to do it manually?
I am pretty sure I am the only one with this problem so I would like to have some simple way to solve it, it does not matter if that means changing each item by hand.

**Comment by Sarjuuk** [comment]
This query here failed for some reason:
https://github.com/Sarjuuk/aowow/blob/master/setup/tools/sqlgen/source.func.php#L1051
try executing it manually. Maybe it throws an error for you. (Ofc after replacing the variables)

**Comment by TheWinchesters** [comment]
What should I use instead of '?d'?

**Comment by TheWinchesters** [comment]
I understood!
I have executed this:
`UPDATE aowow_items i LEFT JOIN aowow_source s ON s.typeId = i.id AND s.type = 3 SET i.cuFlags = i.cuFlags | 536870912 WHERE s.typeId IS NULL;`
With no errors, and finally I have the correct list of items that are not available for players.

**Comment by Sarjuuk** [comment]
whatever made it skip over this query in the first place...
