### ISSUE TITLE
If a search only returns one kind of result, there is no indication of what kind it is

### ISSUE THREAD

**Issue by wodim** [Sarjuuk/aowow#162]
Can't really explain myself...

https://db.rising-gods.de/?search=wintergrasp+fortress

There is no indication anywhere in the page that all of these are objects and not NPCs or whatever. Maybe the tab bar should be drawn even if there is only one kind of result?

**Comment by Sarjuuk** [comment]
![](https://screenshotscdn.firefoxusercontent.com/images/d16a19b6-ff6b-4f7d-bd0b-44f49eda8675.png)

..wat?

**Comment by wodim** [comment]
That is definitely not what I see.

![image](https://user-images.githubusercontent.com/1001553/49304313-44d33c00-f4cc-11e8-9f0e-4e68185e4955.png)

**Comment by wodim** [comment]
You can't reproduce the bug because you seem to be running another version of aowow or the database.

Can you reproduce it with this? https://db.rising-gods.de/?search=Wintergrasp+Fortress+Wall

**Comment by Sarjuuk** [comment]
nah.. i get the sub-zone displayed, because i'm logged in as staff.

anyway, fixed in af7b9f57b0ac599f12e5c075d8bca9ad365d547a

**Comment by wodim** [comment]
Why is such feature restricted to staff? What else is restricted?

**Comment by Sarjuuk** [comment]
in short, a lot!
In case of search it removes a crap load of clutter from the results, the average user is not interested in. That is not going to change.

**Comment by wodim** [comment]
Would it be possible for me to get one of those accounts?
