### ISSUE TITLE
PHP parse error

### ISSUE THREAD

**Issue by Viste** [Sarjuuk/aowow#163]
PHP 7.2 can't understand construction in config.php:

`root@vps6808:/var/www/html# php7.2 aowow
PHP Parse error:  syntax error, unexpected '<', expecting ']' in /var/www/html/config/config.php on line 41
`
i change it to 
`$AoWoWconf['characters'][realmId] = array(`
from
`$AoWoWconf['characters'][<realmId>] = array(`

**Comment by Sarjuuk** [comment]
RTFM and stop manually editing random files.

cc5be5261c3000517c4b62b731338049a0fdaeb5

**Comment by Viste** [comment]
don't need be a jork 
your manual is shit your cli output is more shit, so do it user frendly or get ready to answer questions :)
