### ISSUE TITLE
DBC errors when install

### ISSUE THREAD

**Issue by Viste** [Sarjuuk/aowow#164]
Can't understand why aowow can't read my dbc (ruRU client) put it in setup/mpqdata and after first error duplicate it into setup/mpqdata/dbc
also give 777 right but
`12:28:37          SqlGen::generate() - filling aowow_talents with data
12:28:37  [ERR]   no suitable files found for talent.dbc, aborting.
12:28:37  [ERR]   SqlGen::generate() - required DBC talent.dbc not found!

[c]ontinue anyway? [r]etry? [a]bort?: 
12:28:37          SqlGen::generate() - filling aowow_classes with data
12:28:37  [ERR]   no suitable files found for spell.dbc, aborting.
12:28:37  [ERR]   SqlGen::generate() - required DBC spell.dbc not found!

[c]ontinue anyway? [r]etry? [a]bort?: 
12:28:37          SqlGen::generate() - filling aowow_factions with data
12:28:37  [ERR]   no suitable files found for faction.dbc, aborting.
12:28:37  [ERR]   SqlGen::generate() - required DBC faction.dbc not found!
`

**Comment by Sarjuuk** [comment]
README.md
Seriously, read and follow it. 

Nowhere it tells you to just dump a bunch of dbc files into /mpqdata

**Comment by Viste** [comment]
yes there is nothing about dbc files but why script want to find it xD

**Comment by Viste** [comment]
step 4 is more confusing then config

**Comment by Sarjuuk** [comment]
failed to put in minimum effort.
