### ISSUE TITLE
Handle quest series which converge

### ISSUE THREAD

**Issue by wodim** [Sarjuuk/aowow#165]
As an example, [Magisters' Terrace](https://db.rising-gods.de/?quest=11488) can be started by both [Crisis at the Sunwell](https://db.rising-gods.de/?quest=11481) and [Duty Calls](https://db.rising-gods.de/?quest=11482), but if you look in the "Series" section of the page for Magisters' Terrace, it looks like only Crisis at the Sunwell begins the quest, presumably because it has a lower id.

Would be nice if the list of quests said something like "1. Crisis at the Sunwell or Duty Calls"

**Comment by PolarCookie** [comment]
https://github.com/TrinityCore/TrinityCore/issues/23174
for that particular case

**Comment by Sarjuuk** [comment]
yup, it's fixed with the implementation of breadcrumbs.

d4c0c0535a689ccf58d384b1f9a24245cb81b5dd
