### ISSUE TITLE
Add a category for mails

### ISSUE THREAD

**Issue by wodim** [Sarjuuk/aowow#166]
1. NPC pages. Example: add a tab on [Mei Francis](https://db.rising-gods.de/?npc=32216)' page for the letter she sends you after finishing [Mountain o' Mounts](https://db.rising-gods.de/?achievement=2536).

2. An entry, "Mail", in the Database dropdown, which lists all letters like that one.

**Comment by Sarjuuk** [comment]
1.) eh dunno... what would happen if y lot of mail gets send from one npc
2.) might be interesting. Though, there are roughly 250 mails in mailtemplate.dbc and 100 of them are lunar festivals "i Was very grateful for your visit today [..]"

**Comment by Sarjuuk** [comment]
added in fd04e9f97784823000cfd8e6ca4db99ca26f217c
