### ISSUE TITLE
No response from server :(

### ISSUE THREAD

**Issue by Morpheusxeno** [Sarjuuk/aowow#167]
When mousing over an item I get the error No Response From Server :(
https://i.imgur.com/qGhYWJX.png

When I checked the logs I saw something along the lines of...

No matching DirectoryIndex (index.php) found, and server-generated directory index forbidden by Options directive, referer: 

I included and removed options in the htaccess to allow directory index with + instead of - It removed the error but still doesnt show the tooltips?

**Comment by Sarjuuk** [comment]
Every modern browser has a build in dev-tool  (opens with F12 probably)
There is a tab called something like "connections", that lists every request your browser makes to the server. 
Find one for a tooltip and send me the request-url and full response please.

**Comment by Morpheusxeno** [comment]
https://i.imgur.com/OYDwGxL.png
https://i.imgur.com/yGUrNMb.png

https://db.m-a-t-r-i-x.com/static/?item=37257&domain=www&power

**Comment by Morpheusxeno** [comment]
Do you mind talking real time on discord?

**Comment by TheWinchesters** [comment]
Could this be the problem?
`var g_host      = 'https://m-a-t-r-i-x.com/matrixhead/static';`

**Comment by Morpheusxeno** [comment]
Ill check it one second, I dont know why that links there...

**Comment by Morpheusxeno** [comment]
https://i.imgur.com/ZHEsrzd.png

Where is that var g_host set ?

**Comment by TheWinchesters** [comment]
I saw it in your power.js
You should check your SITE_HOST and STATIC_HOST
1. Connect to your server:
2. php aowow --siteconfig
3. Select 13
4. Press E to edit SITE_HOST
5. If your db is https://db.m-a-t-r-i-x.com/ SITE_HOST shoudl be 'name_of_your_host'
3. Select 18
4. Press E to edit STATIC_HOST
5. If your db is https://db.m-a-t-r-i-x.com/ STATIC_HOST shoudl be 'name_of_your_host/static'

**Comment by Morpheusxeno** [comment]
What do you mean by Name of your host?

**Comment by TheWinchesters** [comment]
The namw of your site without https://
Try db.m-a-t-r-i-x.com

**Comment by Morpheusxeno** [comment]
Alright.

**Comment by Morpheusxeno** [comment]
Looks to be fixed. Thank you.

**Comment by TheWinchesters** [comment]
Great!
You are welcome!
