### ISSUE TITLE
Show item prices in currency pages

### ISSUE THREAD

**Issue by wodim** [Sarjuuk/aowow#168]
https://db.rising-gods.de/?currency=161#currency-for

You've got to click the items to see how many Stone Keeper's Shards they are worth. It would be better if that amount was displayed right there. It's already displayed in the [SKS item page](https://db.rising-gods.de/?item=43228#currency-for), so maybe you could link  to that page from the currency page?

**Comment by Sarjuuk** [comment]
Dunno...
Prices are per vendor and an item can be sold by multiple vendors.
How would that be resolved..?

**Comment by wodim** [comment]
Why is that a problem in the currency page and not in the item page? The item page just adds another column for price...

**Comment by Sarjuuk** [comment]
hrm .. if there are multiple results they are probably discarded.

**Comment by Sarjuuk** [comment]
the real kicker is, the (costly) calculations where already run, but the result wasn't displayed, because the column was missing.

ead6e72
