### ISSUE TITLE
NPC classified as "undefined"

### ISSUE THREAD

**Issue by wodim** [Sarjuuk/aowow#170]
https://db.rising-gods.de/?zone=394 _"Buckets" Cleary_ (second one)

Probably a bug in the database, but aowow should handle that case I imagine.

**Comment by Sarjuuk** [comment]
there are 20 creatures with rank 5 in a standard database, while only ranks 0 - 4 are defined .. weird

34fe4c2654dd41ff0a67a54882d3ac5aa1d8980a
