### ISSUE TITLE
Add "icon" to infobox

### ISSUE THREAD

**Issue by TheWinchesters** [Sarjuuk/aowow#171]
Nowadays wowhead has a "icon" field in the Quick facts.
Example: https://www.wowhead.com/spell=46579/deathfrost
Would it be possible to add that to aowow?

I have found a way but I do not think it is the best one.

**Comment by TheWinchesters** [comment]
I like that but ok.
I will keep trying a good way to add it to my page and I will share here if anyone needs it.

**Comment by Sarjuuk** [comment]
it should look a lot like this^^

392610b899952885b691220e867f5bee14a0324e

**Comment by TheWinchesters** [comment]
Oooh, great! and Thank you.
I though it was useful because there you have the name of the file.
I was trying to improve the TC minimanager and this is perfect if some icons are missing.

Mine was different.
Using `$this->extendGlobalData($iconshow->getJSGlobals());` and another changes in Markup.js to make it work but I was not convinced of it.

**Comment by Sarjuuk** [comment]
Just remember, there are cases where Aowow overrides the icon. 

E.g. glyph trade skills by base have the ink and parchment icon, but display the icon of the spell they are going to affect.
