### ISSUE TITLE
Show respawn times in minutes and seconds

### ISSUE THREAD

**Issue by wodim** [Sarjuuk/aowow#172]
https://db.rising-gods.de/?npc=2972

4.17 minutes = 4:10 minutes. Why not show it like that?

**Comment by Sarjuuk** [comment]
The time formatting function was originally designed for spell tooltips/buffs. They do indeed format time as a float. 

The system is too rigid at the moment and should be overhauled, yes..

**Comment by Sarjuuk** [comment]
![grafik](https://github.com/Sarjuuk/aowow/assets/848030/d92b987b-dc4f-4d2c-829a-e4e5ae00dac8)
