### ISSUE TITLE
Order zones in which an NPC can be found by amount of spawn points

### ISSUE THREAD

**Issue by wodim** [Sarjuuk/aowow#174]
https://db.rising-gods.de/?npc=6491

In this case it would not be very useful, but if you're trying to farm something...

**Comment by jackpoz** [comment]
Fixed in https://github.com/TrinityCore/aowow/commit/56aac1cf6c125c55b1f2190dbcd7be65d6b7a478

**Comment by Sarjuuk** [comment]
fixed in 1f84cae1ddb3cfa5c93d34f72ec86109d95d58ca

thx
