### ISSUE TITLE
aowow_creature is empty

### ISSUE THREAD

**Issue by qyh214** [Sarjuuk/aowow#176]
After TrinityCore/TrinityCore@bf3ab6d9c4366dae1d34957813e3fbf40ac8532b
aowow_creature will empty When `php aowow --firstrun` or `--sql` because some columns transferred location

**Comment by kep123** [comment]
是不是没添加loc4

**Comment by caicaicai** [comment]
how to fix ?any idea?

**Comment by jackpoz** [comment]
if you enable debug config and run it again, you'll notice sql errors in the log. This is because latest TDB structure is different than what aowow expects.
To fix:
- use the TDB version in the readme
- or the queries and submit a pull request

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/aowow/pull/19 adds support to latest TDB

**Comment by Sarjuuk** [comment]
caught up to TC for now with 5bb15d47d7ad08d90985d8b89727b7794eeeebfd
