### ISSUE TITLE
Display breadcrumbs

### ISSUE THREAD

**Issue by PolarCookie** [Sarjuuk/aowow#179]
Breadcrumb quests are supported in https://github.com/TrinityCore/TrinityCore/commit/5ed77113b637c49e99a610b00f385c51da67c3bf
Many quest linking might "disappear" on the database site.

**Comment by Sarjuuk** [comment]
thx for the notice.
implemented in d4c0c0535a689ccf58d384b1f9a24245cb81b5dd
