### ISSUE TITLE
Enable sidebar and ad spots?

### ISSUE THREAD

**Issue by dkpminus** [Sarjuuk/aowow#180]
Hey Sarjuuk,

First of all awesome work maintaining this project! My apologies if this was asked before, I checked through all open and closed issues. I'm trying to determine how to enable the sidebar to add a banner spot. 

I can see in the header.tpl there is this line and `nosidebar` can be changed to `sidebar` which changes the content width:
`<div class="layout nosidebar" id="layout">`
However the sidebar div doesn't seem to exist in this version.

Not sure if I'm missing anything on it. Any help would be appreciated!

**Comment by Sarjuuk** [comment]
will not reimplement ads
