### ISSUE TITLE
NPCs have no abilities

### ISSUE THREAD

**Issue by wodim** [Sarjuuk/aowow#182]
I've tried many NPCs and none show any abilities.

**Comment by Aokromes** [comment]
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=6570

**Comment by Sarjuuk** [comment]
cannot reproduce. maybe fixed in-between?

**Comment by wodim** [comment]
https://db.rising-gods.de/?npc=6570 <- compare this to the link posted above

**Comment by wodim** [comment]
https://db.rising-gods.de/?npc=677 vs https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=677, etc

**Comment by Sarjuuk** [comment]
ah, i see now.

Rising Gods did not wish to publish SAI, so everything related to SAI is gone. 
This is not a bug of Aowow.
