### ISSUE TITLE
In welcher Datei füge ich --firstinstall und wo genau ein --- In which file do I add --firstinstall and where exactly?

### ISSUE THREAD

**Issue by Xardas88073** [Sarjuuk/aowow#184]
In welcher Datei füge ich --firstinstall und wo genau ein ??? Ich bekomme deswegen nicht mal das Setup hin. Ich wäre sehr dankbar für eine Antwort. 

In which file do I add --firstinstall and where exactly? That's why I do not even get the setup. I would be very grateful for an answer.

**Comment by Xardas88073** [comment]
also in der CLI geht es bei mir nicht mit xampp

**Comment by Xardas88073** [comment]
C:\xampp\php>php.exe C:\xampp\htdocs\aowow\setup\setup.php --firstrun
illegal access

**Comment by Xardas88073** [comment]
Am besten wäre es, wenn es ohne CLI gehen würde. 

It would be best if it would go without CLI.

**Comment by wodim** [comment]
`cd C:\xampp\htdocs\aowow\`

`php aowow --firstrun`
