### ISSUE TITLE
Objects with empty names have no titles

### ISSUE THREAD

**Issue by wodim** [Sarjuuk/aowow#185]
For example: https://db.rising-gods.de/?zone=139#objects -> https://db.rising-gods.de/?object=175432

No title on tooltip, and then no page heading or <title>. Should be "Unnamed Object #xxx" or something?

**Comment by Xardas88073** [comment]
please tell me how you install it exactly

**Comment by Sarjuuk** [comment]
fixed in 717e9c43be546c2934642ef51441d94078fb91db
