### ISSUE TITLE
Items 7 & 3 doesn't show (Util::arraySumByKey)

### ISSUE THREAD

**Issue by Xeoxit** [Sarjuuk/aowow#187]
Hello @Sarjuuk first of all, nice work you did by continuing this Project.

Sadly to say but i have here some Problems and i'm not sure if this is because of PHP7.1/7.2

My AoWoW is running on Debian jessie with PHP7.1 and everything works great except when you go to: https://db.rising-gods.de/?items=3 & https://db.rising-gods.de/?items=7 
it says: Site not Found. I also get here an entry from aowow_errors

Version: 28

**phpError:** 0
**File affected:** /home/public_html/aowow/includes/utilities.php
**Line:** 787

**Query:** items=7 **and** items=3
**Message:** Argument 1 passed to Util::arraySumByKey() must be of the type array, null given, called in /home/public_html/aowow/includes/types/item.class.php on line 1278

I hope i did everything well so far because this two issues are the only one.
Thank you

**Comment by jackpoz** [comment]
item 3 and item 7 are not standard items, are they ?

**Comment by Sarjuuk** [comment]
probably fixed in 1c7660316d1e56412be9bdf87cfc5001484e699c
