### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by maikale** [Sarjuuk/aowow#189]
38/5000
Hello can you tell me where i am wrong

http://alfa.kachi-snimka.info/images-2013/bwy1578325829v.png

**Comment by DevCores** [comment]
Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in C:\Web\data\includes\utilities.php on line 1025

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in C:\Web\data\includes\utilities.php on line 1080

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in C:\Web\data\includes\community.class.php on line 128

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in C:\Web\data\pages\genericPage.class.php on line 856
The website is currently closed for maintenance.
This will take a few minutes...

**Comment by DevCores** [comment]
Has anyone solved the problem or knows the solution?

**Comment by jackpoz** [comment]
I fixed some issues at https://github.com/TrinityCore/aowow and got it up and running

**Comment by Sarjuuk** [comment]
fixed in 1c08e5d9cf6e17839f5dd124fc9994869bbe0e62
