### ISSUE TITLE
Zones/Maps : missing coordinates for many areas (dbc_worldmaparea)

### ISSUE THREAD

**Issue by Valkirie** [Sarjuuk/aowow#192]
When generating the database based on wotlk dbcs, the dbc_worldmaparea is missing many locations details and coordinates preventing us to have creatures locations displayed in many areas.

It seams db.rising-gods.de have those filled.

**Comment by Sarjuuk** [comment]
you'll have to manually merge 4.0.3 data into worldmaparea.dbc and dungeonmap.dbc. and copy the appropriate map files over.

This will not be part of this project.
