### ISSUE TITLE
need to update the characters database

### ISSUE THREAD

**Issue by kep123** [Sarjuuk/aowow#194]
'skincolor'         =>  $char['skin']        & 0xFF,
            'facetype'          => ($char['face'] >>  8) & 0xFF, // maybe features
            'hairstyle'         => ($char['hairStyle'] >> 16) & 0xFF,
            'haircolor'         => ($char['hairColor'] >> 24) & 0xFF,
            'features'          =>  $char['facialStyle']       & 0xFF, // maybe facetype
            'activespec'        => $char['activeTalentGroup'],

        $t = DB::Characters($realmId)->selectCol('SELECT talentGroup AS ARRAY_KEY, spell AS ARRAY_KEY2, spell FROM character_talent WHERE guid = ?d', $char['guid']);
        $g = DB::Characters($realmId)->select('SELECT talentGroup AS ARRAY_KEY, glyph1 AS g1, glyph2 AS g4, glyph3 AS g5, glyph4 AS g2, glyph5 AS g3, glyph6 AS g6 FROM character_glyphs WHERE guid = ?d', $char['guid']);

in profile.class.php
.
.
.

update locale_zhcn.js
[locale_zhcn.zip](https://github.com/Sarjuuk/aowow/files/4265853/locale_zhcn.zip)
![5](https://user-images.githubusercontent.com/13764374/75522189-521b0580-5a44-11ea-8a8c-df4177872773.jpg)

**Comment by kep123** [comment]
![3](https://user-images.githubusercontent.com/13764374/75521559-fdc35600-5a42-11ea-914c-6508801ab5bc.jpg)
some erro!

**Comment by Sarjuuk** [comment]
thank you for pointing out the database issue and supplying the localization. 

I'm not sure why you are getting js errors though

**Comment by kep123** [comment]
> thank you for pointing out the database issue and supplying the localization.
> 
> I'm not sure why you are getting js errors though

JS has had no errors

![image](https://user-images.githubusercontent.com/13764374/75610262-a27c8b00-5b4a-11ea-836e-cc2151468ba9.png)
