### ISSUE TITLE
parseTime() and formatTime(), milliseconds and negatives plurals

### ISSUE THREAD

**Issue by Helias** [Sarjuuk/aowow#196]
In the function `parseTime()` only if the time is less than 0 the execution of the code succeed the condition of "**milliseconds**", indeed if I give as input of parseTime a time less than 0, so a negative one, the condition succeed and it returns me the string "milliseconds".

Here the code responsible https://github.com/Sarjuuk/aowow/blob/master/includes/utilities.php#L461
if we test this, the condition of milliseconds will never happen, because 1 millisecond 0.001 is more than 0, so the condition of seconds succeed and not the condition of milliseconds.
To fix this we just need to change the condition in this way:

```php
if ($sec >= 1)
```

Moreover, there is another bug, but in `formatTime()` if I give as input a negative value the plurals do not work correctly, because in the condition where we check to use singular or plural we just compare the time to 1 but if the time is -1 the condition will not succeed.

The responsible code of this is the following, to fix it we need to apply abs() to the time. https://github.com/Sarjuuk/aowow/blob/master/includes/utilities.php#L503

**Example**: s.s === 1 if it is "1 **second**" but we do not compare s.s === -1, we just need to applay absolute to these conditions.

I will open a PR for this.

**Comment by Sarjuuk** [comment]
Also, I'm passing whole seconds (as integer) to parseTime () and expect milliseconds to come out. Oh joy....

I'll check this out in its entirety tomorrow.

**Comment by Helias** [comment]
Thank you for your availability :grin:

**Comment by Sarjuuk** [comment]
fixed in 15246ea96499cba0f7977817baa97cc613f058c8

thx again
