### ISSUE TITLE
Zone overview of Dungeons/Raids 

### ISSUE THREAD

**Issue by Jinnaix** [Sarjuuk/aowow#198]
The zone overview displays results that should not be displayed, but omits results that should be displayed.

https://db.project-nemesis.org/?zones=3.2
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?zones=3.2

**Missing WotLK Raid:**

Onyxias Lair

**WotLK Raids:**

Name | Status
-- | --
Icecrown Citadel | OK
Naxxramas | OK
Putricide's Laboratory of Alchemical Horrors and Fun | Wrong - ICC Sub Wing
The Crimson Hall | Wrong - ICC Sub Wing
The Eye of Eternity | OK
The Frost Queen's Lair | Wrong - ICC Sub Wing
The Frozen Throne | Wrong - ICC Sub Wing
The Obsidian Sanctum | OK
The Ruby Sanctum | OK
The Sanctum of Blood | Wrong - ICC Sub Wing
Trial of the Crusader | OK
Ulduar | OK
Vault of Archavon | OK

**Classic Dungeons**
https://db.project-nemesis.org/?zones=2.0
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?zones=2.0

Name | Status
-- | --
Unused Ironcladcove | Shouldnt be listed
The Great Sea | Shouldnt be listed
Sunken Temple | Shouldnt be listed - correct one is Temple of Atal Hakkar

**Comment by Sarjuuk** [comment]
fixed in 9b4c0bb09e6523e4e4518b15fef40e25615c675e




.... fuck zone logic >:(
