### ISSUE TITLE
Aowow ignore port

### ISSUE THREAD

**Issue by Rohlik** [Sarjuuk/aowow#20]
Hello again,
I use this great Aowow on site http://3server.net:8088/ but I have almost empty page.
I figured out why - Aowow ignore ":" in static and site host from  ?_config as you can see here:
```
var g_staticUrl = "http://3server.net8088/static";
        var g_host = "http://3server.net8088";
```
Can you help me?

**Comment by Sarjuuk** [comment]
strings are checked against a regEx that seems to be too strict here. https://github.com/Sarjuuk/aowow/blob/master/includes/kernel.php#L84 the colon has to be added to the list of allowed characters. (i did not think of ports, my bad)

this will probably need to be also applied here
https://github.com/Sarjuuk/aowow/blob/master/includes/ajaxHandler.class.php#L688

**Comment by Rohlik** [comment]
It´s works! Thank you.
