### ISSUE TITLE
Profiler : SQL request outdated

### ISSUE THREAD

**Issue by Endalaust** [Sarjuuk/aowow#201]
Hello Sarjuuk 
We haven't spoken in years. I hope you're okay ;)

https://github.com/Sarjuuk/aowow/blob/master/includes/types/profile.class.php#L617 
`SELECT guid AS ARRAY_KEY, spell AS ARRAY_KEY2, spec FROM character_talent`

spec = talentGroup right now 
=> https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2129968/character+talent

**Comment by Sarjuuk** [comment]
good lord, thats old .. https://github.com/TrinityCore/TrinityCore/commit/f8230a59a9e878a6f54f421d6621f1595bd93861
i should check other character references while at it  >_<

I'm alright. :] 
Having to program/debug as part of my day to day job kinda killed my interest to work/debug on this in my spare time though.

**Comment by Endalaust** [comment]
Yeah, since 2015 !

Well, I use aowow since 2015 too (https://github.com/Sarjuuk/aowow/issues?q=author%3AEndalaust) Time passes, but for me you are still active, year after year and this project is still great :)

Profiler looks like amazing, I wanted to try it (without succeeding as usual haha)

**Comment by Sarjuuk** [comment]
should be fixed in a1d3be86f7e85622067b74b0c5d7ca2cb00281bb

the fact, that you usually pinpoint these errors is very helpful though :+1:
