### ISSUE TITLE
PHP error under admin account

### ISSUE THREAD

**Issue by ex1dreamer** [Sarjuuk/aowow#202]
Works Ok until I enter under admin account. Follwoing error is displayed:
One or more errors occured, while generating this page.
E_NOTICE - Undefined index: prefix @ C:\Apache24\htdocs\***\includes\database.class.php:36

**Comment by Sarjuuk** [comment]
you manually edited `config/config.php`
the prefix is automatically set when the setup is run properly
run `php aowow --dbconfig` to fix this

also the E_NOTICE always occurs, it's just displayed directly to you, when you are logged in as admin.

**Comment by ex1dreamer** [comment]
I still cannot understand how to run dbconfig properly. it seems all other databaes apart of aowow not connected properly. Why db config asks for table prefix each time. In php code  table prefix has been set only once as aowow_. trinity auth and character DBs are connected but also askign for table prefix. what should I use? no prefix doesn't work eaither.

**Comment by Sarjuuk** [comment]
rel #206
