### ISSUE TITLE
Profiler Resync didn't work

### ISSUE THREAD

**Issue by gonzo1247** [Sarjuuk/aowow#203]
Today is set up the aowow and after some problems most works now. Thx for this Work here.
But it's not possible to view a Character with the Profiler. Its starting the resync and nothing happens. 
I have allready look into aowow_error table (and enabled debug in config) but not realy a message appears. The last errors:
Undefined index: activespec (in includes/types/profile.class.php -> line 650)
A non-numeric value encountered (in includes/types/profile.class.ph -> line 36)
and:
exec() has been disabled for security reasons
Profiler::scheduleResync() - failed to start queue

if i do something wrong?

edit:
ah and most of wotlk items are only have a big red ? in overviewe and no icon if select a item. i think its missing the icons or?

**Comment by Sarjuuk** [comment]
> exec() has been disabled for security reasons  
> Profiler::scheduleResync() - failed to start queue  

There it is. 
I used exec to start a seperate php process to act as a queue to fetch char data. exec being disallowed brakes this obviously.

You could disable the shutdown when idle
https://github.com/Sarjuuk/aowow/blob/master/prQueue#L57-L60 replace this with 
```
$tCycle = microtime(true);
continue;
```

and start/stop it manually, preferably in a screen
`php prQueue`

**Comment by gonzo1247** [comment]
Thanks, its works now. But after reload the site, the site is blank. No Character displayed or somethin other about the character. 
the error log says nothing.

**Comment by Sarjuuk** [comment]
> blank

can you be more specific?

**Comment by gonzo1247** [comment]
yea like empty search results. you can see this here: https://dbwotlk.riseofazhara.de/?profile=eu.rise-of-azhara-wotlk.sevi

**Comment by Sarjuuk** [comment]
https://dbwotlk.riseofazhara.de/?achievement=1316

**Comment by gonzo1247** [comment]
In Quest or text, the $ switch work. I added the Achievement 1316 to self, and server crashed, so i think it's not right handle from server.
But we didn't have custom achievements? Thats all about a fresh wow 3.3.5a client.

**Comment by Sarjuuk** [comment]
Ok, i've found this achievement in the achievement.dbc from the locale-deDE.mpq.
That means you did not extract the "patch"-mpqs or got the order wrong when extracting the games archives, as it is no longer present in the 3.3.5.r12340 build.

try this: https://gist.github.com/Sarjuuk/e171bf5e7e9f7503a779

**Comment by gonzo1247** [comment]
Thanks, i try your script and its works. The achievement is now "away" 

Now the most item icons area available, but the newer items has no icon.

**Comment by Sarjuuk** [comment]
Its just the icon files themselves missing. Probably a leftover from unpacking the mpq archives wrong.

**Comment by gonzo1247** [comment]
Oke thanks for your help. I will search with Icons are missing and search it in the mpq achives.
