### ISSUE TITLE
Object page doesn't work

### ISSUE THREAD

**Issue by Endalaust** [Sarjuuk/aowow#204]
Hi Sarjuuk, what's up? :)

Since your last commit https://github.com/Sarjuuk/aowow/commit/6cabfd3864c03b731b7d7bbe4acb2d65d6b47319 all object page are KO (404)

You can see here : 
https://woehead.way-of-elendil.fr/?objects 
https://woehead.way-of-elendil.fr/?object=1648

I have only this log, but I don't think it's the main problem
<img width="218" alt="screenshot_1137" src="https://user-images.githubusercontent.com/1420867/82839588-276c0c00-9ed0-11ea-9187-f3f423ffcc0a.png">

**Comment by Sarjuuk** [comment]
whoops

fixed in 7db841b823923c32527f6ee7d3b73f4f2e1ac4c7
