### ISSUE TITLE
How to run dbconfig correctly

### ISSUE THREAD

**Issue by ex1dreamer** [Sarjuuk/aowow#206]
Hello,

I'm still cannot figure out how to execute dbconfig. 
When I run it with empty config.php, only aowow databse is correctly connected. 
When I'm trying to choose option [1] world - php script asks for "Table prefix:" - then I can enter anything or empty field and script finishes with "empty" status string and records to php config only:
$AoWoWconf['world'] = array (
  'prefix' => '*whatever*',
);
Script do not asks for host, DB name and pass etc.

After restart dbconfig will ask for host, database name etc. bit still asking for table prefix for world, auth and characters databases. What I suppose to enter?

**Comment by Sarjuuk** [comment]
fixed in 184e5e5c8dbdd2c0822a5bbd7b18d4c279ccb95e

also stop spamming unrelated issues
