### ISSUE TITLE
[Question] Updating of Tables

### ISSUE THREAD

**Issue by Jinnaix** [Sarjuuk/aowow#213]
Sorry if this is the wrong place to ask, but since there is no Wiki or Forum for Aowow that i am aware of, i thought asking here might be an option.

Some functions read directly from the server database and update changes live, like loot tables and smart ai.
Others seem to not do this, like quests.

What is the correct way for updating these tables after changes without starting from scratch? 

--sync or --build dont seem to do the trick
![image](https://user-images.githubusercontent.com/37972361/88892796-ad486280-d245-11ea-990d-d4746a622e48.png)

**Comment by Sarjuuk** [comment]
`--sync` is the right choice. You have to pass the affected world tables with this command (see below)
```
sarjuuk@dev01:~/public_html/aowow$ php aowow --sync=quest_template
15:22:36          begin generation of areatrigger, quests, titles, source
15:22:36          SqlGen::generate() - filling aowow_areatrigger with data
[...]
```

**Comment by Jinnaix** [comment]
thank you very much :)
