### ISSUE TITLE
[SAI] Wrong coordinate shown

### ISSUE THREAD

**Issue by Jinnaix** [Sarjuuk/aowow#214]
Seems like there are cases where AoWoW shows wrong coordinates for SAI Target Position.

Example:
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=4966#sai-actionlist-496601

![image](https://user-images.githubusercontent.com/37972361/89694798-10a35600-d912-11ea-8d41-68941acb9a6e.png)

Database looks like this:
![image](https://user-images.githubusercontent.com/37972361/89694823-2fa1e800-d912-11ea-850f-2c3f4c6035e0.png)

Maybe somehow related to the Zero in orientation?

**Comment by Sarjuuk** [comment]
hm, looks like the fields are offset by one for some reason

**Comment by Sarjuuk** [comment]
fixed in 349c32d0a6ace5dd8f0d50335ef890dd40acab48
