### ISSUE TITLE
add inmunity masks, flags, etc to npcs

### ISSUE THREAD

**Issue by Aokromes** [Sarjuuk/aowow#218]
at https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=15688

**Comment by Sarjuuk** [comment]
![image](https://user-images.githubusercontent.com/848030/91874939-1a9f4700-ec7b-11ea-8f07-34f663d72cc3.png)
like this? That is already implemented.

**Comment by jackpoz** [comment]
It would be nice if there was a setting to always show these things no matter what profile a user has (I see some of these are wrapped around if (User::isInGroup(U_GROUP_STAFF)) )

**Comment by Sarjuuk** [comment]
I think for your use case (https://tcubuntu.northeurope.cloudapp.azure.com/aowow) it might be best to hard assign (bitwise or) `U_GROUP_TESTER` to every user session.
See `includes/user.class.php` override default definition and application in `User::init ()`(I believe)

**Comment by jackpoz** [comment]
is U_GROUP_TESTER supposed to show those U_GROUP_STAFF wrapped sections ? Or maybe it was just left out from U_GROUP_STAFF by mistake ?

**Comment by Sarjuuk** [comment]
apologies, try U_GROUP_BUREAU
U_GROUP_STAFF is a combination of several groups.
https://github.com/Sarjuuk/aowow/blob/583f8658d7f043643db51ab754495d4baf49614c/includes/defines.php#L155-L161
