### ISSUE TITLE
"Jump Behind Target" spell effect does not link to the NPC

### ISSUE THREAD

**Issue by wodim** [Sarjuuk/aowow#220]
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=14329

9527 should instead be a link to https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=9527

**Comment by Sarjuuk** [comment]
Does "jump behind target" usually has its target stored as MiscValue? 
(also, why has a serverside spell titled "summon" a jump effect?)

**Comment by wodim** [comment]
You are right, I don't know why I assumed that. I've found a few counterexamples: https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=55518

Regarding your other question, I've got no idea. It might be something to investigate...

**Comment by wodim** [comment]
Another example: https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=17694

**Comment by Sarjuuk** [comment]
to quote shauren "those are spells used by guard post gameobjects that arent implemented"
Also, they are most likely wrong and need to be fixed.
