### ISSUE TITLE
Pins in maps in tooltips are off

### ISSUE THREAD

**Issue by wodim** [Sarjuuk/aowow#223]
For example, here: https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?zone=28#objects

If you look for "Caer Darrow Skeleton 001" it looks like it is in the northwest part of the island:

![image](https://user-images.githubusercontent.com/1001553/93278071-e885fd00-f7c3-11ea-90e0-86f548aae17f.png)

But it's actually a bit to the bottom of the pin: https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?object=176745

![image](https://user-images.githubusercontent.com/1001553/93278162-2d119880-f7c4-11ea-98fa-3e812211b0c1.png)

**Comment by Sarjuuk** [comment]
the small map images appear to be cut off at the bottom.
 .. the heck?

**Comment by wodim** [comment]
Compare:

https://github.com/Sarjuuk/aowow/blob/c92ab37de11ed409d95382cdffd5547f551574d2/static/js/global.js#L18895

To:

https://github.com/Sarjuuk/aowow/blob/c92ab37de11ed409d95382cdffd5547f551574d2/setup/tools/filegen/complexImg.func.php#L356

btw what a clusterfuck that file is...

**Comment by Sarjuuk** [comment]
hey, it can't be that bad. You found the correct spot. :+1: 

fixed in 12c5f6f468af5a9169adde1dff1ac0cff18cc027
