### ISSUE TITLE
Spell doesn't link back to NPC who uses it

### ISSUE THREAD

**Issue by wodim** [Sarjuuk/aowow#224]
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=25085 should link to https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=2590

**Comment by Sarjuuk** [comment]
fixed in 178c13ec720584e6385e88b27ff0436dc94809d6

**Comment by wodim** [comment]
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=3238#used-by-npc should link to https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=1535

**Comment by wodim** [comment]
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=38557#used-by-npc should link to https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=23589.

Please reopen
