### ISSUE TITLE
"Move displayed spawn point" feature

### ISSUE THREAD

**Issue by wodim** [Sarjuuk/aowow#225]
What does it do? For example this NPC has it (you can move it to Azshara) but it does not seem to do anything.

https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=16015

The rest of NPCs have it but it only shows one zone (shouldn't that menu be completely hidden then?)

**Comment by wodim** [comment]
Talking about:

![image](https://user-images.githubusercontent.com/1001553/93724473-b1d72a80-fba7-11ea-86c5-2253e0f87df8.png)

![image](https://user-images.githubusercontent.com/1001553/93724475-b69bde80-fba7-11ea-9656-7b812e0b03df.png)

**Comment by Sarjuuk** [comment]
Its to resolve spawn points erroneously displayed in another, overlapping area or floor. Check Karazhan, thats 17 overlapping floors of nonsense. 

But there seems to be a rights mismatch between display and execution somewhere.

**Comment by wodim** [comment]
I suspected that. But I think a rewording would benefit the feature.

"Click to see this spawn point from another area" / "View from..."

**Comment by Sarjuuk** [comment]
The ajax returns 1 (success), so its not a user access mismatch. The error has to occur somewhere in here. Probably on the final query.:
https://github.com/Sarjuuk/aowow/blob/15fb7b8711e1de2be7963779c6b9e22131d58ae0/includes/ajaxHandler/admin.class.php#L415-L462
But that is for jackpoz to debug, as it works for me and i can only guess.
