### ISSUE TITLE
Sunken Temple appears on lists as "undefined"

### ISSUE THREAD

**Issue by wodim** [Sarjuuk/aowow#227]
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?zone=1417

![image](https://user-images.githubusercontent.com/1001553/93942461-baa73800-fd30-11ea-932f-e7a7750b9cf3.png)

Also on items:

https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=10454

**Comment by Sarjuuk** [comment]
probably still using the open world area id for sunken temple.

**Comment by wodim** [comment]
There are other zones that are undefined. Champion's Hall: https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?zone=2918

**Comment by wodim** [comment]
The Great Sea: https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?zone=207

**Comment by jackpoz** [comment]
I re-run ```Calculate.Creature.Zone.Area.Data``` and aowow sql, undefined seems to have disappeared in all the links mentioned above

**Comment by jackpoz** [comment]
now that I re-run the aowow sql setup, this issue appeared again (and should be re-opened)

**Comment by jackpoz** [comment]
@Sarjuuk if I check https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?zone=1417 I see the zone is Sunken Temple and has id 1417.
If I click on the first mob https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=5722 and check in world.creature is has zoneId and areaId 1477 (notice it's 1477, not 1417).
https://github.com/Sarjuuk/aowow/blob/c65bd88867cb37ca3bb652dd58522270689096b8/static/js/locale_enus.js#L2037 shows 1477 for Sunken Temple , while https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?zone=1477 shows The Temple of Atal'Hakka .

Is there a typo in the static js files ?

**Comment by Sarjuuk** [comment]
```MariaDB [sarjuuk_aowow]> select * from dbc_areatable where id in (1477, 1417);
+------+-------+-----------+-------+---------------+-----------+----------------+---------------------------+-------------------------+----------------------------+-----------+--------------------------+-------------------+------------------+
| id   | mapId | areaTable | flags | soundAmbience | zoneMusic | zoneIntroMusic| name_loc0                 | name_loc2               | name_loc3   | name_loc4 | name_loc6                | name_loc8         | factionGroupMask |
+------+-------+-----------+-------+---------------+-----------+----------------+---------------------------+-------------------------+----------------------------+-----------+--------------------------+-------------------+------------------+
| 1417 |   109 |         0 |     0 |             0 |         0 |              0| Sunken Temple             | Temple englouti         | Versunkener Tempel
   | ?????     | Templo Sumergido         | ?????????? ????   |                0 |
| 1477 |   109 |         0 |     0 |            33 |         3 |              0| The Temple of Atal'Hakkar | Le temple d'Atal'Hakkar | Der Tempel von Atal'Hakkar | ??????    | El Templo de Atal'Hakkar | ???? ????'??????? |                0 |
+------+-------+-----------+-------+---------------+-----------+----------------
+---------------------------+-------------------------+----------------------------+-----------+--------------------------+-------------------+------------------+
2 rows in set (0.025 sec)```
its a zone on the same instance map and it has me weirded out since day one.

**Comment by jackpoz** [comment]
well https://github.com/Sarjuuk/aowow/blob/c65bd88867cb37ca3bb652dd58522270689096b8/static/js/global.js#L8528 is the one returning "undefined", maybe better to keep the zone id if the name is not found in the js.

in addition to that it might be good to refresh the list of zones as there are quite a few missing

**Comment by jackpoz** [comment]
I opened a PR at https://github.com/TrinityCore/aowow/pull/41 (maybe I should I opened it on this repo but I noticed too late).

I applied it on tcubuntu, you can see the result by clearing your browser cache and visiting these urls:
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?zone=1417
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=10454
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?zone=2918
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?zone=207

![image](https://user-images.githubusercontent.com/1153754/103423421-b6e44680-4ba6-11eb-84dd-5b7bc79178bf.png)
