### ISSUE TITLE
Containers with multiple items with quest requirements are shown incorrectly

### ISSUE THREAD

**Issue by wodim** [Sarjuuk/aowow#228]
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?object=153123

![image](https://user-images.githubusercontent.com/1001553/93942984-e119a300-fd31-11ea-81cb-07e9af1d5d3b.png)

**Comment by Sarjuuk** [comment]
lol, neat one.
there is always that one edge case...

**Comment by Sarjuuk** [comment]
fixed in 003ac1c931726ef01939ae70734e68f9f61002eb
