### ISSUE TITLE
"null" drop category

### ISSUE THREAD

**Issue by wodim** [Sarjuuk/aowow#229]
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=28234

"One or more errors occured, while generating this page.
E_NOTICE - Undefined offset: 0 @ /var/www/tcubuntu.northeurope.cloudapp.azure.com/html/aowow/pages/npc.php:625"

![image](https://user-images.githubusercontent.com/1001553/94168229-51850900-fe85-11ea-8e2d-ef43f4a2bcdb.png)

**Comment by Sarjuuk** [comment]
fixed in 2e9b503c59ca21c51c59b5fe5dd984e68bc43e9e
