### ISSUE TITLE
Incorrect wording of spell links

### ISSUE THREAD

**Issue by wodim** [Sarjuuk/aowow#231]
The word "When", at least in the second column, should not be there.

https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=20066

![image](https://user-images.githubusercontent.com/1001553/94211068-57500e00-fec8-11ea-87db-35831e28da21.png)

**Comment by Sarjuuk** [comment]
adjusted in df1f29c986b09a79e3b1594331b34e838ee578fb
