### ISSUE TITLE
Faction not show for object

### ISSUE THREAD

**Issue by wodim** [Sarjuuk/aowow#232]
Object: https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?object=201385

Is member of faction: https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?faction=960#objects

But this is not shown in the object's page.

**Comment by Sarjuuk** [comment]
added in 59fb6c1bc9ea228f3e0d39d04b9531ecfe8ed2b1

**Comment by wodim** [comment]
How often are these changes applied to the copy running at tcubuntu... etc?

**Comment by Sarjuuk** [comment]
i do not own or have access to the tcubuntu instance.

i believe it's @jackpoz

**Comment by jackpoz** [comment]
Updated
