### ISSUE TITLE
Unknown SmartAI action

### ISSUE THREAD

**Issue by wodim** [Sarjuuk/aowow#234]
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=27202 contains an unknown SmartAI action, #134. The parameter seems to reference https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=48655. Wondering if it is a bug in the database or in aowow.

**Comment by Jinnaix** [comment]
Its missing definitions/translations in aowow for smart script actions 131 - 139:

https://github.com/TrinityCore/TrinityCore/blob/0152878de5c1563cbe8d13fbf4f85839d741aabf/src/server/game/AI/SmartScripts/SmartScriptMgr.h#L590-L598

**Comment by Sarjuuk** [comment]
oh, when where those added?

**Comment by Jinnaix** [comment]
Over the last 3 years, but used rarely

![image](https://user-images.githubusercontent.com/37972361/94973308-9d7e2080-050b-11eb-8abe-bc162ee7977d.png)

**Comment by Sarjuuk** [comment]
note to self - commits over the last 3+ years to have a look at:
- [ ] 50be697e1f3a56760e593b15bfbd576f4d370dcf
- [ ] 619a5534c5f6ce5e736b22e645f7bac72eba9b16
- [ ] 5339d1d3b835fcc8f635d34457ceb6e653e70a1c
- [ ] 5ad38c31b0ed633555f281318684e57ea5d6dd73
- [ ] 9e58ef6940c78d92f1553cf7ab75e87a6e2cf112
- [ ] cbed1039c47f0e3487cea555bb8552a4e6445f5a
- [ ] 4e55e797532ca404ce0e1e603762c17ead760f45
- [ ] 02fca032e1d497be08681de0bfd7bca979f0dafd
- [ ] 152ea6011694518017a47dc23fdbb7175bfa5481
- [ ] 0850b5ff39b187d8a1adb032dfd7900d4474cfaf
- [ ] 0df3cb5bcc8097070b1f215032d3914d6a577f01
- [ ] 6f31784979569c1a9ae3ee3f70416f5e11d3e7f0
- [ ] 691c67f0be09095a34421043baf245fdf28e5d04
- [ ] 63aa5d1e3559f580551544b71fb7dd63d6b54b60
- [ ] 443a425c4c35c1a3ee4594598208032e953dc287
- [ ] dab66cb8d0e94433f5e63b42fca3105a1a3af2d4
- [ ] 5cfce94619cc02cc04bb25ccdd2e1b98e53d9160
- [ ] c65ba35269a68c94c3e423f78fa1585f9d89dd04
- [ ] 37995ade2991ed27845728eb6a6dd95f3a490849
- [ ] 85a7d5ce9ac68b30da2277cc91d4b70358f1880d
- [ ] d365dd915715d4608ae69fa54f094ab65f02e984
- [ ] 264d4e1d30debcf6feacee3d29982875672a7bbe
- [ ] ca4f1e334a98cbd810168b24714c46201079fc5a
- [ ] b0ae5fadd19fd172ec5154cde4f4fd14aa20ff88
- [ ] 482328bddf1c5fcd367268525d2f904793239bc9
- [ ] 891bca934e1522fe33b00e27eef5d4f07bb83fa8
- [ ] 2d948d33666fbd6f82145c4629483753b7780bb5
- [ ] 7634a57f64a38e1151d648eeacae8480c83d19df
- [ ] 46368188ce508359d839d8e48b65bf1df3ae3ac6
- [ ] 50ed1bb5b3d30936b844659b869fe66a0da7e04f
- [ ] ca25e8d0199730c0976ebc37317e9407aceccc34

**Comment by Sarjuuk** [comment]
accumulated changes implemented in e2fe765980718ffebfea09e57a271f75a2044b29
