### ISSUE TITLE
reference listed on disenchant list of item

### ISSUE THREAD

**Issue by Aokromes** [Sarjuuk/aowow#235]
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=31051

**Comment by Sarjuuk** [comment]
working as intended? 
can disenchant into one or two crystals, weighed 1:2 towards two?

**Comment by Aokromes** [comment]
dunno it looks strange to me xd

https://i.imgur.com/hqyZs6Q.png

**Comment by Sarjuuk** [comment]
its displayed verbose since https://tcubuntu.northeurope.cloudapp.azure.com/aowow/ is supposed to be used as dev tool

not a bug
