### ISSUE TITLE
Mobs only visible while dead

### ISSUE THREAD

**Issue by wodim** [Sarjuuk/aowow#238]
Not sure if this can be done (depending on where it is stored I guess) but would it be possible to show somewhere in NPC pages when a mob is only visible whilst you are dead? For example https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=6491 or https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=10988

**Comment by Sarjuuk** [comment]
there are multiple sources of this. 

Spirit Healers and Spirit Guides are flagged as such and thus invisible `npcflag & 0xC000`
there are Spell Auras that cause this effect. those will be hard to catalogue.
and the Kodo has `type_flags & 0x2 CREATURE_TYPEFLAGS_GHOST` set.

eh .. onto the eventually todo pile it goes

**Comment by wodim** [comment]
Re: auras, for example: https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=10848 used by https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=9299 (not shown because of #224)

**Comment by wodim** [comment]
Spells such as spell=33900 are a visual effect and do not have anything to do with whether the NPC appears only when you are dead. 

Is there any addon that shows the ID of auras and spells in-game?

**Comment by Sarjuuk** [comment]
hm, it was really just the type_flags
added in a4bcb33ba4b27bbe8f52c0ab68b289e6ad5b7097
