### ISSUE TITLE
DB: Store structure.sql unzipped

### ISSUE THREAD

**Issue by Carbenium** [Sarjuuk/aowow#24]
Rev. 92b180ca053c7f165cf41540a5a5f1b63911fda7

As the title says. This would allow to properly diff the file. Size shouldn't be a problem (330 KB).

**Comment by Sarjuuk** [comment]
sure, why not.

it just used to be unwieldy sql-dumps :]

**Comment by Sarjuuk** [comment]
added in c779e9139a2c5e3fb68a2fc8333821c400f88a2b
