### ISSUE TITLE
[Question] How to select all disabled quests?

### ISSUE THREAD

**Issue by BarbzYHOOL** [Sarjuuk/aowow#240]
Hey, just a quick question for devs here, 

I found this quest 13317.
Example: https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=13317

This "Disabled" probably automatically because it's not obtainable by players. Can you guys give me the query to get all the similar quests so I can erase them from the world DB? (and I will propose the query to the public too)

**Comment by Jinnaix** [comment]
Not at my computer so I can't fact check my following guess but I think this attribute comes from the disables table from world database.

**Comment by Sarjuuk** [comment]
there is also a QuestFlag & 0x4000 (unavailable) which is handled similarily.
disabled is a straight up entry in disables, yes
