### ISSUE TITLE
In search, zone drops show a wrong item source

### ISSUE THREAD

**Issue by wodim** [Sarjuuk/aowow#241]
Example: https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?search=shredder+operating+manual+page single out https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=3664 as a source--why? In fact this NPC has a pretty poor chance of dropping this item when compared to other NPCs.

Another example: https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?search=Green+Hills+of+Stranglethorn+Page

**Comment by wodim** [comment]
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?search=cutthroat

When you click on any of the items dropped by "Nightbane Dark Runner" you see:

https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=15132

According to that page, the item does not drop from "Nightbane Dark Runner", but if you go to that NPCs page you can see it really drops from it:

https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=205#drops

**Comment by wodim** [comment]
Another example:

https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?items&filter=na=blackskull

Singles out [Mosh'Ogg Shaman](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=679) as a source, but that NPC does not have a particularly high chance of dropping it.

**Comment by Sarjuuk** [comment]
can't reproduce anymore, probably gone.
