### ISSUE TITLE
Item buyable is said "not available" but it is

### ISSUE THREAD

**Issue by BarbzYHOOL** [Sarjuuk/aowow#243]
https://wotlk.evowow.com/?item=43792
This is sold by npc "Paldesse" and this npc is spawned in game normally (found it in dalaran)
https://wotlk.evowow.com/?npc=28995

I don't know why it says unavailable

**Comment by wodim** [comment]
Because you got the wrong one. The item that is sold is https://wotlk.evowow.com/?item=39523 (different ID)

**Comment by BarbzYHOOL** [comment]
i have a query to select all of these shitty items and mark them as duplicate (on world db) if wanted
