### ISSUE TITLE
Trap objects show only one object that triggers them

### ISSUE THREAD

**Issue by wodim** [Sarjuuk/aowow#244]
The trap https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?object=2066 should have a list of objects that have it, but it only links back to a single one in the quick facts section.

For example,  https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?object=24727 (and I guess most bonfires) has that trap also.

**Comment by Sarjuuk** [comment]
true
though it will have to be displayed in a different way. there are over 600 GOs triggering fire damage

**Comment by wodim** [comment]
I think computers in 2020 can handle tables of 600 rows just fine.

**Comment by Sarjuuk** [comment]
moved from infobox to listview tabs in d4a0abf704368ae59a7906d123bf2df3549496d6
