### ISSUE TITLE
Array to string conversion in spell.php:2264

### ISSUE THREAD

**Issue by wodim** [Sarjuuk/aowow#248]
This page causes dozens of these errors: https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=34427

    E_NOTICE - Array to string conversion @ /var/www/tcubuntu.northeurope.cloudapp.azure.com/html/aowow/pages/spell.php:2264

**Comment by Sarjuuk** [comment]
fixed in cac57f5cd8e543e77cd49232653b5fd2dec9e54b
