### ISSUE TITLE
Wrong enchantment amounts

### ISSUE THREAD

**Issue by wodim** [Sarjuuk/aowow#251]
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=45994

All the enchantments appear as +0

**Comment by wodim** [comment]
I _suspect_ this may be a bug in TDB, in which case please close.

**Comment by Sarjuuk** [comment]
the amount is calculated from the item level, so it *should* work, since the rest is dbc data.

**Comment by Sarjuuk** [comment]
works fine for me. 
maybe table `aowow_itemrandomproppoints` is empty and causes this function to return 0?
https://github.com/Sarjuuk/aowow/blob/master/includes/types/item.class.php#L1189-L1259

**Comment by jackpoz** [comment]
![image](https://user-images.githubusercontent.com/1153754/103228461-323cc280-4931-11eb-9d12-1ea9822157b1.png)

**Comment by Sarjuuk** [comment]
lets try debugging them with tooltips (which are also affected)
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=45994&power&rand=-93 

the random enchantments are added to tooltips here:
https://github.com/TrinityCore/aowow/blob/master/includes/types/item.class.php#L515
either `$this->enhanceR['allocationPct'.$i]` or `$this->generateEnchSuffixFactor()` will return `0` and need to be checked further.

**Comment by Sarjuuk** [comment]
nevermind
c65bd88867cb37ca3bb652dd58522270689096b8

**Comment by jackpoz** [comment]
updated on tcubuntu, this is what it shows now:
![image](https://user-images.githubusercontent.com/1153754/103300297-db052380-49fe-11eb-9777-ddb33ad4f981.png)
