### ISSUE TITLE
"Requires Inscription/Jewelcrafting" on herbs and ores

### ISSUE THREAD

**Issue by wodim** [Sarjuuk/aowow#254]
Herbs and ores show "Requires Inscription/Jewelcrafting" in their tooltips, which is inaccurate since they can be used for purposes other than milling/prospecting

https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=22792

https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=36910

**Comment by Sarjuuk** [comment]
Smelting uses a separate set of spells with individual skill requirements that are not linked to the ore as reagent. Same for herbs and alchemy.

I'll keep the requirement in the tooltip for the time being
