### ISSUE TITLE
Enchantment pages have tooltips on effects that do not work

### ISSUE THREAD

**Issue by wodim** [Sarjuuk/aowow#255]
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?enchantment=3721

"Spell power" and "Stamina" look like they have tooltips but they do not.

**Comment by Sarjuuk** [comment]
hmm, erroneously set the css class for tip?

**Comment by Sarjuuk** [comment]
removed in https://github.com/Sarjuuk/aowow/commit/baf47433dd5aa0ec6c9d8eb3563e6db891d16a84
