### ISSUE TITLE
Order zones in which an NPC can be found by amount of spawn points (quests)

### ISSUE THREAD

**Issue by wodim** [Sarjuuk/aowow#256]
Like #174 but for quests:

https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=5101

https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=1933

The locations listed in the quest page should be ordered in the same way than in the NPC page.

**Comment by Sarjuuk** [comment]
red rocket site™ orders those by zone id, though i agree sorting them like npcs is a nice QOL improvement. 

will need to check if sorting the zones by nodes is not too convoluted. and quest pickup/dropoff either last or first

**Comment by Sarjuuk** [comment]
added in bd5200de85ba918bbe5f37cfb9225effaeb29498
