### ISSUE TITLE
Exception - syntax error, unexpected '<', expecting variable (T_VARIABLE) or '{' or '$'

### ISSUE THREAD

**Issue by Helias** [Sarjuuk/aowow#257]
Hello, I am trying to install AoWoW for AzerothCore emulator, I hope I will find the time to upload all the `static files` somewhere to avoid this part of installation for other users. 
```
15:27:59  [OK]    created file datasets/enus/talents-4

 267*3*$<mult> 
Exception - syntax error, unexpected '<', expecting variable (T_VARIABLE) or '{' or '$'
   /var/www/html/aowow/includes/types/spell.class.php(1020) : eval()'d code(1)
#0 /var/www/html/aowow/includes/types/spell.class.php(1442): SpellList->resolveEvaluation()
#1 /var/www/html/aowow/includes/types/spell.class.php(1682): SpellList->resolveFormulaString()
#2 /var/www/html/aowow/includes/types/spell.class.php(1589): SpellList->handleFormulas()
#3 /var/www/html/aowow/setup/tools/filegen/talentCalc.func.php(104): SpellList->parseText()
#4 /var/www/html/aowow/setup/tools/filegen/talentCalc.func.php(188): {closure}()
#5 /var/www/html/aowow/setup/tools/fileGen.class.php(254): talentCalc()
#6 /var/www/html/aowow/setup/tools/clisetup/firstrun.func.php(274): FileGen::generate()
#7 /var/www/html/aowow/setup/setup.php(61): firstrun()
#8 /var/www/html/aowow/aowow(10): require('/var/www/html/a...')
#9 {main}
```
the line mentioned (1020) is: `return eval('return '.$formula.';');`

the content of `$formula` is `267*3*$<mult>`.

I don't really understand what I did wrong, I used [this bash script](https://gist.github.com/Helias/d9bd7708e28e9e8dcd5274bd2f3b68bc) to extract all the data of my enUS client.

**Comment by Sarjuuk** [comment]
`$<xxx>` are references to a SpellDescriptionVariable from the dbc with the same name, linked with the second to last (?) column from spell.dbc

something broke there, check it.

also i'd recommend unpacking mpqs with the -f (full path) -c (forced lowercase) options

**Comment by Helias** [comment]
Thank you a lot, I will try, I've just updated the bash script :wink:

**Comment by Helias** [comment]
Solved, the problem was the order of the MPQ extraction that generates wrong DBCs
