### ISSUE TITLE
Doubts about cases

### ISSUE THREAD

**Issue by Helias** [Sarjuuk/aowow#258]
When I extract using MPQExtractor all the data from the MPQ files I get some files like `Dungeon` and `DUNGEON` but AoWoW will consider only one of these, what should I do exactly? merge them and use the UPPERCASE? is there a command that can easily improve this?

MPQExtractor has the parameter `-c` to convert all files in lowercase, can be a good solution to use only lowercase names?

**Comment by Sarjuuk** [comment]
yes, use `-c`

and either discard and reextract the old files or merge the folders and prioritize files from patch-x.mpq over the base archives

**Comment by Helias** [comment]
ok, but if I use -c it will be sure that AoWoW will not require the files with UPPERCASE? I am in a UNIX system so it is case-sensitive.

**Comment by Sarjuuk** [comment]
ye, its fine. mpq file contents are case insensitive.

**Comment by Helias** [comment]
ok, thanks
