### ISSUE TITLE
MPQExtractor included as submodule will not compile

### ISSUE THREAD

**Issue by jududdar** [Sarjuuk/aowow#26]
Greetings,

Doing the install on a Linux box finally.  When I pulled the submodule repo for the MPQExtractor from iamcal, I can't ever get it to compile.  I did some troubleshooting for a while, then went upstream from what it was forked from:  https://github.com/Kanma/MPQExtractor - that one actually did compile properly.  Using Debian 8 x86_64

I am still apparently too dense to use the tool, but it does compile and appears to give proper output - I'm just feeding it incorrectly!  I'll keep plugging away at that one.

**Comment by Sarjuuk** [comment]
right, also got an ``error: âtransformâ was not declared in this scope`` in main.cpp

it is caused by a missing include at the top of the file
``#include <algorithm>``

the works pretty straight forward, if you are sticking to 3.3.5
``./MPQExtractor -h`` also shows a couple of exaples

**Comment by jududdar** [comment]
I can get files out of it, but it's the patch level thing I am not sure about.  For example, I have these files in my Data/enGB folder (that have the relevant files anyhow):

expansion-locale-enGB.MPQ
lichking-locale-enGB.MPQ
locale-enGB.MPQ
patch-enGB.MPQ
patch-enGB-2.MPQ
patch-enGB-3.MPQ

Then I run the command like so: `./MPQExtractor -e "DBFilesClient\*.*" -f -o out WorldofWarcraft/Data/enGB/locale-enGB.MPQ`

I guess my real question is, do I do this command for each MPQ in alpha/numeric order and overwrite the previous files, or is there something I'm missing? I've went through the entire setup with the MPQ extracts I did when I was messing around with Windows, but the outcome was the same (no quests, only dungeons that showed were lich king, no classic/BC).  It's almost got to be related to me not knowing what I'm doing with the extractor.

**Comment by Sarjuuk** [comment]
yes, just replace the previously extracted files. The command to apply patches is for cata and later

**Comment by jududdar** [comment]
Okay thanks, I'll give it a go.  In remembering what I did with the Windows extractor, I think I did this exact thing.  Looking at what I have, though, I know I forgot to do GlobalStrings.lua so who knows what else I may have omitted in trying to do this with clicks instead of command line (where I can at least verify what the last thing I did was)!

**Comment by Sarjuuk** [comment]
Don't worry, the GlobalStrings.lua was added afterwards.

**Comment by Sarjuuk** [comment]
references MPQExtractor updated some time ago, forgot to close :)
