### ISSUE TITLE
No locations for many NPCs

### ISSUE THREAD

**Issue by wodim** [Sarjuuk/aowow#260]
Seems that lots of NPCs are broken right now and show no location at all:

https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=39501#sold-by-npc

Is this a problem of the tcubuntu instance? If so, who needs to be told so it can be fixed?

**Comment by jackpoz** [comment]
Set up aowow locally and compare the 2. If you have the same issue, then it's an aowow issue

**Comment by jackpoz** [comment]
I guess aowow stopped rebulding halfway through:
![image](https://user-images.githubusercontent.com/1153754/103379720-e3d12480-4ae6-11eb-9475-feb21a62b062.png)

**Comment by jackpoz** [comment]
there, re-run aowow sql setup and how ti shows correctly
