### ISSUE TITLE
Spell does not appear on search

### ISSUE THREAD

**Issue by wodim** [Sarjuuk/aowow#261]
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=61332 does not appear in https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?search=dalaran+brilliance

**Comment by wodim** [comment]
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=48076 does not appear in https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?search=holy+nova

**Comment by wodim** [comment]
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=12999 does not appear in https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?search=World+Invisible+Trigger

**Comment by Jinnaix** [comment]
As far as i know, this is intended. 
When i am logged into aowow as admin, i can search for your examples.
A simple user cant, because they have special hidden flags:

![image](https://user-images.githubusercontent.com/37972361/105357611-5a000d00-5bf5-11eb-96e4-8a61c4a98328.png)

**Comment by wodim** [comment]
Seems like a fool's errand—most spells and a big chunk of NPCs should be flagged as "hidden", but they are not. Why leave such a half-assed system up?

**Comment by Jinnaix** [comment]
Well, better flag this stuff as hidden then - afterall, aowow is a user database. Triggers, serverside spells and stuff like that shouldnt be included in searches for users.

**Comment by Sarjuuk** [comment]
Jinnaix got it. 

though the tcubuntu instance is special and treats all users as devs. There seems to be some mishap when applying it to searches here. 

@jackpoz 
you'll probably need to amend https://github.com/Sarjuuk/aowow/blob/c65bd88867cb37ca3bb652dd58522270689096b8/pages/search.php#L359 with the user groups you default to in https://github.com/Sarjuuk/aowow/blob/c65bd88867cb37ca3bb652dd58522270689096b8/includes/user.class.php#L12

**Comment by jackpoz** [comment]
actually that's not the case anymore. I'm currently running https://github.com/TrinityCore/aowow/pull/41 without any other custom change and with auth db authentication enabled, so accounts created at https://tcubuntu.northeurope.cloudapp.azure.com/ can login.

See here how the same url gives different results (check the Abilities tab, it shows 18 on the left, 9 on the right) https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?search=holy+nova
![image](https://user-images.githubusercontent.com/1153754/108109859-c524ee00-7092-11eb-9733-4eb4aab83a32.png)

**Comment by Sarjuuk** [comment]
alright, not a bug then.
