### ISSUE TITLE
Show which scripts summon an NPC

### ISSUE THREAD

**Issue by wodim** [Sarjuuk/aowow#262]
For example, https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=3569 is summoned by the sai script attached to https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=2080#sai-actionlist-208002. At least a link back to the NPC would be nice.

**Comment by wodim** [comment]
Also objects: https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?object=149410 summoned by https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=8479#sai-actionlist-847900

**Comment by Sarjuuk** [comment]
added in aa82655845ce5aac0cc68f71af89dd7cc9491072 .. i think
