### ISSUE TITLE
URL to icon with trailing space is broken

### ISSUE THREAD

**Issue by wodim** [Sarjuuk/aowow#263]
Seems like achievement_leader_lorthemar_theron has a trailing space so some links to it are broken, for example this image:

https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?achievement=613

Or this small one here:

https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?achievement=618

Here it works correctly:

https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?icon=749

**Comment by wodim** [comment]
Additionally for some reason titles of pages have their first letters converted to uppercase (this one says Achievement_... instead of achievement_...)

**Comment by Sarjuuk** [comment]
fixed in 0c1b73d6ac56fd23eb8499c21199ecab4717cd20
