### ISSUE TITLE
No "rank" text in Everlasting Affliction

### ISSUE THREAD

**Issue by wodim** [Sarjuuk/aowow#264]
The Everlasting Affliction family of talents do not show a "Rank x" text, instead they show the number directly:

![image](https://user-images.githubusercontent.com/1001553/103691883-3d2dcd80-4f97-11eb-9a14-a611463e3df0.png)

https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=47201

But I'm not sure if it's a bug in the dbc files.

**Comment by Sarjuuk** [comment]
its a dbc data "bug"
