### ISSUE TITLE
Missing parentheses on tooltip  formulas 

### ISSUE THREAD

**Issue by wodim** [Sarjuuk/aowow#265]
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=49001

`Stings the target, causing RAP*0.2+242*15/3 Nature damage over 15 sec.`

Parentheses are missing, it should be: `(RAP*0.2+242)*15/3`

**Comment by Sarjuuk** [comment]
dbc data for spell id: 49001
```Stings the target, causing ${$RAP*0.2+$m1*$d/3} Nature damage over $d.  Only one Sting per Hunter can be active on any one target.```

TC handling this differently then the dbc data suggests?

**Comment by wodim** [comment]
Seems a DBC bug then. --Sent from Yandex.Mail for mobile15.02.2021, 16:13, "Sarjuuk" <notifications@github.com>:
dbc data for spell id: 49001
Stings the target, causing ${$RAP*0.2+$m1*$d/3} Nature damage over $d.  Only one Sting per Hunter can be active on any one target.
TC handling this differently then the dbc data suggests?
