### ISSUE TITLE
How to update aowow

### ISSUE THREAD

**Issue by ex1dreamer** [Sarjuuk/aowow#266]
Apologize for asking, but couldn't find such info in closed issues. When I've dowloaded new version of aowow-master, how I suppose to update it on the web server. Should I run again "php aowow --firstrun" and do all config steps?

**Comment by Helias** [comment]
I think that at least you need to run `php aowow --sql` to extract again the data with the lasted core DB and AoWoW versions, but I would wait for @Sarjuuk or @jackpoz to be sure.

**Comment by jackpoz** [comment]
Every time you get a new version of aowow, you should first run
```
php aowow --update
```
which states in the help
>apply new sql updates fetched from github

If you apply TrinityCore updates (or whatever other wow project you are using), you should run
```
php aowow --sql
```
to update aowow with latest world database content.

**Comment by ex1dreamer** [comment]
many thanks, it's very helpful. 
During the update i do see lots of warnings such as 
"[WARN]  tried to default GUID 47714 to instanced area by mapId, but returned empty [M:450]"
any  ideas how to fix them?

**Comment by Sarjuuk** [comment]
what jackpoz said. 

Warnings are usually fine.
The spawn point generation relies on dbc data that is only present for zones that are mapped in game. (zone dimensions) A lot of instanced areas don't have those, so this warning gets spammed a lot.
