### ISSUE TITLE
Do not show maps for zones that do not have one

### ISSUE THREAD

**Issue by wodim** [Sarjuuk/aowow#267]
In the [maps feature](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?maps), all tbc and classic instances appear, but they do not have maps and they show black. They probably should not be in that dropdown.

**Comment by opiums9** [comment]
I am facing the same problem... You can try to add images, but I don't think that this will be a solution to the problem

**Comment by Sarjuuk** [comment]
true.

should be commented from 
https://github.com/Sarjuuk/aowow/blob/c0a1e393b06f78eb9a82f98614741db488bea31d/static/js/maps.js#L7-L27

**Comment by Sarjuuk** [comment]
changed in e8105546954cd84f535ab330a905f80ae234289b
