### ISSUE TITLE
Ordering drop chances by % works incorrectly

### ISSUE THREAD

**Issue by wodim** [Sarjuuk/aowow#268]
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=2592#pickpocketed-from:0-8+1

Some of these are just wrong:

![image](https://user-images.githubusercontent.com/1001553/104140507-e0c11880-53b1-11eb-9422-5c641b8861de.png)

**Comment by Sarjuuk** [comment]
note to self

Listview.extraCol.percent.sortFunc should use the same rounding logic for display and sorting.

0.29 ≙ 0.3
0.34 ≙ 0.3

**Comment by Sarjuuk** [comment]
fixed in d6ca3d7
