### ISSUE TITLE
Show skill level colours for veins and herbs

### ISSUE THREAD

**Issue by wodim** [Sarjuuk/aowow#269]
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?object=1732

https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?object=1618

Veins and herbs should show the levels at which they become orange/yellow/green/grey to mine/pick up.

**Comment by Sarjuuk** [comment]
added inc456ade870ff7511b0cbf3de3a03a82fac760f24
