### ISSUE TITLE
Language selector dropdown redirects to the front page

### ISSUE THREAD

**Issue by wodim** [Sarjuuk/aowow#270]
https://db.rising-gods.de/?npc=6491

**Comment by Jinnaix** [comment]
Works for me,, im not redirected.

**Comment by wodim** [comment]
This is what I see:

![image](https://user-images.githubusercontent.com/1001553/104719861-29b7fa80-572d-11eb-9368-c4c60f1d021c.png)

**Comment by wodim** [comment]
Ah now I understand. It probably relies on the referer header, which my browser strips for privacy reasons. That's... odd.

**Comment by Sarjuuk** [comment]
yeah it uses referer data.
