### ISSUE TITLE
Why boss location in some dungeons is unknown?

### ISSUE THREAD

**Issue by BarbzYHOOL** [Sarjuuk/aowow#271]
Example:
?npc=11519 (ragefire)

?npc=6229

However, this one is fine:
?npc=39747 (ruby sanctum)

**Comment by Jinnaix** [comment]
Lack of data in dbc_worldmaparea, dbc_dungeonmap & the respective map images.
WotLK Dungeons and Raids have these data. TBC and Classic Raid&Dungeon Images and coordinates in dbc files have been added in cataclysm.

**Comment by Jinnaix** [comment]
I tried to import all this from cataclysm but the results are bad for spawns, pretty sure im doing something wrong:

![image](https://user-images.githubusercontent.com/37972361/105468288-1e1d8400-5c97-11eb-97ea-64a4cd5a4281.png)

**Comment by Sarjuuk** [comment]
Also some bosses may be spawned in via instance script. So their spawn point is not in DB.
(at least this used to be the case and probably still is)

But Jinnaix explanation is the usual case.
