### ISSUE TITLE
Linen cloth will be converted to a quest item if you transfer to horde

### ISSUE THREAD

**Issue by BarbzYHOOL** [Sarjuuk/aowow#274]
https://webdb.fusion-host.eu/?item=2589#dropped-by:0+2+1

Item: linen cloth
`This item will be converted to Warlord Goretooth's Command if you transfer to Horde.` 

Why??

**Comment by Jinnaix** [comment]
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=2589

Can't replicate.

**Comment by Sarjuuk** [comment]
Please check your database for an entry in player_factionchange_items for item 2589.
Thats the most likely source of the issue.

**Comment by Sarjuuk** [comment]
can not reproduce
