### ISSUE TITLE
Empty names

### ISSUE THREAD

**Issue by opiums9** [Sarjuuk/aowow#282]
Can anyone tell me where the itemsets data comes from from the database or files? My problem is that I finished building a site for two languages, but one of them is missing names, the screenshots are attached below...

ruru:
![image](https://user-images.githubusercontent.com/25082773/108230838-c11ccd00-7173-11eb-8e0f-6bdb58208201.png)
![image](https://user-images.githubusercontent.com/25082773/108230997-e7db0380-7173-11eb-8b29-447157272d76.png)

enus:
![image](https://user-images.githubusercontent.com/25082773/108231056-f6c1b600-7173-11eb-8913-a094b968d5fd.png)
![image](https://user-images.githubusercontent.com/25082773/108231100-017c4b00-7174-11eb-8b93-88f112cc6b9b.png)

**Comment by Sarjuuk** [comment]
Its from ItemSet.dbc

**Comment by opiums9** [comment]
Yes, but I can't find where the data comes from, from some database table or php file. I want to manually fix empty names

**Comment by opiums9** [comment]
This is in the tables of the database aowow_itemsets, thank's

**Comment by Sarjuuk** [comment]
order is:
ItemSet.dbc > (intermediate) table dbc_itemset > table aowow_itemsets
If i had to guess you build it for ruRU only first and tried to add enUS later. Then the temp table dbc_itemset would only contain data for ruRU. You'd need to drop dbc_itemset and regenerate itemsets `php aowow -sql=itemset`
