### ISSUE TITLE
Requirements to open doors are not shown in object pages

### ISSUE THREAD

**Issue by wodim** [Sarjuuk/aowow#287]
In the tooltip for this door you can see the lockpicking/blasting levels required to open it: https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?object=174626&power

But then the same information is nowhere to be found in the page for the object: https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?object=174626

**Comment by Sarjuuk** [comment]
unified in 01a9744ba7bcc3f0819601003a643f067866a1ac
