### ISSUE TITLE
Tooltip for "No equip cooldown" is shown as undefined

### ISSUE THREAD

**Issue by wodim** [Sarjuuk/aowow#296]
![image](https://user-images.githubusercontent.com/1001553/116943425-ddf57680-ac73-11eb-9208-6ba066da0e7e.png)

https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=45037

**Comment by Sarjuuk** [comment]
added in 41f415095aa23b3cfb1a1e34c8bc38d1374c3641
