### ISSUE TITLE
Profiler output limited to 300 characters only

### ISSUE THREAD

**Issue by ex1dreamer** [Sarjuuk/aowow#297]
The profiler output window shows 447 total characters matching, but  only 300 are available for browsing in "previous/next" navigation bar.Any particular reason for that ot numer of lines is configurable somewhere?

**Comment by ex1dreamer** [comment]
indeed, it's a site config
php aowow -siteconfig
change  AOWOW  SQL_LIMIT_DEFAULT                  [int]  300

**Comment by Sarjuuk** [comment]
All search results are capped at  SQL_LIMIT_DEFAULT, so you increased the result set for everything else too.

If you want to edit it only for the profiler you'll need to add a non-default limit as condition here:
https://github.com/Sarjuuk/aowow/blob/56e70e22bba81692670199c292c231ab0c113cdb/pages/profiles.php#L69

```php
$conditions[] = 500;
```
Or something like that.
