### ISSUE TITLE
profile:windows cannot find php error

### ISSUE THREAD

**Issue by qyh214** [Sarjuuk/aowow#300]
I put php.exe path to system variable.but Windows give error:
Windows cannot find 'php' ……  when use profile

**Comment by qyh214** [comment]
I think I have soloved and also should add this in readme.

windows

1. cd to webserver path,for example `cd D:\webserver\aowow`
2. `php prQueue --log=cache/profiling.log`

that's all

**Comment by qyh214** [comment]
I recommend that the queue be persistent and updated at any time, rather than being closed after the queue is empty

**Comment by jackpoz** [comment]
is this a windows error or a php error or a aowow error ?

**Comment by qyh214** [comment]
> is this a windows error or a php error or a aowow error ?

In fact, it's very difficult to say where it belongs!SAD!

Maybe this issue should be related to environment variables. (although I've defined in system  environment variables)I'll do the test again when I have time. 

Maybe this issue can be used as a note and updated in the future!

**Comment by qyh214** [comment]
Now I have set php.exe to system path in windows (and also in user path)
seems fine!
maybe this issue and how to fix can help some people.
