### ISSUE TITLE
search for custom items,npcs and etc

### ISSUE THREAD

**Issue by qyh214** [Sarjuuk/aowow#302]
In /?items you can see a lot of items and include custom items,but if you in search bar try search custom items, and you will give nothing.

**Comment by Helias** [comment]
Did you generate again the sql data using the setup tool? once you create the new items in item_template you need to re-generate the data to fill the aowow database

**Comment by qyh214** [comment]
> 
> 
> Did you generate again the sql data using the setup tool? once you create the new items in item_template you need to re-generate the data to fill the aowow database

yes!and also modify item.dbc then use setup tool

**Comment by Sarjuuk** [comment]
Sounds a bit like a cached search result, if the items show up when accessed directly.
Does it work when you disable caching?

**Comment by qyh214** [comment]
I have test again and here is note maybe this is not an issue.
for example custom item has name_loc0/name_loc2 ,but name_loc4 is empty.
and your site set language is zhcn(loc4)
search this item will give empty

**Comment by Sarjuuk** [comment]
Yes, that's correct. 

Another thing for the FAQ, I guess.
