### ISSUE TITLE
[CLI]Setup/DB The Setup select the aowow Database Instead of world

### ISSUE THREAD

**Issue by LordMagnum** [Sarjuuk/aowow#303]
Hi,

> Array
> (
>     [code] => 1146
>     [message] => Table '**aowow.spell_enchant_proc_data**' doesn't exist
>     [query] => SELECT EnchantID AS ARRAY_KEY, Chance AS procChance, ProcsPerMinute AS ppmRate FROM spell_enchant_proc_data
>     [context] => E:\xampp\htdocs\aowow\setup\tools\sqlgen\itemenchantment.func.php line 29
> )

https://github.com/Sarjuuk/aowow/blob/56e70e22bba81692670199c292c231ab0c113cdb/setup/tools/sqlgen/itemenchantment.func.php#L29

fbc5d43aabb10847843462090b8e0fe9684daeb9 ?

Best regards.

**Comment by Helias** [comment]
Did you configured it correctly...?

check `config/config.php`, be sure that the variable `$AoWoWconf['world']` point to your world database

**Comment by LordMagnum** [comment]
Jup is checked previously
when I start Setup again, then will it work, but why the error ?! I' dont know.. nothing changed only viewed.
![image](https://user-images.githubusercontent.com/45822783/119224307-16af9f80-bafe-11eb-8a83-1e96ef32c4b2.png)

Jes what you now see is the next Error, I missing Directoires in static folder. automatic create ??

**Comment by qyh214** [comment]
this issue I also met the same.but my php is 8.0 then I use php 7.1 and runs well,(you should delete all dbc_* and clean aowow_ database then again use setup tool)

**Comment by LordMagnum** [comment]
Setup is complete, but with a few tricks and problems. I'll try again with an empty database and clean source code.
The site is doing pretty well so far.
