### ISSUE TITLE
Profiler:  Characters or guild names that are not in English cannot be displayed

### ISSUE THREAD

**Issue by qyh214** [Sarjuuk/aowow#313]
**Describe the bug and how to reproduce it**
Profiler:  Characters or guild names that are not in English cannot be displayed

no errors in aowow_errors,

and cn server is shown in us(how to fix that?or maybe tc server issue?)

give some links for example:

/?guild=us..killer-durotar 
![QQ截图20211111224338](https://user-images.githubusercontent.com/3896160/141317201-563bc26e-b9ee-46ee-8e14-4c0d29d1f125.png)

this is well but if name is Chinese will give error like Screenshots

**Screenshots**

![QQ截图20211111223932](https://user-images.githubusercontent.com/3896160/141316583-21b23732-c98e-48f2-8f6e-49ba65c92a05.png)

**System:**
 - OS: Win10(64)
 - PHP version:8.0.3
 - revision used:rev. 32
 - Browser (in case of JavaScript / display errors):firefox
 - AzerothCore: no

**Comment by Sarjuuk** [comment]
can you please provide some sample strings for guild and character names.

**Comment by qyh214** [comment]
you can copy this and modify your database to test it.

In addition: in database(e.g:aowow_profiler)  all name are right!

guild name: 为了部落

character name: 为了联盟

**Comment by qyh214** [comment]
Further test report:
maybe url issue.
if you type http://xxxx/?guild=us..%E4%B8%BA%E4%BA%86%E9%83%A8%E8%90%BD   (%E4%B8%BA%E4%BA%86%E9%83%A8%E8%90%BD is 为了部落) you can see.but in guild list  (http://xxxx/?guilds=us.)
you will find out chinese name will missing ,url will like http://xxxx/?guild=us..

Another question:
maybe zhcn is china(cn),for example:http://xxxx/?guild=cn..%E4%B8%BA%E4%BA%86%E9%83%A8%E8%90%BD   (%E4%B8%BA%E4%BA%86%E9%83%A8%E8%90%BD ? but now is us,I don't know how to fix it or is it based on tc server timezone?

**Comment by qyh214** [comment]
https://xxxx/?profiles=us.{servername} is shown 404
```
Uncaught TypeError: Cannot read properties of undefined (reading 'name')
    at Object.getName (locale.js?32:53)
    at Object._parse (Markup.js?32:3847)
    at Object.toHtml (Markup.js?32:4146)
    at Object.printHtml (Markup.js?32:4235)
    at Announcement.setText (global.js?32:21680)
    at Announcement.initialize (global.js?32:21629)
    at new Announcement (global.js?32:21547)
    at ?profiles=us.{servername}:62
```
{servername} is Chinese for example `魔兽世界`

and also shall we should add all timezone,now only us ,eu

**Comment by qyh214** [comment]
suggest fix:
[please test and review,or maybe has other solutions]
https://github.com/Sarjuuk/aowow/blob/e4b8a8e90888ef93d58543205b4641eb354d951e/static/js/global.js#L22229
replace to
`        str = str;`

https://github.com/Sarjuuk/aowow/blob/e4b8a8e90888ef93d58543205b4641eb354d951e/includes/profiler.class.php#L171
replace to
`        $str = $str;`

**Comment by Sarjuuk** [comment]
timezone is derived from here: https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130016/realmlist#realmlist-timezone but can only resolve to EU or US (default)

as for the original error: It works for me, but it really shouldn't, because the regexes you mentioned should truncate it..? I am confuse.
![image](https://user-images.githubusercontent.com/848030/153716535-0baa38d8-e04e-4fc5-99e2-5712eac13fb7.png)

**Comment by qyh214** [comment]
maybe test server name?
your server name is trinity ,if is `服务器`
for example: /?profile=us.服务器.为了部落

**Comment by Sarjuuk** [comment]
yup, now it's borked

**Comment by qyh214** [comment]
seems well in /?profiles
but /?guilds /?arena-teams is broked. want to fix.

**Comment by Sarjuuk** [comment]
a24e8594fbbcb3db2ffa5f6ef79384287d551aa6
fair

**Comment by qyh214** [comment]
have test after a24e8594fbbcb3db2ffa5f6ef79384287d551aa6 all fine!
thanks a lot.
