### ISSUE TITLE
Profiler: Profiler index page is 404 in php 8.0

### ISSUE THREAD

**Issue by qyh214** [Sarjuuk/aowow#315]
**Describe the bug and how to reproduce it**
when go to url http://xxx/?profilers will give 404 in php 8.0
in aowow_errors has two errors:
Undefined array key "activespec" in line 650
Unsupported operand types: string + int in line 36

**Screenshots**
n/a

**System:**
 - OS: Win10(x64)
 - PHP version:8.0.3
 - revision used:32
 - Browser (in case of JavaScript / display errors):firefox
 - AzerothCore: no

suggest fix:
https://github.com/Sarjuuk/aowow/blob/e4b8a8e90888ef93d58543205b4641eb354d951e/includes/types/profile.class.php#L36

replace to

`'talentspec'        => (int)$this->getField('activespec') + 1, `

after
https://github.com/Sarjuuk/aowow/blob/e4b8a8e90888ef93d58543205b4641eb354d951e/includes/types/profile.class.php#L647

add

`$curTpl['activespec'] = 0;`

**Comment by Sarjuuk** [comment]
There used to be  a field `activespec` in the `characters` table. 
Did it get renamed or moved?

**Comment by qyh214** [comment]
> There used to be a field `activespec` in the `characters` table. Did it get renamed or moved?

tc char database? tc has renamed it to activeTalentGroup(but I forgot which commit)

**Comment by Sarjuuk** [comment]
Heh, there it is.

**Comment by Sarjuuk** [comment]
58_2015_03_21/2015_06_26_00_characters_335.sql

Oh, looks like it got just changed.


/s

**Comment by Sarjuuk** [comment]
probably fixed

**Comment by qyh214** [comment]
Have test in php 8.0.3 and revert temp fix , use f3f8dac fix.
fine and also fix profiler page always start resynchronize action.
now aowow_errors no related error.
