### ISSUE TITLE
commit a1f0f3d30dd7b4d44a25c8594f9d974efc6222c2 will cause page error

### ISSUE THREAD

**Issue by qyh214** [Sarjuuk/aowow#316]
**Describe the bug and how to reproduce it**
commit a1f0f3d30dd7b4d44a25c8594f9d974efc6222c2 will cause page error:
`Warning: Constant CND_TYPE_MASK already defined in \includes\defines.php on line 1344`

**Screenshots**
n/a

**System:**
 - OS: Win10
 - PHP version:8.0.3
 - revision used:32
 - Browser (in case of JavaScript / display errors):firefox
 - AzerothCore: no

**Comment by Sarjuuk** [comment]
FFS

061449686d4f5ea1b91a300d2e27c11044b3b4ce
