### ISSUE TITLE
no data

### ISSUE THREAD

**Issue by blacknightt1** [Sarjuuk/aowow#317]
hello

The installation process is complete and two databases are created

And the world database data is also spilled

But there is no data in the whole site

[https://dl.mohammadyousefi.com/](https://dl.mohammadyousefi.com/)

![sshot-2](https://user-images.githubusercontent.com/73441575/142765049-67513ca5-70f6-41e8-b556-59c5055635b6.jpg)

**Comment by blacknightt1** [comment]
You have a video of the installation process for us to see
And we can install
Because I have a problem in step 4 --- 4. Extract the client archives (MPQs)---

Or do you not have a file ready for us to use?

**Comment by blacknightt1** [comment]
Hello

Is the listfile I used correct?

https://mega.nz/file/Vl9iyb5a#LAJsAswb3AfKbr1QjewehGM6r8k_WbiefSmcFueKkGI

If not correct please listfile the file which is complete and correct

 Give the link.

![sshot-1](https://user-images.githubusercontent.com/73441575/142781680-d6d3086c-218d-4732-85af-38b603a3a6f2.jpg)

**Comment by blacknightt1** [comment]
Do you have these files in setup / mpqdata /

It is enough to drop or other files

Like: item should I drop too?


![sshot-1](https://user-images.githubusercontent.com/73441575/142834090-eae7e5c0-09c4-452d-9841-b7304a12045f.jpg)

**Comment by qyh214** [comment]
You only need to export the file according to the following requirements:
https://github.com/Sarjuuk/aowow#4-extract-the-client-archives-mpqs
