### ISSUE TITLE
Must we install trinitycore server in vps?

### ISSUE THREAD

**Issue by blacknightt1** [Sarjuuk/aowow#318]
Hi
To install

https://github.com/Sarjuuk/aowow

Must we install trinitycore server in vps?

**Comment by jackpoz** [comment]
To install https://github.com/Sarjuuk/aowow check the requirements in the readme on the homepage at https://github.com/Sarjuuk/aowow#requirements .

Installing the whole TrinityCore is not required but you still need some bits, like TrinityCore Database.
There is also a highly recommended step at https://github.com/Sarjuuk/aowow#highly-recommended that does require TC to be installed (you could run it locally and then backup/restore the database, it depends on what's easier for you)

**Comment by blacknightt1** [comment]
Now my problem:


![12 42 57](https://user-images.githubusercontent.com/73441575/143035582-9985ade2-94bb-4b8d-9ff3-b7ad1495ee43.jpeg)

**Comment by qyh214** [comment]
go db aowow.aowow_errors see errors or folder permission?

**Comment by blacknightt1** [comment]
-- phpMyAdmin SQL Dump
-- version 4.9.7
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Nov 23, 2021 at 05:41 PM
-- Server version: 10.3.32-MariaDB
-- PHP Version: 7.3.32

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `myousefi_aowow`
--

-- --------------------------------------------------------

--
-- Table structure for table `aowow_errors`
--

CREATE TABLE `aowow_errors` (
  `date` int(10) UNSIGNED DEFAULT NULL,
  `version` tinyint(3) UNSIGNED NOT NULL,
  `phpError` smallint(5) UNSIGNED NOT NULL,
  `file` varchar(150) COLLATE utf8mb4_unicode_ci NOT NULL,
  `line` smallint(5) UNSIGNED NOT NULL,
  `query` varchar(250) COLLATE utf8mb4_unicode_ci NOT NULL,
  `userGroups` smallint(5) UNSIGNED NOT NULL,
  `message` mediumtext COLLATE utf8mb4_unicode_ci DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `aowow_errors`
--

INSERT INTO `aowow_errors` (`date`, `version`, `phpError`, `file`, `line`, `query`, `userGroups`, `message`) VALUES
(1637674061, 32, 2, '/home/myousefi/dl.mohammadyousefi.com/includes/utilities.php', 250, 'CLI', 0, 'stream_select(): unable to select [4]: Interrupted system call (max_fd=0)');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `aowow_errors`
--
ALTER TABLE `aowow_errors`
  ADD PRIMARY KEY (`file`,`line`,`phpError`,`version`,`userGroups`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;

**Comment by blacknightt1** [comment]
error :

**Comment by blacknightt1** [comment]
`-- phpMyAdmin SQL Dump
-- version 4.9.7
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Nov 23, 2021 at 05:45 PM
-- Server version: 10.3.32-MariaDB
-- PHP Version: 7.3.32

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `myousefi_aowow`
--

-- --------------------------------------------------------

--
-- Table structure for table `aowow_errors`
--

CREATE TABLE `aowow_errors` (
  `date` int(10) UNSIGNED DEFAULT NULL,
  `version` tinyint(3) UNSIGNED NOT NULL,
  `phpError` smallint(5) UNSIGNED NOT NULL,
  `file` varchar(150) COLLATE utf8mb4_unicode_ci NOT NULL,
  `line` smallint(5) UNSIGNED NOT NULL,
  `query` varchar(250) COLLATE utf8mb4_unicode_ci NOT NULL,
  `userGroups` smallint(5) UNSIGNED NOT NULL,
  `message` mediumtext COLLATE utf8mb4_unicode_ci DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `aowow_errors`
--

INSERT INTO `aowow_errors` (`date`, `version`, `phpError`, `file`, `line`, `query`, `userGroups`, `message`) VALUES
(1637673939, 32, 8, '/home/myousefi/dl.mohammadyousefi.com/includes/kernel.php', 134, 'CLI', 0, 'Constant CFG_SQL_LIMIT_SEARCH already defined');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `aowow_errors`
--
ALTER TABLE `aowow_errors`
  ADD PRIMARY KEY (`file`,`line`,`phpError`,`version`,`userGroups`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;`

**Comment by blacknightt1** [comment]
![sshot-1](https://user-images.githubusercontent.com/73441575/143041804-541394a0-808b-4a03-9758-f81f1d2b4b52.jpg)

**Comment by blacknightt1** [comment]
[kernel](https://mega.nz/file/100EyDJB#V528jM72HLrZ4zqtFIBXX6Hm9zFzxMwqSHiZ_48VjQM)

[utilities](https://mega.nz/file/Ro1kVbrR#tV3sThmLI-7nBwflv0Xe8G-CCR3ZleGfHBQC1G7aF8c)

**Comment by blacknightt1** [comment]
![sshot-2](https://user-images.githubusercontent.com/73441575/143043997-7681947d-fb7f-40ad-b76e-0c24f986886c.jpg)
![sshot-3](https://user-images.githubusercontent.com/73441575/143044011-8099d623-a519-4182-8060-cafc11c015e9.jpg)

**Comment by jackpoz** [comment]
I would suggest first setting aowow up on a local environment, then setting it up in a vps with whatever limited permissions are given by your provider.

You have a error "stream_select(): unable to select [4]: Interrupted system call (max_fd=0)", that would be a place to start for the vps error

**Comment by blacknightt1** [comment]
But I am installing on cpanel

**Comment by jackpoz** [comment]
Did you solve this ?

**Comment by jackpoz** [comment]
What was the issue ?

**Comment by blacknightt1** [comment]
I deleted all the databases and reinstalled them

**Comment by blacknightt1** [comment]
But this is my problem now

https://github.com/Sarjuuk/aowow/issues/319
