### ISSUE TITLE
no suitable localized map files found for locale

### ISSUE THREAD

**Issue by blacknightt1** [Sarjuuk/aowow#319]
Why do I get this error?

![sshot-4](https://user-images.githubusercontent.com/73441575/143504447-e6334f7c-7123-46bd-b46b-9fa9cfc9d31d.jpg)

![sshot-2](https://user-images.githubusercontent.com/73441575/143504518-d4224d33-61ff-4311-912d-607d329e1c78.jpg)

**Comment by qyh214** [comment]
data extract incomplete.
https://github.com/Sarjuuk/aowow/issues/317#issuecomment-976589814 I have said.

Please take out the data according to the requirements here, and it is the complete data of your client
https://github.com/Sarjuuk/aowow#4-extract-the-client-archives-mpqs

**Comment by blacknightt1** [comment]
I extracted the WORLDMAP file again. Do I have to go through the installation process again from 0-100?

Or do I have to enter a new code for this error to fix this problem?

**Comment by blacknightt1** [comment]
![sshot-1](https://user-images.githubusercontent.com/73441575/143552564-01548015-eee8-4f79-9125-d30e24447175.jpg)
![sshot-2](https://user-images.githubusercontent.com/73441575/143552576-03e5f016-baa8-474b-a78d-36a6bbd0c9fc.jpg)
![sshot-3](https://user-images.githubusercontent.com/73441575/143552582-3cfb0c7e-6c01-43a8-8b2f-048b74748302.jpg)

**Comment by blacknightt1** [comment]
Tested for 40 times!
Unfortunately, my problem was not solved
Can anyone extract a map file for me?

**Comment by blacknightt1** [comment]
![sshot-5](https://user-images.githubusercontent.com/73441575/143610184-47c3ec42-da47-415b-9066-e6fdf3fd32d3.jpg)

**Comment by blacknightt1** [comment]
I do not want the audio file

 Only files
 1- DBFilesClient
2- Interface
