### ISSUE TITLE
How can I define LOCALES?

### ISSUE THREAD

**Issue by blacknightt1** [Sarjuuk/aowow#321]
I have this problem
I have been told that I must define LOCALES before starting the installation

![sshot-1](https://user-images.githubusercontent.com/73441575/143788388-c284308f-bbfd-4dea-b3c8-d033d5dae837.jpg)

**Comment by blacknightt1** [comment]
I use the following code but it gives an error

php aowow --locales=<enUS>
bash: syntax error near unexpected token `newline'

**Comment by blacknightt1** [comment]
![sshot-1](https://user-images.githubusercontent.com/73441575/143829377-5db7377c-8b7d-4ada-8a98-20c1f0596506.jpg)

**Comment by Sarjuuk** [comment]
fixed in c950cdc757f39ca98ecfcd13fe36029150703b5d
