### ISSUE TITLE
Can I manually enter location for some npcs?

### ISSUE THREAD

**Issue by blacknightt1** [Sarjuuk/aowow#322]
Can I manually enter location for some npcs?

![sshot-1](https://user-images.githubusercontent.com/73441575/144009554-926ceafd-84a8-446b-ae65-48f85ce4c27b.jpg)

**Comment by Helias** [comment]
"manually"? Probably you need to change it in the aowow_ tables, like aowow_creatute

**Comment by blacknightt1** [comment]
I have checked these cases many times but I do not see any change in the site!

**Comment by qyh214** [comment]
npc location based on client instance map information.(in game,type `M` you can see your location and  current map overview)
in 3.3.5, only wotlk instance and raid have instance map,so other npc will show location unknown is right.
--
how to fix:
you should modify client to add all map information into client and maybe fix some aowow install scripts.(It's just an idea, but it's not the content of this project,)

**Comment by blacknightt1** [comment]
You look at this site.
See the dungeon
Aowow sites do not show these areas and dungeons

https://classicdb.ch/?npc=14323

**Comment by Sarjuuk** [comment]
The 3.3.5 client does not have maps for most non-wotlk instanced areas. That means entities can't be displayed there. 

If you want to add a spawn point for an entity spawned by script/AI, you'll have to enter it manually in `aowow_spawns`. Though, the manual data will be deleted whenever you sync spawns with the game server. There is currently no interface.
