### ISSUE TITLE
How can I see all the npcs in this section?

### ISSUE THREAD

**Issue by blacknightt1** [Sarjuuk/aowow#323]
Hi
How can I see all the npcs in this section?
It shows up to 300 for me
For example, I want to be able to see the number 500 after the number 300 and to be able to see the number 1500 after the number 800.
And so o

![sshot-1](https://user-images.githubusercontent.com/73441575/144763511-9049c8bc-b04e-4103-841f-9d83664d5f6e.jpg)

**Comment by qyh214** [comment]
/?admin=siteconfig SQL_LIMIT_DEFAULT you can set 9999999(but It is not recommended to do so, which will lead to a significant decline in page performance. It should be accurately searched by the user)

**Comment by blacknightt1** [comment]
Hi
Thank you, it was fixed
