### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by blacknightt1** [Sarjuuk/aowow#326]
Hello
In the screenshot section, I can log in with the admin account and confirm the photos
But in the video, I get a Page not found error.

what is the problem ?

![sshot-1](https://user-images.githubusercontent.com/73441575/147820652-621e8fbb-356f-4fc6-b9ed-000cd5cf6d14.jpg)
![sshot-2](https://user-images.githubusercontent.com/73441575/147820655-e5b157ab-a8c3-4480-8540-9003a32911ff.jpg)

**Comment by Sarjuuk** [comment]
Video Management is NYI. 

At the moment you can add them manually into `aowow_videos` and it should work. It only supports Youtube. 

https://www.youtube.com/watch?v= `xYqJ-8FiXCI` < videoId

status flags https://github.com/Sarjuuk/aowow/blob/541224f87bca88995b9721ced0b270d91b73015c/includes/defines.php#L241-L245 types https://github.com/Sarjuuk/aowow/blob/541224f87bca88995b9721ced0b270d91b73015c/includes/defines.php#L28-L47

and everything else is hopefully self explanatory.

**Comment by blacknightt1** [comment]
Hello
The problem was not solved!

https://www.youtube.com/watch?v=6QMk7ah-vSA

**Comment by Sarjuuk** [comment]
**N**ot **Y**et **I**mplemented
If you don't know SQL you cant add videos!

**Comment by blacknightt1** [comment]
You write the code for me here so I can enter it in sql
Keep the video link above and your own npc id
