### ISSUE TITLE
Feature request:profiles/guilds/arenateams support all regions

### ISSUE THREAD

**Issue by qyh214** [Sarjuuk/aowow#328]
now we have us and eu in profiles/guilds/areanteams,suggest we should have all regions.  use tc server timezone like https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130016/realmlist#realmlist-timezone
some info https://github.com/Sarjuuk/aowow/issues/313#issuecomment-1037250544

**Comment by Sarjuuk** [comment]
10805a1f7053b97f532d0c447f22ac7f647055f2

though blizzards usage of regions is pretty arbitrary/inconsistent.
