### ISSUE TITLE
Uninitialized string offset 0 warning

### ISSUE THREAD

**Issue by jackpoz** [Sarjuuk/aowow#329]
**Describe the bug and how to reproduce it**
When updating sql with --sql , I get this warning:
>E_WARNING - Uninitialized string offset 0 @ /trinity/aowow/includes/utilities.php:207

**Screenshots**
![image](https://user-images.githubusercontent.com/1153754/155838896-e2220f98-106a-4171-8020-8a8a829f63e5.png)

**System:**
 - OS: Ubuntu
 - PHP version: PHP 8.0.8 (cli) (built: Oct 26 2021 11:42:42) ( NTS )
 - revision used: https://github.com/Sarjuuk/aowow/commit/bc71ae762cbf80393480dc2e0b7d88f412816db3
 - Browser (in case of JavaScript / display errors): using console only
 - AzerothCore: no, no, no and no

**Comment by Sarjuuk** [comment]
just for the sounds step or in other parts as well?

**Comment by jackpoz** [comment]
It might actually be only in the sounds step, find a better log at https://gist.github.com/jackpoz/e73af0c803d7eab5e9e19c1a6a9229c8 (I will update it once it finishes).

I don't think I follow all the steps required to extract sounds as I am not much interested into those, in particular https://github.com/Sarjuuk/aowow#5-reencode-the-audio-files . Mentioning it in case you cannot reproduce the issue.

As usual, I'm available to test some branches if needed.

**Comment by jackpoz** [comment]
Found one more:
>E_WARNING - Trying to access array offset on value of type bool @ /trinity/aowow/setup/tools/sqlgen/itemset.func.php:122

The gist has been updated with a full log

**Comment by Sarjuuk** [comment]
ty, 
for what it is worth, those ofset warnings are probably not new but get logged to the console since https://github.com/Sarjuuk/aowow/commit/bc71ae762cbf80393480dc2e0b7d88f412816db3

**Comment by Sarjuuk** [comment]
thanks i hate itemsets

19584feab0a91476cdf1ab10d6e9077af52adf58
