### ISSUE TITLE
Missing links between spells and NPCs who use them

### ISSUE THREAD

**Issue by wodim** [Sarjuuk/aowow#330]
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=33900 should link to https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=18872

Also the rest mentioned in #224

**Comment by Sarjuuk** [comment]
8431329645db4f65910a6f1bfb75e6bd3571a8d6

no idea why i grouped these queries in the first place
