### ISSUE TITLE
"Auto accept" not shown in quest pages

### ISSUE THREAD

**Issue by wodim** [Sarjuuk/aowow#332]
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=6394

A request: when a quest is auto accepted that info should show in the quick facts sidebar. Currently it only shows in tables.

**Comment by Sarjuuk** [comment]
hm, fair

also the breadcrumb trail seems to be broken for starter zone quests

**Comment by Sarjuuk** [comment]
added in a1e7bfaa02a4446a5bb77f9dd2c5aa0553c1da61
