### ISSUE TITLE
Display spells without description on item

### ISSUE THREAD

**Issue by wodim** [Sarjuuk/aowow#335]
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=37934 should link to https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=50200

**Comment by Sarjuuk** [comment]
It does. 
It's just, that the spell has no description text. So there is nothing to display on the item. Like in game. 

maybe i can come up with a workaround that doesn't look too out of place.
