### ISSUE TITLE
Google Analytics for Aowow

### ISSUE THREAD

**Issue by dotdotguy** [Sarjuuk/aowow#338]
Hi, I've been trying to enable Google Analytics for my Aowow site but have been unable to get it to work.
I've tried updating my 'AOWOW ANALYTICS_USER' using both the new 'Google Analytics 4 property' as well as the old 'Universal Analytics' GA ways but I'm unsure whether or not there's anything else I need to do since neither seem to work.

If you could provide further information on how I could set this up so I can track my site stats, that'd be appreciated. Thanks!

**Comment by Sarjuuk** [comment]
for futur reference. Its the `UA-xxxxxx-y` key.

**Comment by dotdotguy** [comment]
> for future reference. Its the `UA-xxxxxx-y` key.

Yeah, my confusions was because Google Analytics keeps sending you to the new 'Google Analytics 4 property' because the old 'Universal Analytics' will stop processing data on July 1, 2023. So I had to go through a few extra steps to use the older system.

Will changes have to be made in the future when UA inevitably stops processing data? Thanks.

**Comment by Sarjuuk** [comment]
i haven't followed on GAs development, so this is news to me. 

Not sure yet if i'll adapt it or drop it completely. Depends on the effort reqired, i guess.
