### ISSUE TITLE
suggest:both support http and https

### ISSUE THREAD

**Issue by qyh214** [Sarjuuk/aowow#341]
**Describe the bug and how to reproduce it**
now we use secure and set site to http://xxxx or https://xxxx.   but sometimes maybe we both support is great.

now use //xxxxx can both support and based on original site.

At the same time, this feature needs to configure the server to be compatible with HTTP and HTTPS access at the same time

and also we should keep force ssl  feature,if set force ssl in site config,then all link rewrite to https

**Screenshots**
n/a

**System:**
 - OS: win10
 - PHP version:8.0.1
 - revision used:33
 - Browser (in case of JavaScript / display errors):n/a
 - AzerothCore: no

**Comment by Aokromes** [comment]
imho redirect http to https and leave http to die.

**Comment by Sarjuuk** [comment]
I can't.
there are a couple of tools that are embedded in other pages, that further embed more js and css files. (most notably the tooltips and to a lesser extend the search box)
those would inherit the protocol of the embedding site, which may be wrong.

Ultimately it's up to the site host to kick http to the curb^^

**Comment by Sarjuuk** [comment]
ouh, there is another close option now.
