### ISSUE TITLE
Error at firstrun: `Exception - syntax error, unexpected '->' (T_OBJECT_OPERATOR)`

### ISSUE THREAD

**Issue by Winfidonarleyan** [Sarjuuk/aowow#342]
**Describe the bug and how to reproduce it**
```
[root@web aowow]# php aowow --firstrun
Exception - syntax error, unexpected '->' (T_OBJECT_OPERATOR)
   /home/aowow/includes/types/item.class.php(1429)
#0 [internal function]: {closure}('itemlist')
#1 /home/aowow/setup/tools/sqlgen/item_stats.func.php(10): spl_autoload_call('ItemList')
#2 /home/aowow/setup/tools/sqlGen.class.php(39): include_once('/home/aowow/set...')
#3 /home/aowow/setup/tools/clisetup/setup.func.php(19): SqlGen::init(2)
#4 /home/aowow/setup/setup.php(40): setup()
#5 /home/aowow/aowow(10): require('/home/aowow/set...')
#6 {main}
```

**System:**
 - OS: Centos 8
 - PHP version: `PHP 7.4.29 (cli) (built: Apr 12 2022 10:55:38) ( NTS )`
 - revision used: 2daa7247208a765331a8f2c3a6bc57190169d8c3
 - Browser (in case of JavaScript / display errors):
 - AzerothCore: no

**Comment by qyh214** [comment]
can you upgrade to php 8.0 test

**Comment by Sarjuuk** [comment]
ah great.. 
5 instances of the null safe operator `?->` are in use, which is a v8.0 feature.

honestly, i'll probably bump up the requirements, rather then change those.
It's already been 1.5yr since release...

**Comment by Winfidonarleyan** [comment]
Problem resolved. i update php to 8.0
