### ISSUE TITLE
spell.class.php(1019) : eval()'d code

### ISSUE THREAD

**Issue by opiums9** [Sarjuuk/aowow#345]
In spell = 69420 I get an error: ```syntax error, unexpected ',', expecting ';'```
I don't know what the correct value should be in the end, but I added this code to file as a temporary solution, any ideas how to avoid this error in the future?
```php
        ...
        // hm, minor eval-issue. eval doesnt understand two operators without a space between them (eg. spelll: 18126)
        $formula = preg_replace('/(\+|-|\*|\/)(\+|-|\*|\/)/i', '\1 \2', $formula);
        $formula = preg_replace('/,/', '.', $formula);

        // there should not be any letters without a leading $
        return eval('return '.$formula.';');
        ...
```

**Comment by Sarjuuk** [comment]
I don't see it. The mentioned spell has the following tooltip for me, which parses fine:
`Сокращает время восстановления заклинания суккуба "Всплеск боли" на $/1000;s2 с. и время наложения заклинания беса "Огненная стрела" на ${0-$m1/1000}.2 с.`

no other eval() errors in my logs so far.

**Comment by opiums9** [comment]
I assume that my errors are due to the fact that I have not updated the version of aowow since February 15, 2021
