### ISSUE TITLE
Unable to finish installation of aowow - Exception - Game::worldPosToZonePos(): Argument #4 ($areaId) must be of type int, string given, called in /var/www/html/aowow/setup/tools/sqlgen/spawns.func.php on line 123    /var/www/html/aowow/includes/game.php(326)

### ISSUE THREAD

**Issue by 33mirra33** [Sarjuuk/aowow#350]
Hello,

firstly I want to thank you for, what you did on this project. You are working on amazing project and even through I am unable in my free time to make it work properly and try to finish the installation, I fully accept, that you are doing something really awesome. Thank you very much.

**Describe the bug and how to reproduce it**
I am installing on php 7.4.26/8.0.x/8.1.6 debian 11 aowow and I am unable to finish installation.
```
23:44:07          SqlGen::generate() - filling aowow_spawns with data
23:44:07           - reading and merging map.dbc for locales 0
23:44:07           - reading taxipathnode.dbc
23:44:07           - reading soundemitters.dbc
23:44:07           - reading and merging areatable.dbc for locales 0
23:44:07           - assembling creature spawns
23:44:08           * sets 1 - 1000
Exception - Game::worldPosToZonePos(): Argument #4 ($areaId) must be of type int, string given, called in /var/www/html/aowow/setup/tools/sqlgen/spawns.func.php on line 123
   /var/www/html/aowow/includes/game.php(326)
#0 /var/www/html/aowow/setup/tools/sqlgen/spawns.func.php(123): Game::worldPosToZonePos()
#1 /var/www/html/aowow/setup/tools/sqlGen.class.php(239): SetupScript@anonymous->generate()
#2 /var/www/html/aowow/setup/tools/clisetup/setup.func.php(292): SqlGen::generate()
#3 /var/www/html/aowow/setup/setup.php(40): setup()
#4 /var/www/html/aowow/aowow(10): require('...')
#5 {main}

```

When I try to run setup and continue where it ended it will show this:

```
# php aowow --setup
23:48:44          FileGen::init() - creating required directories
23:48:44          created 8 extra paths

23:48:44  [INFO]  Found firstrun progression info. (Halted on subscript spawns)

continue setup? (y/n):
23:48:46          Resuming setup from step 43...
23:48:47          SqlGen::generate() - filling aowow_spawns with data
23:48:47           - assembling creature spawns
23:48:47           * sets 1 - 1000
Exception - Game::worldPosToZonePos(): Argument #4 ($areaId) must be of type int, string given, called in /var/www/html/aowow/setup/tools/sqlgen/spawns.func.php on line 123
   /var/www/html/aowow/includes/game.php(326)
#0 /var/www/html/aowow/setup/tools/sqlgen/spawns.func.php(123): Game::worldPosToZonePos()
#1 /var/www/html/aowow/setup/tools/sqlGen.class.php(239): SetupScript@anonymous->generate()
#2 /var/www/html/aowow/setup/tools/clisetup/setup.func.php(292): SqlGen::generate()
#3 /var/www/html/aowow/setup/setup.php(40): setup()
#4 /var/www/html/aowow/aowow(10): require('...')
#5 {main}
```

At this point I am unable to continue installation, it just crash like this back to shell.

```

**Screenshots**
# php -m
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
imap
intl
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
pspell
readline
Reflection
session
shmop
SimpleXML
soap
sockets
sodium
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tidy
tokenizer
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend OPcache
zip
zlib
```

[Zend Modules]
Zend OPcache

**System:**
 - OS: Linux Debian 11 (  5.10.113-1 (2022-04-29) )
 - PHP version: 8.1.6, 8.0.x , 7.4.26 On all of them it fails. (tested with php-fpm version for 7.4, 8.0, 8.1, on all same issue)
 - revision used: latest from 18.6. 2022
 - Browser (in case of JavaScript / display errors):   firefox, chrome, every browser.
 - AzerothCore: no
 - I am unable to finish installation of the Aowow.

**Comment by TQPS** [comment]
I am also getting this after upgrading my server to MySql v8.x

Pages work from previous version but depreciation warning messages are constantly popping up;
Icons don't display and cant regenerate or run setup due to the errors described above.

**Comment by 33mirra33** [comment]
@Krutok + @TQPS 
My best advice is to run it under a docker with PHP 5.6 or PHP 7.1 or maybe PHP 7.2 with all possible modules and route the traffic only to this container. Security will still be bad, but docker has its own separate namespaces. The other option is to rewrite and refactor all the code written in the Aowow project, and nobody probably wants to do that kind of hard work, and I understand they won't.

**Comment by 33mirra33** [comment]
If you find an alternative to aowow, could you please let us know? Thank you.

**Comment by Sarjuuk** [comment]
> I am installing on php 7.4.26/8.0.x/8.1.6
so, what version was it actually...?

In any case. I could not reproduce that. The quick and dirty solution would be to add a typecast to int here:
https://github.com/Sarjuuk/aowow/blob/master/setup/tools/sqlgen/spawns.func.php#L131
like
```php
                $points = Game::worldPosToZonePos($spawn['map'], $spawn['posX'], $spawn['posY'], intVal($area), $floor);
```
