### ISSUE TITLE
"Drag to change level" broken for certain spell(s)

### ISSUE THREAD

**Issue by wodim** [Sarjuuk/aowow#356]
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=67378

Using the slider breaks the tooltip.

**Comment by wodim** [comment]
Another example: https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=41002

**Comment by Sarjuuk** [comment]
included in f05fe60030694f27cbb80ba10124eb50a7b1e011
