### ISSUE TITLE
"Drops in..." item filter doesn't work

### ISSUE THREAD

**Issue by wodim** [Sarjuuk/aowow#357]
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?items&filter=cr=16;crs=2057;crv=0

If I'm not misunderstanding this, this filter (and "drops in raid...", etc) is broken, since it shows all items.

**Comment by Sarjuuk** [comment]
Not implemented as i have no idea how to efficiently structure the data. 

But also this is behind #245 in general.

**Comment by wodim** [comment]
If you can't currently implement the filter you should consider removing it as it is non-functional.
