### ISSUE TITLE
Better explanation for profession specialisation extra crafts

### ISSUE THREAD

**Issue by wodim** [Sarjuuk/aowow#358]
For example: https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=53901

The way it looks, it seems like there's a 17% chance of getting 1-7 additional items. This is incorrect: there's a 17% chance of getting additional [items to be crafted] items, and if that roll succeeds, there is a 17% chance of getting additional [items to be crafted] items, and so on. In this case (flasks) 2 items are crafted and thus you can get x2 flasks, x4 flasks, etc. but in the case of other crafts such as Spellweave the multiplier is 1.

 Therefore there should be a tooltip like these ones that already exist:

![image](https://user-images.githubusercontent.com/1001553/185763478-bcf0759d-c879-4af6-a807-bd6bd3b4608b.png)

It could say:

Stack of 2: 17% (this % is wrong: it's 17% minus the sum of all the percentages below)
Stack of 4: 2.89%
Stack of 6: 0.4913%
...etc

Well maybe not so many decimals... but you get the idea.

**Comment by Sarjuuk** [comment]
added in 4f5504471a8929ea6402ead1fc15868b4669147c
