### ISSUE TITLE
Model viewer not working

### ISSUE THREAD

**Issue by racerx2** [Sarjuuk/aowow#359]
Model viewer not working due to shockwave flash at EOL. Perhaps this or similar can be implemented in place of flash https://github.com/Miorey/wow-model-viewer

**Comment by Faq** [comment]
There was topic about that https://github.com/Sarjuuk/aowow/issues/301

**Comment by Sarjuuk** [comment]
#301

**Comment by racerx2** [comment]
so we closed it because you are not interested in improving aowow?
