### ISSUE TITLE
Wrong "cost" for certain items

### ISSUE THREAD

**Issue by wodim** [Sarjuuk/aowow#362]
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=49861

![image](https://user-images.githubusercontent.com/1001553/188303606-7582f09a-4766-4c47-b2dc-a47c6b899787.png)

**Comment by Sarjuuk** [comment]
item count for cost must be integer
maybe remove "(each)" in cases where you buy an indivisible batch of something
