### ISSUE TITLE
location npc

### ISSUE THREAD

**Issue by blacknightt1** [Sarjuuk/aowow#363]
Hello
I manually add the location of some npc's that don't exist or are incorrect and it is done correctly in the database.
But when the location in the mode
I add Heroic 10-25, the map and location are not added on that page
where is the problem from?

1. 
![sshot-1](https://user-images.githubusercontent.com/73441575/189473182-1eae7b9c-5111-431b-bf27-c03bf2446e5c.jpg)

2. 
![sshot-2](https://user-images.githubusercontent.com/73441575/189473196-69879109-3ac0-4e0b-98e1-a0a207ea9f39.jpg)

If you look at these two images, you will notice that it has been added to the database and the first image shows Icecrown Citadel
But when we choose one of the heroic modes, there is no map in it

[But take a look at this link](https://wotlk-twinhead.twinstar.cz/?npc=39168)

There are maps and locations for all npc modes and I think this is correct

Thanks

**Comment by Sarjuuk** [comment]
Mode speciffic information are displayed on the page of the base entity. The difficulty dummies are by default hidden from listviews so that shouldn't be a problem. 
It's probably more correct to auto forward from the dummy entity to the base entity in such cases. At least for non-devs.

The difficulty dummys have no spawn point because they are never spawned. The stats are just applied to the base entity if i'm not mistaken.

**Comment by blacknightt1** [comment]
> spawn point

I enter the spawn point manually

And if I want for these things too

The map will be displayed.

what should I do?

**Comment by blacknightt1** [comment]
> Mode speciffic information are displayed on the page of the base entity. The difficulty dummies are by default hidden from listviews so that shouldn't be a problem. It's probably more correct to auto forward from the dummy entity to the base entity in such cases. At least for non-devs.
> 
> The difficulty dummys have no spawn point because they are never spawned. The stats are just applied to the base entity if i'm not mistaken.

I enter the spawn point manually

And if I want for these things too

The map will be displayed.

what should I do?
