### ISSUE TITLE
Add zones and zone

### ISSUE THREAD

**Issue by blacknightt1** [Sarjuuk/aowow#364]
Hello
I have another question in this regard
Look at the image below

![sshot-1](https://user-images.githubusercontent.com/73441575/193663515-af76d920-ddf1-4461-9017-e51755a59037.jpg)

I want to create a new category, I have entered a number of regions in the database with Category number 110, and my problem currently shows undefined, and I want to enter a name for Category number 110, but I don't know in which part

Thank you

**Comment by blacknightt1** [comment]
I fixed this problem
[var g_zone_categories = {](https://github.com/Sarjuuk/aowow/blob/df1ba841c5a70e889bd7b689d495471f465606f7/static/js/locale_enus.js#L2221)


But I still have a problem, when I click on that new name, I enter the 404 page!

![sshot-3](https://user-images.githubusercontent.com/73441575/193682958-d2313896-a00f-4346-b14d-7c982324895c.jpg)

**Comment by Sarjuuk** [comment]
categories are validated against this property https://github.com/Sarjuuk/aowow/blob/master/pages/zones.php#L18
Add ` ,110 => true` to the array.

This validation happens for most (all?) database items.

**Comment by blacknightt1** [comment]
> categories are validated against this property https://github.com/Sarjuuk/aowow/blob/master/pages/zones.php#L18 Add ` ,110 => true` to the array.
> 
> This validation happens for most (all?) database items.

Hello, if possible, write the complete code here, because I will add it, but it gives an error
