### ISSUE TITLE
Page not found when adding video

### ISSUE THREAD

**Issue by blacknightt1** [Sarjuuk/aowow#365]
Hello
I was able to manually add a video to a quest in the database and it works fine.

1. 
![sshot-1](https://user-images.githubusercontent.com/73441575/189474104-e0917205-557d-4115-9464-7e74a5a45a0f.jpg)

2. 
![sshot-2](https://user-images.githubusercontent.com/73441575/189474109-aa000d7d-0dcc-4749-b6fa-9a707da1e454.jpg)

But when I enter the site and add a video, I get an error

1. 

![sshot-1](https://user-images.githubusercontent.com/73441575/189474246-fbf8c731-4a03-4fe0-a7cc-98b88da3ea66.jpg)

2. 
![sshot-3](https://user-images.githubusercontent.com/73441575/189474255-442b46e5-882f-451b-9a6a-0ae47dd99111.jpg)

Is this a bug or am I doing something wrong?
Thank you

**Comment by Sarjuuk** [comment]
The video management is not implemented.

**Comment by blacknightt1** [comment]
> The video management is not implemented.

Why did you close Issues if you concluded it was a bug?

**Comment by Faq** [comment]
not bug, missing feature

**Comment by blacknightt1** [comment]
> 

Worse!

**Comment by Jinnaix** [comment]
> > 
> 
> Worse!

Implement it yourself then and make a pull request. Don't expect others to do it for you. A not implemented feature does not equal a bug.
