### ISSUE TITLE
Error creature

### ISSUE THREAD

**Issue by blacknightt1** [Sarjuuk/aowow#369]
Hello
I ran into a new problem
I in the database and table aowow_creature
I have an npc with id = 189143 but it gives an error and doesn't show on the site.
Why?
Of course, the numbers before 149447 are correct and from now on it gives an error!

Note: I have entered 195823 identifiers in the table and all these identifiers are fully added in the table and if I search for the identifier, this identifier is there.

But unfortunately, ID number 149447 onwards is not shown on the site.

![sshot-1](https://user-images.githubusercontent.com/73441575/200620764-d261b5d2-c9f6-47e9-892a-42bf1ea1aa00.jpg)

![sshot-2](https://user-images.githubusercontent.com/73441575/200620818-c5a22aa1-2e9d-4d96-ab1a-666293b86173.jpg)

**Comment by Sarjuuk** [comment]
like the others: not 3.3.5
also no usable error message to work with. check the aowow_errors table.
