### ISSUE TITLE
Drops item

### ISSUE THREAD

**Issue by blacknightt1** [Sarjuuk/aowow#370]
There are some npc whose LootId is 0

But in the Drops section, it shows some items for them
From which table or column should these numbers be seen?

for example: https://www.wowhead.com/npc=43296/chimaeron

![sshot-3](https://user-images.githubusercontent.com/73441575/200622687-e98df06e-9209-4a1c-bc70-841560ddd5a7.jpg)

**Comment by Sarjuuk** [comment]
not 3.3.5a 
probably need to adapt the query in https://github.com/Sarjuuk/aowow/blob/master/setup/tools/sqlgen/creature.func.php to pick up all fields correcty. and check if the lootId in creature_template isn't also 0
