### ISSUE TITLE
Something about sounds

### ISSUE THREAD

**Issue by huaijiuwow** [Sarjuuk/aowow#371]
**Describe the bug and how to reproduce it**
additionally paste relevant lines from db table  `aowow_errors`
or your browsers console here.

**Screenshots**

**System:**
 - OS: win10
 - PHP version:8.0
 - revision used:1.2
 - Browser (in case of JavaScript / display errors):IE
 - AzerothCore: yes

I success converted the *.wav audio，which dir should i put the.ogg files?

**Comment by Sarjuuk** [comment]
For posterity:
Neither mp3 nor ogg files should be moved manually, The setup will pick them up from `mpqdata/<locale>/sounds/` when it handles the file generation.
