### ISSUE TITLE
erorr icon

### ISSUE THREAD

**Issue by blacknightt1** [Sarjuuk/aowow#372]
I sent you a problem that the aowow system does not show large creature numbers on the site
The same problem exists for icon

Note: In the path \static\images\wow\icons\...

The icon with the name that I sent in the above images is loaded and it is in this path

**Screenshots**

![sshot-1](https://user-images.githubusercontent.com/73441575/204232480-2d48306f-1a1f-4933-88c1-980711d12537.jpg)

![sshot-2](https://user-images.githubusercontent.com/73441575/204232509-3e1980d6-db2e-4ffb-88ca-9b9cb4cfbef5.jpg)

**Comment by blacknightt1** [comment]
The problem was fixed
Icons should be added with lowercase letters

**Comment by Faq** [comment]
This should be handled by code, whatever name is used, convert to lowercase.
