### ISSUE TITLE
erorr spell

### ISSUE THREAD

**Issue by blacknightt1** [Sarjuuk/aowow#373]
I sent you a problem that the aowow system does not show large creature numbers on the site
The same problem exists for spell

**Screenshots**

![sshot-1](https://user-images.githubusercontent.com/73441575/204276875-a9b9e8d0-8d13-48fe-99f2-882c681327b2.jpg)

![sshot-2](https://user-images.githubusercontent.com/73441575/204276891-ce890544-f760-40b8-9d49-239428fc391a.jpg)

**link:**
[https://github.com/Sarjuuk/aowow/issues/369#issue-1440521680](url)

- [ ] https://github.com/Sarjuuk/aowow/issues/369#issue-1440521680

.
.
.
.

**Comment by Sarjuuk** [comment]
again, not 3.3.5a
and no useable error message to work with.
