### ISSUE TITLE
Discrepancy in modified by/modifies listings

### ISSUE THREAD

**Issue by wodim** [Sarjuuk/aowow#377]
[Predator's Swiftness](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=69369#modified-by) has [Improved Nature's Swiftness](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=37292#modifies) in the "modified by" column, but [Predator's Swiftness](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=69369#modified-by) is not in the "modifies" column of [Improved Nature's Swiftness](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=37292#modifies).

**Comment by Sarjuuk** [comment]
fixed in 9aeb2177cf3eda493b32325cece83310c6457256
