### ISSUE TITLE
spell.dbc incorrect format string

### ISSUE THREAD

**Issue by spacefox-platforms** [Sarjuuk/aowow#385]
**Describe the bug and how to reproduce it**
while running the setup script, once it gets to the point of populating the aowow db, i keep running into a problem with spell.dbc

```
08:41:29  [ERR]   incorrect format string (niiiuuuuuuuuixixixixxxxxxxxxiiixxxxiiiiiiiiiiiixxiiiiiiiiiiiiiiiiiiiiiiiiiiiifffiiiiiiiiiiiiiiiiiiiiifffiiiiiiiiiiiiiiifffiiiiiiiiiiiiixsxsssxsxsxxxxxxxxsxsssxsxsxxxxxxxxsxsssxsxsxxxxxxxxsxsssxsxsxxxxxxxxiiiiiiiiiixxfffxxxiixiixifffii) specified for file setup/mpqdata/enus/dbfilesclient/spell.dbc fieldCount=240
08:41:29  [ERR]   no suitable files found for spell.dbc, aborting.
08:41:29  [ERR]   CLISetup::loadDBC() - required DBC spell.dbc not found!
```
seems that the spell.dbc has the incorrect number of fields? the string format shows 234 individual characters, apparently the copy i have has 240 fields
i've tried with 2 different mpq sets from 2 different 3.3.5a clients with no change.

**Screenshots**

**System:**
 - OS: Debian 12.2 
 - PHP version: 8.2.7
 - revision used:
 - Browser (in case of JavaScript / display errors): n/a
 - AzerothCore: yes

**Comment by Sarjuuk** [comment]
https://github.com/TrinityCore/TrinityCore/blob/acf5ce58a7d3ced306eeebd60dbc36732b21ad56/src/server/shared/DataStores/DBCStructure.h#L1397-L1506
I'm pretty sure 234 fields is correct.

Now I'm curious. Where the hell did you get your client? :D

**Comment by spacefox-platforms** [comment]
ah, i did some digging, compared filesizes and found that the files were not being overwritten when running the [mpqextract script](https://gist.github.com/Helias/d9bd7708e28e9e8dcd5274bd2f3b68bc)
manually extracted spells.dbc from patch-enUS-3.mpq and used that, everything moved on.
there were a couple of other dbcs that needed this done with as well.
