### ISSUE TITLE
Small link issue

### ISSUE THREAD

**Issue by CraftedRO** [Sarjuuk/aowow#388]
**Describe the bug and how to reproduce it**
Woud be nice in the future to remove questionmark (?) from link to be much more wowhead-like.

**Screenshots**
![Captură de ecran 2024-02-06 033807](https://github.com/Sarjuuk/aowow/assets/24683355/47acabf4-117b-4f8e-9f09-dad504ffc646)

also seems like in generated #links button there's missing a slash before questionmark.
![Captură de ecran 2024-02-06 033511](https://github.com/Sarjuuk/aowow/assets/24683355/61ddb52c-46e3-473d-a254-2250f6633ee1)

**Comment by CraftedRO** [comment]
> this has to be the most minor bug in the history of bugs.

the part with removing questionmark from the url scheme was still not implemented.

**Comment by Sarjuuk** [comment]
you .. can't?

the fancy url flattening that wowhead does requires a server mod (e.g. [mod_rewrite for Apache](https://httpd.apache.org/docs/current/mod/mod_rewrite.html)), nginx has a different system for the same effect. And that is well within the realm of the server operator.

**Comment by CraftedRO** [comment]
haven't even tried, not using this, it just what I've seen on aowow.trinitycore.info and was not match wowhead and this might be an issue for other apps that get data from there since there's a missmatch between aowow and wowhead url scheme when you switch between.

**Comment by Sarjuuk** [comment]
It works at least one way. Even after over a decade wowhead understands the unmodded urls and display the correct page.
