### ISSUE TITLE
Changes to STATIC_HOST/SITE_HOST are not synced

### ISSUE THREAD

**Issue by Toshik** [Sarjuuk/aowow#39]
`php aowow --siteconfig` then edit STATIC_HOST or SITE_HOST:
this does not affects to static files contents (e.g. power.js) where those paths are constantly defined

**Comment by Sarjuuk** [comment]
no, they have to be regenerated using `php aowow --build=file1,file2,...,fileN`

If you want to add a system, that automatically regenerates files based on updated config values, feel free to do so. 
Sadly i can't spare time for this at the moment :/

**Comment by Toshik** [comment]
Ok, it will be on my checklist
At least, now I know how to regenerate files :)

**Comment by Sarjuuk** [comment]
Whoool...!
It's fixed!
