### ISSUE TITLE
Mousing Over no longer displays details since update

### ISSUE THREAD

**Issue by TQPS** [Sarjuuk/aowow#393]
As per title, the mousing over of an item no longer displays full details.

Background & Reproducing Steps:
=====================
- Some months ago, I updated MySQL from 5.7 to 8.x 
- Previously, updating aowow using --update failed as already reported by others
(Broke things, no pictures, no tooltips, who drops what wouldn't display; unusable.)
- March 2024, pulled recent repository and reran aowow --setup (Thank you for the update!!)
(Works, pictures appears, dropped-by working ... tooltips? no, mouse-overs dont work.)
- SITE_HOST & STATIC HOST settings not changed

Caveats:
======
- When entering the front page, the following two warnings are displayed:
```
Deprecated: Creation of dynamic property DbSimple_Mysqli::$attributes is deprecated in C:\Servers\WOTLK.bots\_Server\apache\htdocs\database\includes\libs\DbSimple\Database.php on line 453

Deprecated: Creation of dynamic property DbSimple_Mysqli::$_lastQuery is deprecated in C:\Servers\WOTLK.bots\_Server\apache\htdocs\database\includes\libs\DbSimple\Mysqli.php on line 160
```

- Installation does fail towards the end with the following:
```
* #2  Drop [NPC]Exception - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '> 0, 1, 0)) FROM aowow_creature WHERE id IN ('36296', '36296', '1178', '1179', '' at line 1
   C:\Servers\WOTLK.bots\_Server\apache\htdocs\database\includes\libs\DbSimple\Mysqli.php(163)
```

Screens
=====
Siteconfig has all correct settings for a local setup:
- SITE_HOST is local IP 192.168.10.210/database
- STATIC_HOST is local IP 192.168.10.210/database/static

<details>

![image](https://github.com/Sarjuuk/aowow/assets/66294837/f18a929a-e08d-4161-9572-651cf04a091c)

</details>

- F12; looks good and URIs look correct.
<details>

![image](https://github.com/Sarjuuk/aowow/assets/66294837/4dc39985-2232-4d6a-9008-1569df31415b)

</details>

Mouse-over/Tooltips are not working. Is this related to the SQL upgrade to 8 where some of the "depreciation warnings" are preventing them?
Is it possible the incomplete installation missing a vital step that comes after it aborts?

**System:**
 - OS: Windows 10
 - PHP version: PHP 8.2.5 (cli) (built: Apr 12 2023 08:43:43) (ZTS Visual C++ 2019 x64)
 - revision used: 25b5928a22694d0b138c8ceac266263e9ebadbda
 - Browser (in case of JavaScript / display errors): Firefox latest
 - AzerothCore: No

**Comment by Sarjuuk** [comment]
https://github.com/Sarjuuk/aowow/blob/25b5928a22694d0b138c8ceac266263e9ebadbda/setup/tools/sqlgen/source.func.php#L266

Maybe `rank` needs to be in backticks. I faintly remember mysql introducing more keywords.

If you stopped there then about a third of your setup is missing which could very well affect the tooltips.

**Comment by Sarjuuk** [comment]
should be better after ec1a2afc5f7aaa243de83e9552ce4fabc14ffcc5

**Comment by TQPS** [comment]
Confirmed.

Setup detected the previous attempt and continued:

<details>

![image](https://github.com/Sarjuuk/aowow/assets/66294837/21c09840-befc-4192-8153-720642ecdb27)

</details>

Site loads. Depreciation warnings are gone! Mouse overs and tooltips working again!

<details>

![image](https://github.com/Sarjuuk/aowow/assets/66294837/d280447e-b98d-41c5-b572-9c614828f2fe)

</details>

Legend! Thank you so much. Sincerely appreciate the hard work that went into the updates!

This issue can be closed as completed.
