### ISSUE TITLE
All admin pages are KO

### ISSUE THREAD

**Issue by Endalaust** [Sarjuuk/aowow#395]
**Describe the bug and how to reproduce it**

Since this commit https://github.com/Sarjuuk/aowow/commit/ec1a2afc5f7aaa243de83e9552ce4fabc14ffcc5  all admin pages are inaccessible
https://woehead.way-of-elendil.fr/?admin=[...]

**Screenshots**

![screenshot_4565](https://github.com/Sarjuuk/aowow/assets/1420867/2ac4ef86-bab8-48dd-ae84-ae4b595fd44c)

**System:**
 - OS: Deb
 - PHP version: 8.2.15
 - revision used:  494328cf5339e6e30976895b530129f5c643c1dc
 - Browser (in case of JavaScript / display errors): All
 - AzerothCore: lol, TC pls

**Comment by Sarjuuk** [comment]
https://github.com/Sarjuuk/aowow/blob/master/index.php#L124 
here? are you sure?

**Comment by Endalaust** [comment]
I'm not, but it's the only error I have (nothing about apache log or in aowow_errors table)

**Comment by Sarjuuk** [comment]
Is your index.php different from the one I linked?

**Comment by Sarjuuk** [comment]
weirdly misplaced error source aside, this should be it.

555a6211bd3658798ecedfa7a94cc207bd21f44e
