### ISSUE TITLE
Unit is missing in spells details table

### ISSUE THREAD

**Issue by Endalaust** [Sarjuuk/aowow#398]
**Describe the bug and how to reproduce it**

https://woehead.way-of-elendil.fr/?spell=33856 
Insides table, units are sometimes missing or didnt easy to find
It's absolutly not a big deal, but players came to ask, so... :) 

**Screenshots**

In red we can see unit is percent
But unit is not precised for the next lines

From aowow:

![screenshot_4654](https://github.com/Sarjuuk/aowow/assets/1420867/c3f29aca-ef2f-4e38-b99e-74b1d53d38ff)

From wowhead: https://www.wowhead.com/wotlk/fr/spell=33856/survie-du-plus-fort

![screenshot_4655](https://github.com/Sarjuuk/aowow/assets/1420867/34d76f25-2dfc-4238-8829-6dfb654e90b2)

**Comment by Sarjuuk** [comment]
added in d2e109d81834b0d4591e26ea670582dd1d5001c8
