### ISSUE TITLE
3D model display does not work

### ISSUE THREAD

**Issue by vahzxz** [Sarjuuk/aowow#399]
**Describe the bug and how to reproduce it**
3D model display does not work

**Screenshots**
![image](https://github.com/Sarjuuk/aowow/assets/37352351/883765b3-c24b-4b2b-9abe-ccbe17da3478)

**Comment by Sarjuuk** [comment]
see: https://github.com/Sarjuuk/aowow?tab=readme-ov-file#troubleshooting
It's gone and not fixable.
