### ISSUE TITLE
The website is currently closed for maintenance

### ISSUE THREAD

**Issue by ParadoXs** [Sarjuuk/aowow#40]
Hello i download and run this db, but after config i recive this measage:
The website is currently closed for maintenance.
This will take a few minutes...

You can help me?

**Comment by Sarjuuk** [comment]
while in the siteconfig part of the first-time setup you should have unset the `maintenance` key.

you can get there again by using `php aowow --siteconfig`

**Comment by Hoyung** [comment]
what a lovely tip , i love #40

**Comment by darkmihai** [comment]
hello i have the same problem how i can fix ?

**Comment by Sarjuuk** [comment]
On second thought...
the setup will automaticly unset the maintenance flag in the end. So yours was Interrupts at some point.
I suggest you rerun it.
