### ISSUE TITLE
It is impossible to leave a comment in Russian

### ISSUE THREAD

**Issue by vahzxz** [Sarjuuk/aowow#400]
**Describe the bug and how to reproduce it**
When creating a comment in the established Russian language. It gives an error and writes that this page is only available in English, but after returning to the subject, a comment appears

Mysql 5.7
PhP 8.2
Linux

**Screenshots**
![image](https://github.com/Sarjuuk/aowow/assets/37352351/305a33af-4a53-4de9-92fe-67235b086e3c)

**Comment by peycho** [comment]
I would suggest you to post more details in this regards.
Like OS, php version, mysql version, aowow revision. Probably some logs.

**Comment by vahzxz** [comment]
> I would suggest you to post more details in this regards. Like OS, php version, mysql version, aowow revision. Probably some logs.

Done

**Comment by Sarjuuk** [comment]
cannot reproduce so far. I set my keyboard layout to ruRU and put in some random cyrillic characters. Do you really think it's the locale? 
Can you check the `aowow_errors` table in your DB for more info?

> the established Russian language

...is there an unestablished russian language?

**Comment by strn-xx** [comment]
@vahzxz 
![изображение](https://github.com/Sarjuuk/aowow/assets/167621689/fcbf10dc-d9f1-4925-96b2-835b28203754)

Йоу, брат, помоги пожалуйста c mpqdata, вроде лежат в папке, но скрипт не видит. Использую те, что достал через экстрактор TrinityCore.

**Comment by Sarjuuk** [comment]
![grafik](https://github.com/Sarjuuk/aowow/assets/848030/6b2300f6-be80-4aae-9742-24f45febf107)
oh look .. its working...
