### ISSUE TITLE
There are no necessary files

### ISSUE THREAD

**Issue by vahzxz** [Sarjuuk/aowow#401]
**Describe the bug and how to reproduce it**
Numerous files required in Admin are missing

**Screenshots**
![image](https://github.com/Sarjuuk/aowow/assets/37352351/60e9b837-bb29-40a9-8c2a-d169cf5e9fcd)
![image](https://github.com/Sarjuuk/aowow/assets/37352351/707aa4ff-2cbf-40e3-a07f-c3bd8289b4f3)
![image](https://github.com/Sarjuuk/aowow/assets/37352351/67230bfb-b1cf-465f-a469-b7303a11f334)

**System:**
Mysql 5.7
PhP 8.2
Linux

**Comment by vahzxz** [comment]
> Only the following menu items are implemented. If the error occured on one of those please provide more info about how and when it occured.
> 
> * Staff / Validate
> * Staff / Refresh / < any >
> * Staff / Development / < any >
> * Staff / Content /
>   
>   * Guides awaiting aproval
>   * Screenshots
>   * Out of date Comments
>   * Featured Box - interface is missing, can be set directly in DB
>   * Oneliners - interface is missing, can be set directly in DB

Another question is, is it possible to somehow remove the requirements of NO_AUTO_CREATE_USER, the host simply does not allow this mod to be removed

Error log

Array
(
    [code] => 3090
    [message] => Changing sql mode 'NO_AUTO_CREATE_USER' is deprecated. It will be removed in a future release.
    [query] => SET SESSION sql_mode = 'NO_ENGINE_SUBSTITUTION'
    [context] => /var/www/u1859316/data/www/wow-vision.ru/aowow/includes/database.class.php line 43
)

**Comment by Sarjuuk** [comment]
Haven't seen this one before. Maybe try adding it back here:
https://github.com/Sarjuuk/aowow/blob/master/includes/database.class.php#L41-L49

```diff
        // disable STRICT_TRANS_TABLES and STRICT_ALL_TABLES off. It prevents usage of implicit default values.
        if ($idx == DB_AOWOW)
-            $interface->query("SET SESSION sql_mode = 'NO_ENGINE_SUBSTITUTION'");
+            $interface->query("SET SESSION sql_mode = 'NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER'");
        // disable ONLY_FULL_GROUP_BY (Allows for non-aggregated selects in a group-by query)
        else
-            $interface->query("SET SESSION sql_mode = ''");
+            $interface->query("SET SESSION sql_mode = 'NO_AUTO_CREATE_USER'");

        self::$interfaceCache[$idx] = &$interface;
        self::$connectionCache[$idx] = true;
```

**Comment by Sarjuuk** [comment]
if d084e6072bc4157c04ba3291a1e016e8ce38daed doesn't alleviate your problem you'll have to unset the following sql modes in you mysql config. Setting them from aowow **WILL** touch NO_AUTO_CREATE_USER and cause this error.

`'STRICT_TRANS_TABLES', 'STRICT_ALL_TABLES', 'ONLY_FULL_GROUP_BY'`

**Comment by vahzxz** [comment]
> if [d084e60](https://github.com/Sarjuuk/aowow/commit/d084e6072bc4157c04ba3291a1e016e8ce38daed) doesn't alleviate your problem you'll have to unset the following sql modes in you mysql config. Setting them from aowow **WILL** touch NO_AUTO_CREATE_USER and cause this error.
> 
> `'STRICT_TRANS_TABLES', 'STRICT_ALL_TABLES', 'ONLY_FULL_GROUP_BY'`

Everything worked) Thanks for the quickness of solving the problem)
