### ISSUE TITLE
Can't see character profile

### ISSUE THREAD

**Issue by vahzxz** [Sarjuuk/aowow#402]
**Describe the bug and how to reproduce it**
He doesn’t see the profiles of characters and guilds and asks to add them to the database, how can I do this? And to constantly update this information? As I understand it, it takes information from the AOWoW database and not from characters

**Screenshots**
![image](https://github.com/Sarjuuk/aowow/assets/37352351/01d5aa93-fddd-4099-8607-658a721a3a4b)

**System:**
 - OS: win 10
 - PHP version: 8.2
 - Mysql: 5.7
 - AzerothCore: no

**Comment by Sarjuuk** [comment]
have you tried enabling the profiler feature in the config?

**Comment by vahzxz** [comment]
> have you tried enabling the profiler feature in the config?

Yes, it is enabled. I go to show the characters, it shows all the characters created on the server, but when I open them, this error pops up. The same situation applies to Guilds

It is written in errors. Such a guild does not exist or has not yet been added to the database
