### ISSUE TITLE
Unable to open some NPCs

### ISSUE THREAD

**Issue by vahzxz** [Sarjuuk/aowow#403]
**Describe the bug and how to reproduce it**
When opening the Lich King, such an error occurs.
https://www.wowhead.com/npc=36597/the-lich-king

**Screenshots**
![image](https://github.com/Sarjuuk/aowow/assets/37352351/d2ad8d7c-ec3e-4b06-9c7b-bc21533d0303)

**System:**
 -OS: win 10
 -PHP version: 8.2
 -Mysql: 5.7
 -AzerothCore: no

**Comment by Sarjuuk** [comment]
handled more gracefully in 67d4f12cfeaf6f04dcc72e6aa3d5fa7c35a677af
