### ISSUE TITLE
Error adding video

### ISSUE THREAD

**Issue by vahzxz** [Sarjuuk/aowow#404]
**Describe the bug and how to reproduce it**
When adding a video to the NPC it gives an error

**Screenshots**
![image](https://github.com/Sarjuuk/aowow/assets/37352351/a4bf9aa7-82f3-4a28-8dd0-a1a113ee2c1f)

**System:**
-OS: win 10
-PHP version: 8.2
-Mysql: 5.7
-AzerothCore: no

**Comment by Sarjuuk** [comment]
upload Interface and moderation not yet implemented.

you can add youtube videos directly in the DB though.
