### ISSUE TITLE
DBC not found

### ISSUE THREAD

**Issue by strn-xx** [Sarjuuk/aowow#405]
Hi, I can't solve the problem with loading mpqdata. The files I got from TrinityCore extractor are in the root folder setup/mpqdata/. But for some reason the installer doesn't see them. The problem is observed both on the web server and on the local machine. Could you please tell me how to solve it?

![изображение](https://github.com/Sarjuuk/aowow/assets/167621689/482863b1-77d9-41b8-8d03-ae55553e6823)

![изображение](https://github.com/Sarjuuk/aowow/assets/167621689/99eee18f-71f0-40c0-b033-6f11016bb025)

![изображение](https://github.com/Sarjuuk/aowow/assets/167621689/daa0869d-2a59-4c5a-a976-412ee0c2435e)

**Comment by Sarjuuk** [comment]
setup expects all files in the same directory structure they had in the mpq archives. 
so: `setup/mpqdata/<localeCode>/DBFilesClient`
the locale for you is probably `enUS` or `ruRU`

see https://github.com/Sarjuuk/aowow?tab=readme-ov-file#4-extract-the-client-archives-mpqs

I don't know if the TrinityCore extractor extracs all dbc files or just the ones nessecary for the server to run. You may be missing some.

**Comment by strn-xx** [comment]
@Sarjuuk 
![изображение](https://github.com/Sarjuuk/aowow/assets/167621689/8d355341-5b3f-4cf0-b1a4-04e9020952f2)

![изображение](https://github.com/Sarjuuk/aowow/assets/167621689/e36cc12c-01bc-4d2c-aa69-d8e35c4d3f46)


I apologize for bringing the hassle, but how do you get a site up and running? Does this mean that some key files are missing, or?

**Comment by Sarjuuk** [comment]
If the setup crashed at 104/105 enable DEBUG in seiteconfig and try again.

Also, this should be a separate issue.

Also, also, highlighting me does nothing.
