### ISSUE TITLE
DB Error appearing on home page

### ISSUE THREAD

**Issue by TQPS** [Sarjuuk/aowow#406]
**Describe the bug and how to reproduce it**
The following message is appearing on the front page beginning in the top left corner since commit d084e6072bc4157c04ba3291a1e016e8ce38daed

```
DB ERROR:

Array
(
    [code] => 3135
    [message] => 'NO_ZERO_DATE', 'NO_ZERO_IN_DATE' and 'ERROR_FOR_DIVISION_BY_ZERO' sql modes should be used with strict mode. They will be merged with strict mode in a future release.
    [query] => SET SESSION sql_mode = 'NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'
    [context] => C:\Servers\WOTLK.bots\_Server\apache\htdocs\database\includes\database.class.php line 47
)
```

**Screenshots**
![image](https://github.com/Sarjuuk/aowow/assets/66294837/f82f3ce5-a086-45fe-acf3-ca405b7fe679)

**System:**
 - OS: Windows 10
 - PHP version: PHP 8.2.5 (cli) (built: Apr 12 2023 08:43:43) (ZTS Visual C++ 2019 x64)
 - revision used: 42d284dce05bea8ee5e6f3b84b22f31cf43fe22a
 - Browser (in case of JavaScript / display errors): Firefox (latest)
 - AzerothCore: no

**Comment by Sarjuuk** [comment]
i hate mysql...

probably gone in a4c15653d88b7d40512a5261238d76b0512931a9

**Comment by TQPS** [comment]
Much appreciate the fix. Thank you.
