### ISSUE TITLE
Content unavailable to players

### ISSUE THREAD

**Issue by vahzxz** [Sarjuuk/aowow#407]
**Describe the bug and how to reproduce it**
I suggest making an item in the Admin panel that allows you to hide items from users that are not available to players in the game world, so that they are displayed only to Administrators

**System:**
OS: win 10
PHP version: 8.2
Mysql: 5.7
AzerothCore: no

**Comment by Sarjuuk** [comment]
Though the admin interface is missing, every db item can already be flagged with `cuFlags |= CUSTOM_EXCLUDE_FOR_LISTVIEW` via sql query. 
The setup tries to guess what is unavailable, but there are cases where loot is set via cpp-script or items are transformed that can't be caught. 

The flagged db item can still be accessed by it's id and intentionally so.
