### ISSUE TITLE
input type=number does not accept dashes for negative numbers

### ISSUE THREAD

**Issue by vahzxz** [Sarjuuk/aowow#409]
**Describe the bug and how to reproduce it**
Searches only by nickname, does not perform a search in the second field

**Screenshots**
![image](https://github.com/Sarjuuk/aowow/assets/37352351/6c3ca375-bd64-4b4e-8d48-017c0af9b26e)
![image](https://github.com/Sarjuuk/aowow/assets/37352351/5d86932c-703d-411e-9b23-a247e1a9133f)

**System:**
 - OS: [e.g. Win10]
 - PHP version:
 - revision used:
 - Browser (in case of JavaScript / display errors):
 - AzerothCore: yes/no

**Comment by Sarjuuk** [comment]
The itemset id is negative, your input is not. 

Why does an `input[type=number]` not accept dashes? Hell if i know. For now you can click the down-arrow or copy and paste the Id

**Comment by vahzxz** [comment]
![image](https://github.com/Sarjuuk/aowow/assets/37352351/a1f12db5-436f-4ea0-b461-6ac536a61256)
Insert =,-,+ he won't let me in the water, he just ignores the ID of the set

**Comment by Sarjuuk** [comment]
can you test with bf06c418d4d5088f03793142b534296bb77de4e2 ?

**Comment by vahzxz** [comment]
> can you test with [bf06c41](https://github.com/Sarjuuk/aowow/commit/bf06c418d4d5088f03793142b534296bb77de4e2) ?

everything works, you just have to enter -72 to find it, but at the same time - you can only enter it by copying it from somewhere
![image](https://github.com/Sarjuuk/aowow/assets/37352351/b5f12741-c864-4875-a56c-e65b5b5e25c6)
