### ISSUE TITLE
PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user......

### ISSUE THREAD

**Issue by Krutok** [Sarjuuk/aowow#410]
A database connection with your script is not possible because your tool is probably buggy.
It's not my server's fault because I have installed a test script with a test to establish the database connection

```
php aowow --setup
PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'woltk'@'localhost' (using password: YES) in /var/www/vhosts/XXX/XXX/aowow/includes/libs/DbSimple/Mysqli.php:59
Stack trace:
#0 /var/www/vhosts/XXX/XXX/aowow/includes/libs/DbSimple/Mysqli.php(59): mysqli_connect()
#1 /var/www/vhosts/XXX/XXX/aowow/includes/libs/DbSimple/Generic.php(116): DbSimple_Mysqli->__construct()
#2 /var/www/vhosts/XXX/XXX/aowow/includes/database.class.php(31): DbSimple_Generic::connect()
#3 /var/www/vhosts/XXX/XXX/aowow/includes/database.class.php(136): DB::connect()
#4 /var/www/vhosts/XXX/XXX/aowow/includes/database.class.php(177): DB::safeGetDB()
#5 /var/www/vhosts/XXX/XXX/aowow/includes/kernel.php(98): DB::Aowow()
#6 /var/www/vhosts/XXX/XXX/aowow/includes/kernel.php(137): loadConfig()
#7 /var/www/vhosts/XXX/XXX/aowow/includes/shared.php(24): require_once('...')
#8 /var/www/vhosts/XXX/XXX/aowow/aowow(3): require('...')
#9 {main}
  thrown in /var/www/vhosts/XXX/XXX/aowow/includes/libs/DbSimple/Mysqli.php on line 59

Fatal error: Uncaught mysqli_sql_exception: Access denied for user 'woltk'@'localhost' (using password: YES) in /var/www/vhosts/XXX/XXX/aowow/includes/libs/DbSimple/Mysqli.php:59
Stack trace:
#0 /var/www/vhosts/XXX/XXX/aowow/includes/libs/DbSimple/Mysqli.php(59): mysqli_connect()
#1 /var/www/vhosts/XXX/XXX/aowow/includes/libs/DbSimple/Generic.php(116): DbSimple_Mysqli->__construct()
#2 /var/www/vhosts/XXX/XXX/aowow/includes/database.class.php(31): DbSimple_Generic::connect()
#3 /var/www/vhosts/XXX/XXX/aowow/includes/database.class.php(136): DB::connect()
#4 /var/www/vhosts/XXX/XXX/aowow/includes/database.class.php(177): DB::safeGetDB()
#5 /var/www/vhosts/XXX/XXX/aowow/includes/kernel.php(98): DB::Aowow()
#6 /var/www/vhosts/XXX/XXX/aowow/includes/kernel.php(137): loadConfig()
#7 /var/www/vhosts/XXX/XXX/aowow/includes/shared.php(24): require_once('...')
#8 /var/www/vhosts/XXX/XXX/aowow/aowow(3): require('...')
#9 {main}
  thrown in /var/www/vhosts/XXX/XXX/aowow/includes/libs/DbSimple/Mysqli.php on line 59
```

Testscript:

```
<?php
error_reporting(E_ALL);

define ( 'MYSQL_HOST',      'localhost' );
define ( 'MYSQL_BENUTZER',  'myuser' );
define ( 'MYSQL_KENNWORT',  'mypassword' );
define ( 'MYSQL_DATENBANK', 'aowow' );

$db_link = mysqli_connect (MYSQL_HOST,
                           MYSQL_BENUTZER,
                           MYSQL_KENNWORT,
                           MYSQL_DATENBANK);

if ( $db_link )
{
    echo 'Connection successfull';
    print_r( $db_link);
}
else
{
    die('No connection possible: ' . mysqli_error());
}
?>
```
![Screenshot 2024-05-07 121452](https://github.com/Sarjuuk/aowow/assets/47283866/394aa3af-4bc5-4ad5-a37b-5fedc4492b83)

As you can see the database connection works with my test phpscript, but with your tool I can't get a database connection

OS: Debian 12
PHP Version: 8.3.6
MySQL Server: MariaDB 10.11

**Comment by Sarjuuk** [comment]
`'woltk'@'localhost'`
wrath of lich the king

 ... sicher..?

**Comment by Sarjuuk** [comment]
> > `'woltk'@'localhost'` wrath of lich the king
> > ... sicher..?
> 
> Yes very safe and "woltk" is the database username I use the TC WoltK 3.3.5 core

![woltk](https://github.com/Sarjuuk/aowow/assets/848030/b223e466-1cb4-4289-8d3c-6601fb0b53ec)

...ganz sicher..?

**Comment by iTob191** [comment]
> #0 /var/www/vhosts/XXX/XXX/aowow/includes/libs/DbSimple/Mysqli.php(59): mysqli_connect()

In the current version of aowow there is no `mysqli_connect()` call on that line. See https://github.com/Sarjuuk/aowow/blob/937bec3d84cefdcd0b79af65904dd201cd910eee/includes/libs/DbSimple/Mysqli.php#L59 Can you try updating?

**Comment by Sarjuuk** [comment]
So you really have an egregious typo in your mysql username and can't be arsed to say: "yes, i have an egregious typo in my mysql username."

does your password contain chars that would be changed by [`urlencode()`](https://www.php.net/manual/de/function.urlencode.php)

**Comment by Sarjuuk** [comment]
not all special chars would trigger urlencode. Be more speciffic or just remove the function call for yourself.

https://github.com/Sarjuuk/aowow/blob/master/includes/database.class.php#L21

**Comment by Sarjuuk** [comment]
I pointed you at the probable cause of your issues and instead of confirming whether urlencode is the issue you chose to use an insecure password. 

Yeah, i'm done.
