### ISSUE TITLE
Not a bug, just a question about the SmartAI dropdown menu

### ISSUE THREAD

**Issue by Thor1423** [Sarjuuk/aowow#412]
Is there a way to hide or remove the SmartAI window?
Since many custom NPCS story elements contain elements, I don't want you to read through them beforehand

![Screenshot 2024-05-12 095748](https://github.com/Sarjuuk/aowow/assets/169218249/06276b66-0aa0-4c30-86ee-1b60aafb649d)

**Comment by Sarjuuk** [comment]
deleting or commenting these blocks here removes them for this page.
https://github.com/Sarjuuk/aowow/blob/c87178c7919c268f5f26d88f847ec49658024ac3/pages/npc.php#L376-L395
https://github.com/Sarjuuk/aowow/blob/c87178c7919c268f5f26d88f847ec49658024ac3/pages/object.php#L248-L267

alternatvely if you just want the toggle to start closed, edit:
https://github.com/Sarjuuk/aowow/blob/c87178c7919c268f5f26d88f847ec49658024ac3/includes/smartAI.class.php#L447
```diff
-        $return = '[style]#text-generic .grid { clear:left; } #text-generic .tabbed-contents { padding:0px; clear:left; }[/style][pad][h3][toggler id=sai]SmartAI'.(!empty($this->miscData['title']) ? $this->miscData['title'] : null).'[/toggler][/h3][div id=sai clear=left]%s[/div]';
+        $return = '[style]#text-generic .grid { clear:left; } #text-generic .tabbed-contents { padding:0px; clear:left; }[/style][pad][h3][toggler=hidden id=sai]SmartAI'.(!empty($this->miscData['title']) ? $this->miscData['title'] : null).'[/toggler][/h3][div=hidden id=sai clear=left]%s[/div]';
```

**Comment by Thor1423** [comment]
thank you :-)
