### ISSUE TITLE
MySQL 8.4

### ISSUE THREAD

**Issue by jackpoz** [Sarjuuk/aowow#413]
**Describe the bug and how to reproduce it**
Upgrading to MySQL 8.4 showed this warning during the upgrade process:

Foreign key 'FK_acc_weightscales' on table 'aowow'.'aowow_account_weightscales' refers to non-unique key or partial key. This is deprecated and will be removed in a future release.
Deprecated 'foreign key referring to a non-unique or partial key' used 1 times, last time used 'during upgrade'.

This showed up in the .err file which is located by default in the /data directory of MySQL.

**Screenshots**
No screenshot available

**System:**
 - OS: Windows 10
 - MySQL 8.4

**Comment by Sarjuuk** [comment]
aowow_account_weightscale_data's `FK_acc_weightscales` REFERENCES `aowow_account_weightscales` (`id`) 
but aowow_account_weightscales PRIMARY KEY  is (`id`,`userId`)

.. why tho..?

**Comment by Sarjuuk** [comment]
probably fixed in 7d5930865ca2348ba454ea401f1cd7ef3f269984

feel free to reopen if not.
