### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by vahzxz** [Sarjuuk/aowow#419]
**Describe the bug and how to reproduce it**
An error occurred when logging into the database
![image](https://github.com/Sarjuuk/aowow/assets/37352351/f4bf11a4-ad86-40d3-a7d3-7b6c27953517)

**System:**
OS: win 10
PHP version: 8.2
Mysql: 5.7
AzerothCore: no

**Comment by Sarjuuk** [comment]
[setup/updates/1717076299_01.sql](https://github.com/Sarjuuk/aowow/blob/master/setup/updates/1717076299_01.sql) needs to be applied .. manually.

the updater can't apply it, because it already expects the updated structure. 

No clue how to circumvent that.

**Comment by vahzxz** [comment]
> [setup/updates/1717076299_01.sql](https://github.com/Sarjuuk/aowow/blob/master/setup/updates/1717076299_01.sql) needs to be applied .. manually.
> 
> it can't be applied by the updater, because it already expects the updated structure and crashes.
> 
> No clue how to circumvent that circular logic.

Thanks) It helped)
