### ISSUE TITLE
Problems with translation

### ISSUE THREAD

**Issue by vahzxz** [Sarjuuk/aowow#420]
**Describe the bug and how to reproduce it**
Hello, everyone. Russian Russian translation I translated almost the entire table of the article into Russian and indicated that the article is also for Russian. And when you log in, the system also shows that this article is available only in English

**Screenshots**
![image](https://github.com/Sarjuuk/aowow/assets/37352351/a28210bc-7454-4db2-b806-374c408d4ae4)
![image](https://github.com/Sarjuuk/aowow/assets/37352351/9613bff8-4197-4782-98f3-077d936ebe74)

**System:**
OS: win 10
PHP version: 8.2
Mysql: 5.7
AzerothCore: no

**Comment by Sarjuuk** [comment]
hm, should work.

can you check the footer of the page if it's cached? You need to be logged in as admin.

![grafik](https://github.com/Sarjuuk/aowow/assets/848030/1bd2f929-979a-41a8-8ede-8016d1d50637)

**Comment by vahzxz** [comment]
> hm, should work.
> 
> can you check the footer of the page if it's cached? You need to be logged in as admin.
> 
> ![grafik](https://private-user-images.githubusercontent.com/848030/336181215-1bd2f929-979a-41a8-8ede-8016d1d50637.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0ODA0OTMsIm5iZiI6MTcxNzQ4MDE5MywicGF0aCI6Ii84NDgwMzAvMzM2MTgxMjE1LTFiZDJmOTI5LTk3OWEtNDFhOC04ZWRlLTgwMTZkMWQ1MDYzNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNFQwNTQ5NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMDdjMDhiYmYwYmNlY2JkMzMwMDhjYzRiZDJjOGJiMGQyNDZlNWU0MWVjM2RiODQ0ZTRjMjE5ZGZlMTVmNmY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mFfy-5PavV78agOjBCzmXwtfrx9cOjazla1rEWjOrJo)

![image](https://github.com/Sarjuuk/aowow/assets/37352351/2b96fb8f-8db5-4175-a1d6-099199d40de7)
![image](https://github.com/Sarjuuk/aowow/assets/37352351/fee9b3ad-70e5-478b-9046-d40c0bbb37bc)
![image](https://github.com/Sarjuuk/aowow/assets/37352351/c4af66b6-6bab-437c-83bc-ec889ddc29e8)
