### ISSUE TITLE
Building AOwow DB

### ISSUE THREAD

**Issue by Cyberfren** [Sarjuuk/aowow#422]
Sorry if this is the wrong template, first time posting on Github for something.

I am at the stage where I am using the CLI to run the MPQdata and get it inserted into the DB.  Do i need to use the MPQExtractor to get the files out of my Client?  I have tried putting the required files in every possible directory order and using any feasible folder name.  I have read the code and I can't figure out what I am doing wrong.  I have put them in a actual MPQ too.  Tried every directory pattern for about 3 hours straight.  I didn't use the CLI tool because i couldn't get it to pull anything besides the DBCs.

I tried to put the DBCs in but it can't seem to find the areatrigger.dbc or some error about it being a problem.  Can you give me a screen shot of the exact directory order it goes into?
>mpqdata/enUS/Interface
>mpqdata/LOCALE_EN/enUS/Interface
>mpqdata/enUS/archive.mpq
all lower case, all captials, and like 20 other variations.  I can't get past the first dbc.

I think this project looks amazing and I would love to use it.  English is not my first language, can you please give me better directions?  Thank you!

**Comment by jzizka91** [comment]
Hi. 

I've also struggled with setting up the app. This is the`mpqdata` structure that worked for me.

```
mpqdata
└── enUS
    ├── dbfilesclient
    ├── interface
    │   ├── calendar
    │   ├── flavorimages
    │   ├── framexml
    │   ├── glues
    │   ├── icons
    │   ├── paperdoll
    │   ├── pictures
    │   ├── pvpframe
    │   ├── pvprankbadges
    │   ├── spellbook
    │   ├── talentframe
    │   └── worldmap
    └── sound
        ├── cinematicvoices
        ├── creature
        └── music
```

* You can use this [Extractor](https://github.com/iTob191/aowow-extractor) script (docker image)  to extract all MPQ files to get the necessary files/structure.
 * To get `mpqdata/enUS/interface/glues/credits` data (which is [mentioned](https://github.com/Sarjuuk/aowow?tab=readme-ov-file#4-extract-the-client-archives-mpqs) in the usage guide) you'll need to modify Extractor [script](https://github.com/iTob191/aowow-extractor/blob/8b70508e9d2f832a9eacbe50dbc822c42907c68c/scripts/extract_mpq.sh#L29). Simply add a new line `"interface\\glues\\credits\\*.blp"` and run the docker container.

To get the necessary files/structure with using the Extractor you'll need these files from the 3.3.5 client.

```
locale-enUS.MPQ
expansion-locale-enUS.MPQ
lichking-locale-enUS.MPQ
patch-enUS.MPQ
patch-enUS-2.MPQ
patch-enUS-3.MPQ
```

**Comment by Cyberfren** [comment]
Thank you so much!

**Comment by Sarjuuk** [comment]
@jzizka91 is generally correct, though he missed the archives relevant for sound files in:
language agnostic (background music, sound effects)
* Data/common.mpq
* Data/expansion.mpq
* Data/lichking.mpq
* patch(-X).mpq

localized (speech)
* Data/enUS/(\<exp>-)speech-enUS.mpq

`enUS` as a standin for whatever your locale is.

Just be sure to maintain the patch order. It's especially relevant for the dbc tables as they change structure a couple of time.

**Comment by jzizka91** [comment]
Indeed I missed the sound files. Thanks for pointing that out.
