### ISSUE TITLE
Question: Non-interactive setup

### ISSUE THREAD

**Issue by jzizka91** [Sarjuuk/aowow#425]
Hi.

Just a question. Is it possible to run the `php aowow --setup` in a non-interactively mode or would it be possible to implement it? It would be useful for automatic deployments.

**System:**
 - OS: Ubuntu 24.04
 - PHP version: 8.3
 - revision used: -
 - Browser (in case of JavaScript / display errors): -
 - AzerothCore: no

**Comment by Sarjuuk** [comment]
That's not something i've considered so far. And at least for now i don't think wil implement.

But there are only a couple of steps that actually require user input, though generally if there is any error there will be a prompt.

https://github.com/Sarjuuk/aowow/blob/615c203c7a89176b5da977a87bd680e57162f6e7/setup/tools/clisetup/setup.us.php#L28-L35
You'd need to comment:
* database: you'd have to generate `/config/config.php` yourself in advance.
* configure: setting `site_host` and `static_host`. They can each be done as oneliner: `./aowow -c e site_host myhost.com` in advance
* account:  also a oneliner command: `./aowow -a user pass email` you need to set an email or you'll get prompted for one.

And barring any errors it should run without user input.

**Comment by iTob191** [comment]
I think it's already possible to a reasonable degree. The most interactive steps are the first 2 (db and site config). You can skip those by creating a file `cache/setup/firstrun` with contents
```
37
2
```
and calling the setup like `printf "y" | php aowow --setup`. As sarjuuk has mentioned, this requires that you provide the database config file (`config/config.php`) and apply the needed database changes for site configuration yourself. With the recent changes in 10de3206167089a985dbfee9999469bbd86cc23c, the setup will no longer hang if user input is required when running in a non-interactive environment.

Info: `37` is the [current aowow revision](https://github.com/Sarjuuk/aowow/blob/615c203c7a89176b5da977a87bd680e57162f6e7/includes/kernel.php#L6) at the time of writing. If you try this at a later time you may need to update the number.

**Comment by jzizka91** [comment]
Alright, I'll take a look. Thanks.
