### ISSUE TITLE
Setup is unable to find DBC files.

### ISSUE THREAD

**Issue by Ikatzuki** [Sarjuuk/aowow#430]
**Describe the bug and how to reproduce it**
I'm trying to run the setup file but it seems to be unable to find any DBC files. I've extracted all the required game files and put them inside of the setup/mpqdata/ folder (i.e: setup/mpqdata/DBFilesClient/Achievement_Criteria.dbc)

This exact same setup works fine on my Ubuntu machine and finds the DBC files just fine but on my Win11 computer, it's unable to find any of them. Any help would be greatly appreciated, tyvm!

```
16:42:08          [setup] resuming from step 3...
16:42:09          [setup] step 3 / 79
16:42:09          [sql] filling aowow_achievementcriteria with data
16:42:09          [sql] copying achievement_criteria.dbc into aowow_achievementcriteria
16:42:11  [INFO]  indexing game data from setup/mpqdata/ for first time use... done!
16:42:11  [ERR]   no suitable files found for achievement_criteria.dbc, aborting.
16:42:11  [ERR]   [sql] subscript 'achievementcriteria' returned with errors
```

**System:**
 - OS: Win11
 - PHP version: 8.0.30
 - revision used: Latest

**Comment by virgo77** [comment]
Hi!
Your extraction is not good. ALL the locale extraction must be in a locale folder:
- `setup/mpqdata/enUS/DBFilesClient/Achievement_Criteria.dbc`
- `setup/mpqdata/frFR/DBFilesClient/Achievement_Criteria.dbc`
- `setup/mpqdata/deDE/DBFilesClient/Achievement_Criteria.dbc`
- etc.

Like this:
![image](https://github.com/Sarjuuk/aowow/assets/23108339/9153b351-dd7b-4080-b557-a8910214959f)

I suggest you to do extractions like this:
- as you are under Windows, you may use MPQEditor. This one should create a .\Work folder
- so, extract all the WoW Client .\Data MPQ files first
- then, create a folder named mpqdata and move all your folders and files into it
- next, extract your locale MPQ files
- then create a folder names as your locale (enUS, frFR, deDE, etc.)
- and move your files inside
- lastly, move your locale folder inside the mpqdata

You may have to convert again your sounds.

Good luck! :)

Regards,
V.

**Comment by Sarjuuk** [comment]
Nah, he is correct. Even when you apply the localeCode to your mpqdata path it will not be found. (But yeah, you should apply it anayway)

I'm still liberally applying DIRECTORY_SEPARATOR constants until the problem goes away.

**Comment by virgo77** [comment]
> Nah, he is correct. Even when you apply the localeCode to your mpqdata path it will not be found. (But yeah, you should apply it anayway)
> 
> I'm still liberally applying DIRECTORY_SEPARATOR constants until the problem goes away.

oki doki, I wasn't aware of that. But what about multiple locales? You just can't put EN/FR/DE in the mpqdata folder as files could be replaced? I'm wondering... or I did not understand your explaination :)

**Comment by Sarjuuk** [comment]
You are right, this will not work. It's a failsafe for single language users that skipped over that part in the readme.
It will be assigned enus regardless of the files you put there. 

Anyway, should work under WIN again.
