### ISSUE TITLE
Show created item in profession spell list

### ISSUE THREAD

**Issue by Marty** [Sarjuuk/aowow#432]
**Describe the bug and how to reproduce it**
In the list of spells of a profession it shows only the "creating spell" on the spell name, as well as the spell icon.
On wowhead, the icon shows the item and the name shows the spell.

This would make browsing a professions spells much easier.

**Screenshots**
turtle wow database
![grafik](https://github.com/user-attachments/assets/c085bb52-ca03-4282-914f-e1e2e0eae7d1)
![grafik](https://github.com/user-attachments/assets/525aec39-1da3-4477-91f6-f5d641d47ff6)
wowhead
![grafik](https://github.com/user-attachments/assets/10b9432c-a62a-4b87-b000-83c50e3002f7)

**System:**
Seen on turtle wow database. It says it's based on aowow, I hope this is the right spot to address this.

Greetings from a fellow dtwow player :)

**Comment by Sarjuuk** [comment]
TurtleWoW uses the aowow base I started of from over a decade ago. (time isn't real, time can't hurt you)

At this point there is barely anything in common between the two versions.

see: https://aowow.trinitycore.info/?spells=9.185

> Greetings from a fellow dtwow player :)

Oh, really :D
