### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Hoyung** [Sarjuuk/aowow#44]
**Sorry, I'm a rookie.
I can't understand the fifth of the installation section.
Can u tell me the detail.**

5 .compile the MPQExtractor （im a win user , so i use MPQEditor directly）
extract the **following directories** (where are directories,can u tell me which directory or which file ？ ) from **the client**(do u mean The World of Warcraft v3.3.5 Client?) archives into **setup/mpqdata/**（do u mean the aowow folder which i have cloned.=aowow/setup/mpqdata）, while maintaining patch order (suffix: 1 -> 9 -> A -> Z)
.. for every locale you are going to use:*
```
<localeCode>/DBFilesClient/
<localeCode>/Interface/WorldMap/
<localeCode>/Interface/FrameXML/GlobalStrings.lua
```
- [x] I cant understand **localeCode** mean,Maybe it's because I didn't finish the extract step.
 
.. once is enough (still apply the localeCode though):
```
<localeCode>/Interface/TalentFrame/
<localeCode>/Interface/Glues/Credits/
<localeCode>/Interface/Icons/
<localeCode>/Interface/Spellbook/
<localeCode>/Interface/PaperDoll/
<localeCode>/Interface/GLUES/CHARACTERCREATE/
<localeCode>/Interface/Pictures
<localeCode>/Interface/PvPRankBadges
<localeCode>/Interface/FlavorImages
<localeCode>/Interface/Calendar/Holidays/
```
 .. optionaly (for other uses):
```
<localeCode>/Interface/GLUES/LOADINGSCREENS/
```

:sparkles:Forgive my ignorance and bother ! Please tell me the detail ! thx a lot ! :sparkles:

**Comment by Sarjuuk** [comment]
* the direcories (or paths (or folders)) within the mpq-archives were listed below.  Usable localeCodes are  **enUS, frFR, deDE, esES, ruRU**
(also **enGB** and **esMX** are mapped to the former ones)
* yes from the WoW 3.3.5 client
* yes into the cloned aowow folder

if you are using a chinese client (**enCN** or **zhCN**) you are out of luck. sorry..

**Comment by Hoyung** [comment]
Thx. Now Im downloading the enUS version wow client. until then i will tell u detail

**Comment by Hoyung** [comment]
I did the following steps（WIN user without World of Warcraft v3.3.5 private server install. ):
1, copy aowow foder to D:\xampp\htdocs\aowow
2, Created a new database named 'aowow'. then `mysql -p aowow < setup/db_structure.sql` done
3, Created a new database named 'world'. then `mysql -p aowow < TDB_full_world_335.60.sql` done
4, extract the following directories from the client archives into setup/mpqdata/.......like this
* aowow\setup\mpqdata\locale-enUS
  * DBFilesClient
  * Interface
     * FlavorImages
     * FrameXML
     * GLUES
     * Icons
     * PaperDoll
     * Pictures
     * PvPRankBadges
     * Spellbook
     * TALENTFRAME
     * WORLDMAP
* aowow\setup\mpqdata\expansion-locale-enUS
  * Interface
     * GLUES
     * Icons
* aowow\setup\mpqdata\lichking-locale-enUS
  * Interface
     * Icons
* aowow\setup\mpqdata\patch-enUS
  * DBFilesClient
  * Interface
     * Calendar
     * FrameXML
     * GLUES
     * Icons
     * Spellbook
     * TALENTFRAME
     * WORLDMAP
* aowow\setup\mpqdata\patch-enUS-2    ~omit
* aowow\setup\mpqdata\patch-enUS-3    ~omit

5, run the initial setup from the CLI `php aowow --firstrun`.
```
PHP 5.5.30 (cli) (built: Sep 30 2015 13:50:53)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies

D:\xampp\htdocs\aowow>php aowow --firstrun

17:18:04          FileGen::init() - creating required directories
17:18:04          created 7 extra paths

17:18:04          Please enter your database credentials.

Press any key to continue:
```
:sparkles: so I pressed the enter button.
```
17:18:05     select a numerical index to use the corresponding entry
17:18:05     [0] aowow          OK    mysqli://root:@127.0.0.1/aowow  table prefix: aowow
17:18:05     [1] world          OK    mysqli://root:@127.0.0.1/world
17:18:05     [2] auth           OK    mysqli://root:@127.0.0.1/auth
17:18:05     [3] characters [0]     OK    mysqli://root:@127.0.0.1/characters
17:18:05     [4] characters [1]     OK    mysqli://root:@127.0.0.1/characters
17:18:05     [5] add an additional Character DB
```
:sparkles:If I choose “5”, then there will be a “6” more, how should I end this step?
:sparkles:So there is no way, I press the Enter key, the bad results came out,
```
17:18:24  [INFO]  db setup aborted
17:18:24          SITE_HOST and STATIC_HOST must be set. Also enable FORCE_SSL i
f needed. You may also want to change other variables such as NAME, NAME_SHORT O
R LOCALES.

Press any key to continue:
```
Can you tell me the wrong place, and I found that the Install chapter does not mention the use of BLPConverter, as a necessary tool, BLPConverter will be used in which step?

thx!
（My English is so terrible.）

**Comment by Sarjuuk** [comment]
1. ok
2. ok
3. um, according to the query you've put the world tables into the aowow-db. This is not critical, as long as you set up the connection for the world DB to use the aowow DB.
4. no, just `mpqdata\enUS\` (thats why the patches may overwrite base files)
5. [0] aowow and [1] world are required. [2] is only needed if you wan to log in using wow-accounts (which does not apply to you `WIN user without World of Warcraft v3.3.5 private server install.`). [3+] characters can be omitted, since this is only needed for the profiler which is NYI.
just continue from there.

the BLPConverter is not *required* but if some of the images you will extract look weired, you can convert them using this tool. You probably won't need it.

**Comment by Hoyung** [comment]
Sorry for my type error:
3, 
Created a new database named 'world'. then mysql -p world < TDB_full_world_335.60.sql done

that's what I did, sorry for my type error.
4,
Yes, just mpqdata\enUS\ 
then the DBFilesClient foder from the patch-enUS.mpq will overwrite the DBFilesClient foder from the locale-enUS.mpq.
finally...
* aowow\setup\mpqdata\enUS
  * DBFilesClient(from patch-enUS.mpq)
  * Interface(from mpq_files together)
     * FlavorImages
     * FrameXML
     * GLUES
     * Icons
     * PaperDoll
     * Pictures
     * PvPRankBadges
     * Spellbook
     * TALENTFRAME
     * WORLDMAP

so until now, does everything right?

**Comment by Sarjuuk** [comment]
the table prefix requires an underscore 

**aowow** => **aowow_**

**Comment by Hoyung** [comment]
Thank you for all your help, I will continue to take time to finish it.
