### ISSUE TITLE
not support zhCN and zhTW?

### ISSUE THREAD

**Issue by qyh214** [Sarjuuk/aowow#46]
see local and some codes
no zhcn and zhtw support?can you add it?

**Comment by Sarjuuk** [comment]
My answer is basicly the same as for #45 
Except, said site uses CN, so you could build on top of that.

**Comment by qyh214** [comment]
In #45 
you say 
But if you do, there is also the comparatively minor hassle of registering the new locale, adding an additional locale-field to he affected tables, updating the setup to search for these DBC-fields and strings in TrinityCores DB, etc.
so
can you introduce what documents are involved, ,and  I try to deal with, because now TC has eight language data

**Comment by Sarjuuk** [comment]
this should cover the code part
https://gist.github.com/Sarjuuk/5ae005d53a6ae5307568

whats missing
- [ ] localized aowow-tables will need an additional *_loc4 field
- [ ] `localization/locale_zhcn.php`
- [ ] `template/localized/contrib_4.tpl.php`
- [ ] `static/js/locale_zhcn.js`
- [ ] `static/css/locale_zhcn.css` and linked imagery

**Comment by qyh214** [comment]
I have a simple test
dbc convert well,db from tc world db and merge convert well
but some bugs:
1.dbc_achievement have data but aowow_achievement is nothing
2.in web although has zhcn but choose it and web refresh but also is enus
if choose other language ,shows well

**Comment by Sarjuuk** [comment]
1) I cannot test as i do not have a chinese client. I guess, you forgot to delete he dbc_* tables, that were generated previously
2) I overlooked a check in ìncludes/ajaxHandler.class.php` I've updated the gist with the change

**Comment by qyh214** [comment]
1) dbc_achievement only has CN data,convert from dbc seems well,but can not merge to aowow_achievment.
this is my dbc_achievement.sql 
[dbc_achievement.zip](https://github.com/Sarjuuk/aowow/files/76454/dbc_achievement.zip)
2) work now!
and new issue:
tooltip:like quest,spell,item shows English or name is BLANK.

**Comment by Sarjuuk** [comment]
1) Have you enabled CN in your config? The setup only looks for locales it is told to use and CN is new.
add 0x10 to the locales variable or reapply the `setup/db_structure.sql` (was updated by the patch)

3) is to be expected if the required strings are missing.

In any case it may be helpful if you could send me the full set of dbcs.

**Comment by qyh214** [comment]
now my aowow_config -locale value is 349 cat 2 flag 169
I have enUS and zhCN wow client
and now there are two major issues:
1)tooltip:quest,item,npc,spell
for example 
url is  /db/?quests=10.3537
![qq 20160104195337](https://cloud.githubusercontent.com/assets/3896160/12089488/4493a860-b320-11e5-8999-c14b3f42eb01.png)
you can see cn can be shown but tooltip is english,if you click it into
for example 
url is /db/?quest=11611
![qq 20160104195350](https://cloud.githubusercontent.com/assets/3896160/12089507/6e52d3f6-b320-11e5-8c09-125c04399b1e.png)
you can see all are CN,so tooltip has wrong can not show cn.

2)aowow_achievement,aowow_itemset is empty but dbc_*  have data,I give you all 335 cn dbc for you test.
[dbc335zhCN.zip](https://github.com/Sarjuuk/aowow/files/77175/dbc335zhCN.zip)

**Comment by Sarjuuk** [comment]
Updated the gist once again. This should fix the tooltips, achievements and itemsets.

How are the translations coming along?

**Comment by qyh214** [comment]
thanks!
and
achievement 
why your site is:
![qq 20160106222655](https://cloud.githubusercontent.com/assets/3896160/12144716/a354df9a-b4c4-11e5-9180-e8a288dc81a6.png)
but me
![qq 20160106222709](https://cloud.githubusercontent.com/assets/3896160/12144724/aa07675e-b4c4-11e5-8382-bad820aa7b25.png)
 only a little..........

about translate ,
I invited a few good friends, together with the translation, but the translation in large quantity, we usually have to busy, so they try to hurry up good translation and I check it and will submit the merger request, when the time comes for you to check.

**Comment by Sarjuuk** [comment]
This is not the site i actively develop on. It's the 'working presentation'.
But it looks like you encountered some sort of javascript error. Impossible to say what happened from the screenshot alone.

also you can probably use this as a basis: http://static.wowhead.com/js/locale_zhcn.js

**Comment by qyh214** [comment]
maybe javascript error
but I don't know why cause it
I see global.js wrong ,use firefox F10 dev tool

**Comment by Sarjuuk** [comment]
and thats why you usually post the occurring error and/or the pages source via paste or gist or something

**Comment by qyh214** [comment]
I have updated my comment

**Comment by Sarjuuk** [comment]
this is probably called from here [global.js#14468](https://github.com/Sarjuuk/aowow/blob/master/static/js/global.js#L14468) (since in the screenshot, the "Side" field is the first not being generated)
that would mean, that `g_sides` (which is in `static/js/locale_zhcn.js`, which you need to translate) either has no data or `achievement.side` is wrong (improbable, the related functions haven't been touched in ages).

Still, i wouldn't need to guess all that often, if you'd provide sensible information about these errors.

**Comment by qyh214** [comment]
I give your my aowow_achievement_* 3 tables db sql for you test

[my_db_aowow_achievement.zip](https://github.com/Sarjuuk/aowow/files/88924/my_db_aowow_achievement.zip)

and locale js maybe not an issue? I copy enus.js and rename it to zhcn.js for quickly test

now translation are On going!

**Comment by Sarjuuk** [comment]
When unpacking your DBCs, your integers appear to not be read as expected.
It's not totally unexpected though. 
* [Try changing the unpack-format in this line as the comment suggests (V => l)](https://github.com/Sarjuuk/aowow/blob/master/setup/tools/dbc.class.php#L435)
* clear your aowow-database and regenerate it using `php aowow --sql` (without any parameter)
* see if the data displayed makes sense (on all pages)

**Comment by qyh214** [comment]
I have done it but achievement page also wrong
and my system is win 7 x64 and CN language.
could I give your my all aowow_db?

**Comment by Sarjuuk** [comment]
i've committed the changes to the extractor 278176a48eb45a6921bce60c5f0c4c6955cba6fa

as the error occurs either while extracting the dbcs or moving the extracted data from the (temporary) dbc_* tables to the aowow_* tables, please do the following.
* delete the affected dbc-tables and truncate the aowow- ones

    ```
DROP TABLE IF EXISTS dbc_achievement_category, dbc_achievement;
TRUNCATE aowow_achievement;
```
* regenerate the data using
    `php aowow --sql=achievement`
* report back the values returned by those queries
    
    ```
SELECT faction, map, 0 FROM dbc_achievement WHERE Id = 457 UNION
SELECT faction, map, parentCat FROM aowow_achievement WHERE id = 457;
```

expected returns are

-1 | -1 |  0
------------ | ------------- | -------------
3 | -1 | -1

**Comment by qyh214** [comment]
yes!now returns are true now
