### ISSUE TITLE
Achievements page issue

### ISSUE THREAD

**Issue by Hoyung** [Sarjuuk/aowow#47]
Some achievements pages display nothing.
![Image of 1](https://raw.githubusercontent.com/Hoyung/AOWOWISSUES/4e3562499e8e9fb23c4be7ca1e54d48989d7a0f0/images/1.jpg)
but
![Image of 2](https://raw.githubusercontent.com/Hoyung/AOWOWISSUES/4e3562499e8e9fb23c4be7ca1e54d48989d7a0f0/images/2.jpg)
errors comes out here i think !
![Image of 3](https://raw.githubusercontent.com/Hoyung/AOWOWISSUES/4e3562499e8e9fb23c4be7ca1e54d48989d7a0f0/images/3.jpg)

**Comment by Sarjuuk** [comment]
i've never seen somthing linke this.

please dump the pages source somewhere, as the error probably lies somewhere in the listview-javascript on the page itself
