### ISSUE TITLE
how to use 3dmodelviewer

### ISSUE THREAD

**Issue by qyh214** [Sarjuuk/aowow#50]
Now wlll meet loading error

**Comment by Sarjuuk** [comment]
in `static/js/global.js` exchange the comments on line 19249/19250 and 19268/19269

**Comment by qyh214** [comment]
In fact, I would like to know how to convert them from client, using own data independent of wowhead
like your site

**Comment by Sarjuuk** [comment]
I never had a way to create the models myself. 
In theory you could could get the textures yourself using the blpconverter.

anyway, i'd configure my server to redirect to a small php-script for 404-requests on the path /modelviewer.
the script would fetch that file from WH, save a copy of it for future use and do a fpassthru()

**Comment by qyh214** [comment]
oh!~ok!~thanks
