### ISSUE TITLE
Shields block value incorrect 

### ISSUE THREAD

**Issue by Endalaust** [Sarjuuk/aowow#51]
Hello

Shields block value is incorrect:
http://woehead.way-of-elendil.fr/?item=28606 you can see "Block: 42" (line 5) but it's a duplicate of equipment spell. If you check item ingame, stat is different: https://lut.im/scdUKdpArJ/ALaoDTXaIJEBuIG2.png (Block: 122). 

Ty

**Comment by Sarjuuk** [comment]
Hm, right, should probably add up.

**Comment by Sarjuuk** [comment]
should be fixed in 432223264e34452543c0053403dd5669efd3a043
