### ISSUE TITLE
limit  three characters to auth

### ISSUE THREAD

**Issue by Endalaust** [Sarjuuk/aowow#57]
It's 3 minimum characters to create an account on WoW, and not 4. Users who have small user account can not auth on aowow :)
https://github.com/Sarjuuk/aowow/blob/master/includes/user.class.php#L370

**Comment by Sarjuuk** [comment]
char limit was predefined in javascript. 
hm..

also need to check name max length and password restrictions, while at it..

**Comment by Sarjuuk** [comment]
fixed in a52193593491de7e649e68d3ef4597f36a65244a
