### ISSUE TITLE
firstrun fails

### ISSUE THREAD

**Issue by dawnstrider** [Sarjuuk/aowow#59]
Commit: 8f777745698b093ae7bbea699d63cce636c69689

Problem: After setting up the DB schema and importing the SQL file, the command 
> php aowo --firstrun

fails with the following output:

> 09:17:56  [INFO]  site configuration aborted
> 09:17:56          SqlGen::generate() - copying achievement_category.dbc into aowow_achievementcategory
> 
> 09:17:56          reading MPQdata from setup/mpqdata/ to list for first time use...
> 09:17:56          done
> 
> 
> [c]ontinue anyway? [r]etry? [a]bort?:

Is there a way to increase debugging output? I cannot see whats wrong. Maybe it has to do with the latest changes in the DB structure file?

**Comment by Sarjuuk** [comment]
it should tell you what went wrong. 
judging from the time it took to read MPQdata, it was not found.

i'll have to check that.

**Comment by dawnstrider** [comment]
Nevermind. I used

> php aowow --delete

and then

> php aowow --firstrun

and it seems to work now. More logging would be nice but this is not part of this issue.
