### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Tangol** [Sarjuuk/aowow#6]
Hello,
Can you please provide a detailed installation guide in the README?

I've tried installing this but i get the following error:
![error](https://cloud.githubusercontent.com/assets/3336728/3707914/85cb82c4-143b-11e4-822b-3839c13858a7.png)
I'm using Apache: 2.4.9 
MySQL: 5.6.17 
PHP: 5.5.12
And i did the following steps:
1. Cloned the repo.
2. Uploaded the files in my www folder.
3. Created a new database named 'aowow'.
4. Went to the folder config and removed the .in extension from every file.
5. Edited the config.php with the required info.
6. Extracted db_setup_1.zip, db_setup_2.zip, db_setup_3.zip, db_content.rar .
7. Run the above databases + the config.sql, in my previous created 'aowow' db.

Also the actual website doesn't contain any info. I'm getting "There is no data to display."

So if you could post a detailed install guide we'll forever be in your debt.
Thanks!

**Comment by Asandru** [comment]
wamp sucks..
