### ISSUE TITLE
limit the custom items,npc etc?

### ISSUE THREAD

**Issue by qyh214** [Sarjuuk/aowow#62]
If I have added new custom npc items,can it be shown?
and If do some related restrictions, how to remove this restriction or how to add support for custom items,npc

**Comment by kep123** [comment]
这个网站怎么弄啊？我架设不了……求助 我给你发过邮件你没回复！

**Comment by kep123** [comment]
你好，能帮忙指导下如何安装这个网站麽？一直出现#61 的问题！

**Comment by Endalaust** [comment]
just update your db : 
php aowow --sql
