### ISSUE TITLE
importing quests from world database fail

### ISSUE THREAD

**Issue by Fra298** [Sarjuuk/aowow#68]
As said in tittle, importaing quests from trinity database does not seem to work for me.
See log details : 

`06:37:11           * sets 193588 - 195403
06:37:11           * sets 195404 - 300205
06:37:12  [OK]     - subscript 'objects' returned sucessfully
06:37:12          SqlGen::generate() - filling aowow_pet with data
06:37:13  [OK]     - subscript 'pet' returned sucessfully
06:37:13          SqlGen::generate() - filling aowow_quests with data
06:37:13           * sets 1 - 
06:37:14           * sets 1 - 
06:37:15           * sets 1 - 
06:37:16           * sets 1 - 
06:37:17           * sets 1 - `

the *sets 1 - seems to be an endless loop...

**Comment by Sarjuuk** [comment]
https://github.com/Sarjuuk/aowow/commit/321c9ba7f4125bb035786d82e1bb27d6c3cf9f6a#commitcomment-19559675

sorry :/

**Comment by Sarjuuk** [comment]
changed in e896daa148e246349903c9b51287085884528890

thank you
