### ISSUE TITLE
setup crash on glyphs data generation

### ISSUE THREAD

**Issue by Fra298** [Sarjuuk/aowow#69]
```
Aowow --firstrun ends on glyphs data generation. Here's the log : 
```

`08:37:05          FileGen::init() - creating required directories
08:37:05          created 7 extra paths

08:37:05  [INFO]  Found firstrun progression info. (Halted on subscript glyphs)

08:37:07          Resuming setup from step 62...
08:37:08          FileGen::generate() - gathering data for glyphs
`

according to php error log it's a memory problem : 
`[26-Oct-2016 08:12:17 Europe/Berlin] PHP Fatal error:  Out of memory (allocated 1514143744) (tried to allocate 16384 bytes) in C:\xampp\htdocs\aowow\includes\libs\DbSimple\Database.php on line 1024`

I increased memory_limit in my php.ini up to 4096M but error still occurs... Any idea?

**Comment by Sarjuuk** [comment]
Aowow selbst sollte 2GB voreingestellt haben, aber 1514143744b sind 1.4GB? 
4GB sollten eigentlich mehr als ausreichend sein.

Versuch mal den Wert per `--siteconfig` oder direkt im table `aowow_config` auf 4GB hoch zu setzen.

**Comment by Fra298** [comment]
well, error report was wrong, this error was before increasing memory_limit to 2048M. I tested with 2GB and 4 GB and error report is the same : 

`Allowed memory size of 2097152 bytes exhausted (tried to allocate 32768 bytes) in C:\xampp\htdocs\aowow\includes\basetype.class.php on line 346`

**Comment by Sarjuuk** [comment]
If this is still relevant after the recent updates, feel free to reopen the issue.

**Comment by electricmessiah** [comment]
I'm having the same issue. I've increased RAM to 8GB on the server from 4GB and set all the limits. Performance monitor shows the memory start to be consumed at an alarming rate and then it crashes way before it ever reaches the limit.

**Comment by Sarjuuk** [comment]
That's exactly 1.5GB of memory. Maybe you have another limit somewhere else?

**Comment by electricmessiah** [comment]
I know, but this is a default copy of XAMPP and I checked everywhere including all of the files in this repo. I found nothing. I ended up editing the progress file and incrementing the step to move past it. I then got hung up on that script for converting the MP3 files that did some I left you a snarky comment on. :P

**Comment by Sarjuuk** [comment]
> Windows
> XAMPP
Then 2gig it is.. ;>

Yeah sorry, at the moment I don't have the time to really dig into issues like this one. Though, if you find something I'll probably commit it.

**Comment by lyrl** [comment]
Do Not Use Embed PHP In Xampp 

Download 64Bit Version PHP，Will solve It.
