### ISSUE TITLE
Error in select call in items.func.php

### ISSUE THREAD

**Issue by mwondere** [Sarjuuk/aowow#71]
In you current code you use:

while ($items = DB::World()->select($baseQuery, $lastMax, $ids ?: DBSIMPLE_SKIP, $offset, SqlGen::$stepSize))

You changed this in your last commit. $offset is still in this code while not used / initialized anymore. Resulting in failure of this total function. Remove the parameter (reducing number of parameters once again to three) and it works.

This also corrected the FileGen Glyph problem for me (issue #69). It could not handle an empty item table.

Keep up the good work!

**Comment by Sarjuuk** [comment]
dang, you are right.
thanks!
