### ISSUE TITLE
Informations for Vanilla/BC donjon and raids

### ISSUE THREAD

**Issue by Killyana** [Sarjuuk/aowow#73]
After https://github.com/Sarjuuk/aowow/commit/dcff6f6525ee9fa9ad85045cd67b90221e4a1527 zones for non wotlk donjon are shown, but informations like: NPCs, Objects, Starts quest are not listed.
only Fishing, spells and zones are there.

**Comment by Sarjuuk** [comment]
currently you need the zones dimensions/map to relate anything to it (which none of the classic/BC Dungeons/Raids have). But since these are  .. well .. instances of a map, this check is probably sufficient.

**Comment by Endalaust** [comment]
What do you mean about "zones dimensions" ?

**Comment by Sarjuuk** [comment]
worldmaparea.dbc left, right, top and bottom world coordinates, which each zone zone map relates to. (and for dungeons dungeonmap.dbc)
And, as i said, those instances don't have displayable maps, so they have no entries in these DBCs
