### ISSUE TITLE
Feature request: sound id names

### ISSUE THREAD

**Issue by Kittnz** [Sarjuuk/aowow#74]
See the name of the sound id.
?spell=75767 shows Play Music: (17487).

On wowhead you can see the name and actually play the sound file.
http://www.wowhead.com/spell=75767/dnd-music
Event-GnomereganEventComplete

This way, it's easyier to see what soundid if for what. Quicker scripting and finding what is what.

**Comment by Sarjuuk** [comment]
somewhere in between maps for quests, icon db and profiler there is surely room for the sound db

**Comment by Kittnz** [comment]
http://www.wowhead.com/sounds

**Comment by Sarjuuk** [comment]
f*** it, lets try this..

- [ ] setup
  - [x] create database structure & content
  - [ ] file extraction, conversion & placement
- [ ] display
  - [x] detail page
  - [x] list page
  - [ ] playlist page
  - [ ] integrate player into spell detail page
- [ ] cross referencing
  - [ ] spells (effect: play sound, general usage sounds)
  - [ ] creature (dialog, activity sounds)
  - [ ] zones (ambient, music)
  - [ ] race (activity sounds, error messages, emotes)
  - [ ] items (pickup/dropdown, weapon hits)

**Comment by Kittnz** [comment]
Seems like this can be closed now.
