### ISSUE TITLE
tooltips

### ISSUE THREAD

**Issue by kvipka** [Sarjuuk/aowow#75]
In fresh version aowow tooltips are empty

adress:aowow/?tooltips
- empty

**Comment by Sarjuuk** [comment]
What are you trying to accomplish? There is no page tooltips. Tooltips can be displayed for most db entries, but are not on a page for themselves. 
Could you be more specific?

**Comment by kvipka** [comment]
Yep. Look at this.
http://imgur.com/BEpU8TH

This is https://github.com/Sarjuuk/aowow/commit/674a2a78146e6dea06969be0cc9ccee57220469a revision

**Comment by Sarjuuk** [comment]
the page looks alright...

do you mean, the javascript you can include on other pages `localhost/static/widgets/power.js` is missing..?

**Comment by kvipka** [comment]
nope, it's only my mistake.

I updated from repo of trinitycore, and they haven't your last commit. Sorry, my mistake
