### ISSUE TITLE
Default language

### ISSUE THREAD

**Issue by tortosi** [Sarjuuk/aowow#76]
How i change the default language to Spanish? 
Can put only one language? I changed to database the flag to 64 (only spanish) but appear english too

**Comment by Sarjuuk** [comment]
For the first time language is determined by the request header the server receives. From here on forth it is saved in a cookie.

You can restrict the available languages as you've already discovered. Now if you rebuild the language menu `php aowow --build=locales` this is also reflected there.

I just noticed, that english can never by deselected. This is a bug.

**Comment by Sarjuuk** [comment]
aaand it should be fixed. (ab8d7caced30e3a811bb8f4103b604231ea28c3d)

Feel free to reopen this ticket, if the problem should persist.
