### ISSUE TITLE
Parse Error BUTTON_LINKS on pages/quest.php

### ISSUE THREAD

**Issue by Endalaust** [Sarjuuk/aowow#79]
https://github.com/Sarjuuk/aowow/commit/090410cbf854e45425753a84e5dc9c1d17190c03#diff-7de027659de69b0071d37b249fc2b161

PHP Parse error:  syntax error, unexpected 'BUTTON_LINKS' (T_STRING), expecting ')' in /var/www/xxx/pages/quest.php on line 563

**Comment by Sarjuuk** [comment]
fixed in 99760d7c7266668318a2f578c0d31bd6c2270ed9
