### ISSUE TITLE
PHP5.5 compatibility

### ISSUE THREAD

**Issue by Endalaust** [Sarjuuk/aowow#80]
You are very kind to work on php 5.5 compatibility, but the last commit is not enough (unfortunatly)

https://github.com/Sarjuuk/aowow/blob/da5944010686a5fe9bdf301f6cfbdd4c6de5af33/includes/ajaxHandler/admin.class.php#L175

[Sat Feb 25 09:15:11.984654 2017] [:error] PHP Parse error:  syntax error, unexpected ')', expecting ']' in /var/www/aowow/includes/ajaxHandler/admin.class.php on line 175

Thank you so much for your devotion

**Comment by Sarjuuk** [comment]
just a(nother) typo

**Comment by Sarjuuk** [comment]
3b1bcfe1a5883509c15949ceb49999ff7543b572

[Bah, try this](http://media.services.zam.com/v1/media/byName/hs/sounds/enus/VO_EX1_398_Play_01.ogg)
