### ISSUE TITLE
Item gives Timeout

### ISSUE THREAD

**Issue by Kittnz** [Sarjuuk/aowow#81]
aowow/?item=47241

Fatal error: Maximum execution time of 30 seconds exceeded in E:\xampp\htdocs\wow\aowow\includes\libs\DbSimple\Mysqli.php on line 162

**Comment by Sarjuuk** [comment]
note to self:
ginormous amount of sql-querys when collecting data for tab "currency for"

**Comment by Sarjuuk** [comment]
fixed in 8fcd8ea429886eaefd457395cd24868abae4c94b
