### ISSUE TITLE
Structure of "spell_enchant_proc_data" has been changed

### ISSUE THREAD

**Issue by Endalaust** [Sarjuuk/aowow#83]
TrinityCore commit:
https://github.com/TrinityCore/TrinityCore/blob/f609e7a08b3b4d2d9642e5ec252e1eedad836f0f/sql/updates/world/3.3.5/2017_02_21_02_world.sql

Your func:
https://github.com/Sarjuuk/aowow/blob/master/setup/tools/sqlgen/itemenchantment.func.php#L26

Should edit pages/spell.php like this:
https://github.com/TrinityCore/aowow/commit/717728f71cb5c688adacd57d8cf3c05e310fe559

**Comment by Sarjuuk** [comment]
ty, 
should be fixed in fce8b014937357f72ea7c5313338216fd6ff0194
