### ISSUE TITLE
Traduction FR: Requière = Requiert

### ISSUE THREAD

**Issue by Endalaust** [Sarjuuk/aowow#85]
https://github.com/Sarjuuk/aowow/blob/20a1829317c365074af4ef48a25b06e4982f736b/static/js/locale_frfr.js

You have 3 "Requière" in this file
The good word is: "Requiert"

See ya

**Comment by Sarjuuk** [comment]
are you sure ..?
It's not my translation, but how 'red smiling rock'-site translated it.

Granted, they are not perfect. I already corrected a couple of iffy cases for German...

**Comment by Endalaust** [comment]
Well, "requière" is subjcontif (subjonctive) in French. 
The subjunctive is a grammatical mode expressing a fact thought or imagined, in contrast to the indicative, which is supposed to relate the actual facts.

The verb requires, is oriented on the obligation and the real facts, and not a fact thought or imagined. You agree ? For exemple, when a quest is required to do another one, **we have to** do the first. So the indicative is more appropriate than the subjonctive, because its a real fact and not imagined.

You can find a table about this verb and conjugation (in FR): 
http://leconjugueur.lefigaro.fr/conjugaison/verbe/requerir.html
The first one is Indicative (Indicatif), and the second is subjcontive (subjcontif)

**Comment by Sarjuuk** [comment]
while reading this link derelict memories of my school lessons in french crawled out of the darkest corners of my mind and started to mock me......

... anyway while you are at it, are there maybe similar cases in [localization/locale_frfr.php](https://github.com/Sarjuuk/aowow/blob/master/localization/locale_frfr.php)? If so, id like to fix them in the same manner.

**Comment by Endalaust** [comment]
Mhmm
https://github.com/Sarjuuk/aowow/blob/master/localization/locale_frfr.php#L514 (russian ?)
That's all i can find..

And just to confirm my opinion about subjcontive and indicative:
https://github.com/Sarjuuk/aowow/blob/master/localization/locale_frfr.php#L28 (it's "requiert") ;)

I told you I had a translator working on the article table. I gave him the file to check later. I would open another issue if she found something.

Amandil.

**Comment by Sarjuuk** [comment]
> https://github.com/Sarjuuk/aowow/blob/master/localization/locale_frfr.php#L514 (russian ?)

what the...?

**Comment by Sarjuuk** [comment]
added changes locale strings.
as for the article translations, please get back to me on IRC.
