### ISSUE TITLE
about project process

### ISSUE THREAD

**Issue by qyh214** [Sarjuuk/aowow#86]
When this project support 335.60,I have test and well.After tc updated to 335.62,I did not follow up the project,Recently, I was surprised to find that the project was updated. then I test but meet some serious problems:

- In my one pc it's used xmapp 5.6(Apache 2.4.25, MariaDB 10.1.21, PHP 5.6.30, phpMyAdmin 4.6.5.2, OpenSSL 1.0.2, XAMPP Control Panel 3.2.2, Webalizer 2.23-04, Mercury Mail Transport System 4.63, FileZilla FTP Server 0.9.41, Tomcat 7.0.56 (with mod_proxy_ajp as connector), Strawberry Perl 7.0.56 Portable).I setup but it's coming database can not connect but database seems well,and I go to this site and I got 500 error,Preliminary confirmation of the problem in a file: includes/kernel.php#65 and it maybe get wrong values.

- In my another pc.it's used xampp 7.1(Apache 2.4.25, MariaDB 10.1.21, PHP 7.1.1, phpMyAdmin 4.6.5.2, OpenSSL 1.0.2, XAMPP Control Panel 3.2.2, Webalizer 2.23-04, Mercury Mail Transport System 4.63, FileZilla FTP Server 0.9.41, Tomcat 7.0.56 (with mod_proxy_ajp as connector), Strawberry Perl 7.0.56 Portable).can setup well and I go to like http://127.0.0.1/aowow/ and I can see site is `The website is currently closed for maintenance.` but after `php aowow --firstrun` and have set db config,it is stop!!
then I use  `php aowow --sql` and shows like:
![20170320220615](https://cloud.githubusercontent.com/assets/3896160/24103196/784d8780-0db9-11e7-8bbc-c296859263a0.png)
and yes! it's stop!

so I want to know that the project is still in the development and is not stable(Compared with 335.60), and these errors are known?

In addition, I am very willing to contribute to the project in my spare time, such as the completion of simplified Chinese and traditional Chinese translation, I hope the author(you) can complete the adaptation in the code(e.g:add *_loc4,loc5 and add all related placeholders,for example you can copy lang_enus to lang_zhcn,and then I will start translate and in all code add loc4,loc5), I would also like to test simplified Chinese and traditional Chinese.

**Comment by Sarjuuk** [comment]
Hm, haven't run it on my windows box in ages. i'll have to recheck on it.

500 is Internal Error though. Thats most likely some misconfiguration on your end.
At any rate, set debug=1 in aowow_config, manually if you have to and add a php config `display_errors=1` anywhere you like.

Without a proper error, this guesswork is moot.

**Comment by qyh214** [comment]
I have 335 zhcn client,but I don't know if you can download it.
this is bt link:
https://mega.nz/#!AwJVgJJY!JBxGGRuL3dyIS1Sw3t0J3s7LFEyMr3LEaZxTYdCNF8k

If you only want to zhcn dbc,this link:
https://mega.nz/#!dl4Q1JDR!IxwneWcZUnhzNP2o1drHcJFHFul3Q2JOIGK8SoSUs50

**Comment by Sarjuuk** [comment]
ty

https://github.com/Sarjuuk/aowow/blob/master/includes/kernel.php#L80 would be the first time the DB is accessed. Which would be in line with what you described.

**Comment by qyh214** [comment]
Now I use xampp 7.1(php 7.1)to test:
![20170321203105](https://cloud.githubusercontent.com/assets/3896160/24147561/be52f802-0e75-11e7-9047-dbc1041efce3.png)
you can see errors and stop

**Comment by Sarjuuk** [comment]
wait a sec. 
why is your limit 2GB. I defaulted it to 4GB a while ago.

try increasing it to 4GB (yes i know, the code is not very optimized)

**Comment by qyh214** [comment]
I have check in aowow.aowow_config memory_limit is right:4096m,but like image only 2G
I guess: system limit?
I tried modify php.ini memory_limit But useless
so……I should use unix like ubuntu?

**Comment by Sarjuuk** [comment]
finally managed to recreate my local setup much to the same result.
it is possible that this is due to memory limitations of the 32bit php xampp provides. Then again, aowow ran just fine on it beforehand. 

needs more investiagation.

**Comment by Sarjuuk** [comment]
good news / bad news:

**good news**: we are stupid and 2097152 bytes are 2MB not 2GB. That is apparently the default value that gets set for memory_limit if the entered value is not accepted. (and on 32bit systems anything > 2GB is not acceptable) So set memory_limit to 1900M or something and it should work.

**bad news**: php crashes anyway. at first i thought it were my changes to the DBC handler and it had issues with keeping 6 handles open at the same time and bouncing back and forth between stringBlock and dataBlock within them but reverting that commit concludes with the same crash. 

eh .. need to look into it more.
