### ISSUE TITLE
Items not available for players

### ISSUE THREAD

**Issue by tortosi** [Sarjuuk/aowow#90]
All items that are farmed from npc appear that are not available by the players and does not show that npc drop those items

![captura de 2017-03-28 12-48-17](https://cloud.githubusercontent.com/assets/160920/24401603/5238037a-13b5-11e7-93ac-50b5ae5c298e.png)

**Comment by Sarjuuk** [comment]
hm, apparently i forgot to push that.

**Comment by tortosi** [comment]
I enable Debug mode and in terminal with the command php aowow --sql=source i obtain these error:

`DB ERROR:

Array
(
    [code] => 1055
    [message] => Expression #3 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'world_wotlk.it.entry' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
    [query] => 
        SELECT
            rlt.Entry AS ARRAY_KEY,
            IF(Reference, -Reference, Item) AS ARRAY_KEY2,
            it.entry, it.class, it.subclass, it.spellid_1, it.spelltrigger_1, it.spellid_2, it.spelltrigger_2,
            COUNT(1) AS qty
        FROM
            reference_loot_template rlt
        LEFT JOIN
            item_template it ON rlt.Reference = 0 AND rlt.Item = it.entry
        GROUP BY
            ARRAY_KEY, ARRAY_KEY2
    
    [context] => /home/editweb/www/head/setup/tools/sqlgen/source.func.php line 132
)
`

And in web i obtain theese:
`DB ERROR:

Array
(
    [code] => 1055
    [message] => Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'world_wotlk.lt1.Entry' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
    [query] => SELECT
                            lt1.entry AS ARRAY_KEY,
                            IF(lt1.reference = 0, lt1.item, lt1.reference) AS item,
                            lt1.chance,
                            SUM(IF(lt2.chance = 0, 1, 0)) AS nZeroItems,
                            SUM(lt2.chance) AS sumChance,
                            IF(lt1.groupid > 0, 1, 0) AS isGrouped,
                            IF(lt1.reference = 0, lt1.mincount, 1) AS min,
                            IF(lt1.reference = 0, lt1.maxcount, 1) AS max,
                            IF(lt1.reference > 0, lt1.maxcount, 1) AS multiplier
                        FROM
                            `reference_loot_template` lt1
                        LEFT JOIN
                            `reference_loot_template` lt2 ON lt1.entry = lt2.entry AND lt1.groupid = lt2.groupid
                        WHERE
                            lt1.item = 4306 AND lt1.reference = 0
                        GROUP BY lt2.entry, lt2.groupid
    [context] => /var/www/head/includes/loot.class.php line 434`

**Comment by Sarjuuk** [comment]
>  sql_mode=only_full_group_by
i'll have to do some reading up on that

**Comment by Sarjuuk** [comment]
probably fixed in 4651165e4d415167f6eef4e755c2a5e63ce59ba6

please check

**Comment by tortosi** [comment]
That's ok!!

Thanks!
