### ISSUE TITLE
PHP Parse Error in genericPage.class.php

### ISSUE THREAD

**Issue by Endalaust** [Sarjuuk/aowow#92]
try `php aowow` in the shell

PHP Parse error:  syntax error, unexpected '::' (T_PAAMAYIM_NEKUDOTAYIM) in aowow/pages/genericPage.class.php on line 294

Application doesnt work too, ofc

**Comment by Sarjuuk** [comment]
...i should really deprecate usage of php5

**Comment by Sarjuuk** [comment]
should be fixed in e5de7a8a4583d75e833fa84f597b9aa6ed21f97e
