### ISSUE TITLE
Update to Readme

### ISSUE THREAD

**Issue by knuxyl** [Sarjuuk/aowow#93]
Since Sounds from MPQ is just a big folder, I have put together a script to go through all convert all files and delete the originals since the .wav are so big.

`find -name "*.wav" | xargs -I % sh -c 'ffmpeg -hide_banner -y -i "%" -acodec libvorbis "%.ogg"; rm "%";' && find -name "*.mp3" | xargs -I % sh -c 'ffmpeg -hide_banner -y -i "%" -f mp3 -acodec libmp3lame "%.mp3"; rm "%";'`

**Comment by Sarjuuk** [comment]
I believe i originally used xargs to link find and ffmpeg but for some reason it skipped over half of the files.
using -exec it just worked, and i never bothered to find out why.

I'll have to recheck that.

**Comment by knuxyl** [comment]
Yeah I was going to use -exec but I couldn't find a way to execute multiple commands on the file, the convert then delete
