### ISSUE TITLE
Spell: Wrong data for some spells

### ISSUE THREAD

**Issue by Killyana** [Sarjuuk/aowow#94]
For some spells like https://woehead.way-of-elendil.fr/?spell=31872
There's https://db.rising-gods.de/?spell=11 on effect 3
It looks like the misc = 11 (11) is interprated like a spell ID, but it's not the case

Effect 2: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 100
Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)
Aura Id 4 (SPELL_AURA_DUMMY), value = 100, misc = 11 (11), miscB = 0, periodic = 0

**Comment by Sarjuuk** [comment]
ok, so a dummy aura can't use its miscValue as procSpell

things, that can trigger spells:
effects:  3, 32,  64, 101, 142, 148, 151, 152, 155, 160, 164
dummy, trigger missile, trigger spell, feed pet, force cast, force cast with value, unk, trigger spell 2, unk, dualwield 2H, unk, remove aura
auras: 4, 23, 42, 48, 109, 226, 227, 231, 236, 284
dummy; 23/227: periodic trigger spell (with value); 42/231: proc trigger spell (with value); 48: unk; 109: add target trigger; 226: periodic dummy; 236: control vehicle; 284: linked

is there an easy way to get, what effect/aura can use its miscValue as spell and what cannot?

**Comment by Sarjuuk** [comment]
fixed in 92394e415afdfded32fbae92fa4e990dc9a908ce
