### ISSUE TITLE
Icon preview with power.js

### ISSUE THREAD

**Issue by Endalaust** [Sarjuuk/aowow#95]
Since your last update about Icon, we dont have icon preview with hover on aowow link

Demo : https://way-of-elendil.fr/event/mariage.html (You have a lot link to DB in this page)
If you put your pointer on a link from DB, icon place is empty inside preview
Like that: http://screens.way-of-elendil.fr/sz9FC7N4.jpg

Just to know: When I add `rel="domain=fr"`, it's broken. If i remove this, should be OK

**Comment by Sarjuuk** [comment]
your icon names are in square brackets ... why though..

**Comment by Endalaust** [comment]
Yeah. Error in basic.js. Maybe with that.. https://github.com/Sarjuuk/aowow/commit/ee568da6ec75587d29daf8a10be0b605b92eed1a#diff-a15a48e26d26b9fff1a595a80acd7071

**Comment by Sarjuuk** [comment]
should be fixed in acad94770b63a6608e82ad02c2710a830f68f058
