### ISSUE TITLE
Do not know how to install?

### ISSUE THREAD

**Issue by DarkmoonRabbit** [Sarjuuk/aowow#97]
Hello, can you provide a complete installation video or graphic tutorial?

**Comment by madmax765** [comment]
that would be nice.. And i use windows... I Wish i had the doc's to install this.. been wanting to for years now

**Comment by Sarjuuk** [comment]
what the .. *no*!

Seriously, what step is still unclear. Yes this project requires at least superficial knowledge of the data structures in wow. (e.g. you should have set up a TrinityCore, MaNGOS server or related at least once).

The other tools aren't even a requirement, but a suggestion. You can use whatever you like as long as the end result is the same. In that vein; it is pointless to provide tutorials on those, as the process will be different.

Windows and php7 currently have an issue where you run out of memory unreasonably fast. So far i had no luck pinning that down. Just something to keep in mind.

there are a couple of threads over at https://community.trinitycore.org, but nothing substantial.

**Comment by Kittnz** [comment]
Let's face it, there won't be an easy installer for aowow. Reason is because we need data to be extracted and sounds to be converted.

**Comment by Dokman** [comment]
@Kittnz it's not so difficult but it needs time and a verter like ffmpeg or something like this

**Comment by Sarjuuk** [comment]
Again, tell me how you'd improve on the instructions and i'll most likely do it. If not, i'm done with this topic.

**Comment by Dokman** [comment]
@Sarjuuk is not your problem :D he/she refers to for example make

### 1 - Do Something
Here i explain something

**Comment by Sarjuuk** [comment]
and nothing came of it...
