### ISSUE TITLE
filegen is not updated with new database

### ISSUE THREAD

**Issue by Endalaust** [Sarjuuk/aowow#98]
Hello Sarjuuk,

Since your last edition of your database (icons), script to generate content is not updated with your last modifications

Fiew examples (but maybe not all, im sorry) :  
setup/tools/filegen/glyphs.func.php line 44
setup/tools/filegen/enchants.func.php line 77
[message] => Unknown column 'ic.iconString' in 'field list

Thanks a lot

**Comment by Sarjuuk** [comment]
fixed in 0360f6f600d59ff380469d1d8ffc0892cff9449a
