### ISSUE TITLE
[Error]?_table not work

### ISSUE THREAD

**Issue by Dokman** [Sarjuuk/aowow#99]
So yes if i use in windows with xampp ?_table not work but if use nametable_table works, why?

**Comment by Dokman** [comment]
Okay the problem is the table structure that has a prefix and if you remove the aowow_ prefix works perfectly
@Sarjuuk please fix it :)

**Comment by Sarjuuk** [comment]
Or, you know .. you set the prefix when asked by the setup.

On second thought, why is this configurable anyways. I will probably drop support for this....

**Comment by Dokman** [comment]
@Sarjuuk one question why is so slow, when i try to get data from the webpage?

**Comment by Dokman** [comment]
it's consuming like 2GB of ram the httpd.exe process why :(

**Comment by Dokman** [comment]
and when finish there is what i has 
![image](https://cloud.githubusercontent.com/assets/2290904/24837436/5895107c-1d34-11e7-9503-c74146fe4e6a.png)

**Comment by Sarjuuk** [comment]
I don't think you finished the setup.
Try firstrun again and resume if asked to. If it doesn't work at least give some basic information when, where and why it fails.

**Comment by Dokman** [comment]
@Sarjuuk it fails with alll okay, the problem is that when parse a bunch of worldmaps fails and tell me that the GlobalString or whatever the name of that lua file is is not in other languages but in spanish is in there, so... i don't know what fails, and when i go into the webpage my httpd.exe it starts to consume like 1,6GB of ram

**Comment by Sarjuuk** [comment]
the heck...?
?items=2.7 is displayed in milliseconds for me.

what does `php -v` return for you?

**Comment by Dokman** [comment]
![image](https://cloud.githubusercontent.com/assets/2290904/24842037/85fff880-1d91-11e7-972a-5b6430dd3b2f.png)

**Comment by Dokman** [comment]
idk what's happening and why is eating my ram xDDDD

**Comment by Sarjuuk** [comment]
oh, windows.

yeah, doesn't work for now. Windows, Aowow and php7 don't go well with each other.

**Comment by Dokman** [comment]
what i can do?
go under php 5.x?

**Comment by Sarjuuk** [comment]
closed, since the table-prefix changed in fa9d518980c30a9458d0353f3eb7936652f1eb8f
and the windows-thing is a highjack anyway. ref to #101
